apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
#      version: 4.0.36
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: ${WW_ADMIN_PASSWORD}
    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: Weave Gitops
        hajimari.io/icon: simple-icons:git
        hajimari.io/group: infrastructure
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: &host "ww.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
