---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rutorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  timeout: 15m
  values:
    controllers:
      rutorrent:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              storageClass: iscsi
              accessMode: ReadWriteOnce
              size: 5Gi
        containers:
          rutorrent:
            image:
              repository: ghcr.io/crazy-max/rtorrent-rutorrent
              tag: "5.2.10-0.15.5"
            env:
              TZ: ${CONFIG_TIMEZONE}
            resources:
              requests:
                cpu: 700m
                memory: 1000Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 2800Mi
                ephemeral-storage: 200Mi
    service:
      rutorrent:
        controller: rutorrent
        ports:
          http:
            port: 8080
      bittorrent:
        controller: rutorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.20.108
        externalTrafficPolicy: Local
        ports:
          rutorrent:
            enabled: true
            port: 50000
            protocol: TCP
    ingress:
      rutorrent:
        className: private
        hosts:
          - host: &host ru.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: rutorrent
                  port: http
        tls: [hosts: [*host]]
    persistence:
      downloads:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /downloads
      addons:
        type: emptyDir
        globalMounts:
          - path: /passwd
      data:
        type: emptyDir
        globalMounts:
          - path: /data
