---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  path: ./cluster/apps/db/cloudnative-pg/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: nfs
    - name: replicator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: flux-system
spec:
  path: ./cluster/apps/db/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cloudnative-pg
