---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              storageClass: iscsi
              accessMode: ReadWriteOnce
              size: 5Gi
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
              pullPolicy: IfNotPresent
            env:
              INIT_POSTGRES_HOST: "postgres-rw.database.svc.cluster.local"
              INIT_POSTGRES_SUPER_PASS: "${SECRET_PG_PASSWORD}"
              INIT_POSTGRES_USER: "radarr"
              INIT_POSTGRES_PASS: "${RADARR_PG_PASSWORD}"
              INIT_POSTGRES_DBNAME: radarr_main radarr_log
          securityContext:
            runAsUser: ${CONFIG_APP_UID}
            runAsGroup: &gid ${CONFIG_MEDIA_UID}
            fsGroup: *gid
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.1.3.8246
            env:
              TZ: Europe/Warsaw
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 80
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__APPLICATION_URL: "https://movies.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
              RADARR__THEME: dark
              RADARR__POSTGRES_MAIN_DB: radarr_main
              RADARR__POSTGRES_LOG_DB: radarr_log
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
              resources:
                requests:
                  cpu: 50m
                  memory: 200Mi
                limits:
                  memory: 500Mi
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            retain: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host "movies.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host
