---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: ingress-nginx
      namespace: network
    - name: nfs
      namespace: storage
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              storageClass: nfs
              accessMode: ReadWriteOnce
              size: 5Gi
        annotations:
          secret.reloader.stakater.com/reload: cluster-secrets
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.1
              pullPolicy: Always
            env:
              INIT_POSTGRES_HOST: &dbHost "postgres-rw.database.svc.cluster.local"
              INIT_POSTGRES_SUPER_PASS: "${SECRET_PG_PASSWORD}"
              INIT_POSTGRES_USER: &dbUser "radarr"
              INIT_POSTGRES_PASS: &dbPass "${RADARR_PG_PASSWORD}"
              INIT_POSTGRES_DBNAME: radarr_main radarr_log
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 300Mi
                ephemeral-storage: 5Gi
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.2.6.8376
              pullPolicy: Always
            env:
              TZ: Europe/Warsaw
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__AUTHENTICATION_METHOD: External
              RADARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__APPLICATION_URL: "https://movies.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
              RADARR__THEME: dark
              RADARR__POSTGRES_MAIN_DB: radarr_main
              RADARR__POSTGRES_LOG_DB: radarr_log
              RADARR__API_KEY: &API_KEY "${RADARR_API_KEY}"
              RADARR__POSTGRES_HOST: *dbHost
              RADARR__POSTGRES_PORT: "5432"
              RADARR__POSTGRES_USER: *dbUser
              RADARR__POSTGRES_PASSWORD: *dbPass
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 500Mi
                ephemeral-storage: 5Gi
    service:
      main:
        ports:
          http:
            port: 80
            targetPort: *port
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            retain: true
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Radarr
          gethomepage.dev/icon: radarr.svg
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: http://radarr.media
          gethomepage.dev/widget.key: *API_KEY
        enabled: true
        hosts:
          - host: &host "movies.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host
