---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/node-feature-discovery/app
  sourceRef:
    kind: GitRepository
    name: homelab
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname node-feature-discovery
  prune: true
  wait: true
  interval: 10m
