---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      qbittorrent:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              storageClass: iscsi
              accessMode: ReadWriteOnce
              size: 5Gi
        containers:
          qbittorrent:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: "5.0.4"
            env:
              TZ: ${CONFIG_TIMEZONE}
              QBITTORRENT__PORT: &port 1080
              QBITTORRENT__BT_PORT: &bittorrentPort 50413
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    resource: limits.memory
                    containerName: qbittorrent
                    divisor: 1Mi
              QBT_Preferences__WebUI__AlternativeUIEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.244.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__RootFolder: /addons/VueTorrent
              QBT_Preferences__WebUI__UseUPNP: false
              QBT_BitTorrent__Session__Interface: eth0
              QBT_BitTorrent__Session__InterfaceAddress:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              QBT_BitTorrent__Session__InterfaceName: eth0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 700m
                memory: 1000Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 2800Mi
                ephemeral-storage: 200Mi
          vuetorrent:
            dependsOn: qbittorrent
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.5.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 1Gi
                ephemeral-storage: 200Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    service:
      qbittorrent:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      qbittorrent:
        className: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: QBittorrent
          gethomepage.dev/icon: qbittorrent.svg
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent.media:1080
        hosts:
          - host: q.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: qbittorrent
                  port: http
        tls:
          - hosts:
              - q.${SECRET_DOMAIN}
    persistence:
      downloads:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /downloads
            subPath: Downloads
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons

