---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      qbittorrent:
        type: statefulset
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: "4.6.4"
            env:
              TZ: ${CONFIG_TIMEZONE}
              QBITTORRENT__PORT: &port 1080
              QBITTORRENT__BT_PORT: &bittorrentPort 50413
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    resource: limits.memory
                    containerName: app
                    divisor: 1Mi
              QBT_Preferences__WebUI__AlternativeUIEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.244.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__RootFolder: /addons/VueTorrent
              QBT_Preferences__WebUI__UseUPNP: false
              QBT_BitTorrent__Session__Interface: eth0
              QBT_BitTorrent__Session__InterfaceAddress:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              QBT_BitTorrent__Session__InterfaceName: eth0
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup:
                enabled: false
#            probes:
#              liveness: &probes
#                enabled: true
#                custom: true
#                spec:
#                  httpGet:
#                    path: /api/v2/app/version
#                    port: *port
#                  initialDelaySeconds: 0
#                  periodSeconds: 10
#                  timeoutSeconds: 5
#                  failureThreshold: 3
#              readiness: *probes
#              startup:
#                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 500Mi
              limits:
                memory: 8152Mi
          vuetorrent:
            dependsOn: app
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.2.1
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
              limits:
                memory: 50Mi
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
      bittorrent:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.20.105
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: *bittorrentPort
            protocol: TCP
    ingress:
      app:
        className: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: QBittorrent
          gethomepage.dev/icon: qbittorrent.svg
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent-app.downloads
        hosts:
          - host: &host q.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls: [hosts: [*host]]
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          qbittorrent:
            main:
              - path: /config
      downloads:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /downloads
            subPath: Downloads
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
