---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      qbittorrent:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              storageClass: iscsi
              accessMode: ReadWriteOnce
              size: 5Gi
        initContainers:
          vuetorrent:
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.5.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --root=/addons
              - --one-time
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 1Gi
                ephemeral-storage: 200Mi
          config:
            dependsOn: vuetorrent
            image:
              repository: docker.io/library/alpine
              tag: 3.21.2
            command:
              - /bin/sh
              - -c
            args:
              - |
                CONFIG_FILE="/config/qBittorrent/qBittorrent.conf"
                RSS_DIR="/config/qBittorrent/rss"
                FEEDS_FILE="$RSS_DIR/feeds.json"

                # Create config file if it doesn't exist
                if [ ! -f "$CONFIG_FILE" ]; then
                  mkdir -p /config/qBittorrent
                  echo "[Preferences]" > "$CONFIG_FILE"
                fi

                # Ensure [Preferences] section exists
                if ! grep -q "^\[Preferences\]" "$CONFIG_FILE"; then
                  echo "[Preferences]" >> "$CONFIG_FILE"
                fi

                # Remove existing WebUI alternate settings if present
                sed -i '/^WebUI\\AlternativeUIEnabled=/d' "$CONFIG_FILE"
                sed -i '/^WebUI\\RootFolder=/d' "$CONFIG_FILE"
                sed -i '/^WebUI\\Port=/d' "$CONFIG_FILE"

                # Add the WebUI settings under [Preferences]
                sed -i '/^\[Preferences\]/a WebUI\\AlternativeUIEnabled=true\nWebUI\\RootFolder=/addons/VueTorrent\nWebUI\\Port=1080' "$CONFIG_FILE"

                # Configure RSS feeds using secret
                mkdir -p "$RSS_DIR"
                echo "{\"PTE\": {\"uid\": \"{a1b2c3d4-e5f6-7890-abcd-ef1234567890}\", \"url\": \"$${PTE_RSS}\"}}" > "$FEEDS_FILE"

                # Configure RSS auto-download rules
                cat > "$RSS_DIR/download_rules.json" << 'RULES_EOF'
                {
                    "Autodownload": {
                        "addPaused": false,
                        "affectedFeeds": [
                            "RSS_URL_PLACEHOLDER"
                        ],
                        "assignedCategory": "",
                        "enabled": true,
                        "episodeFilter": "",
                        "ignoreDays": 0,
                        "lastMatch": "",
                        "mustContain": "",
                        "mustNotContain": "",
                        "previouslyMatchedEpisodes": [],
                        "priority": 0,
                        "savePath": "/downloads",
                        "smartFilter": false,
                        "torrentContentLayout": "Original",
                        "torrentParams": {
                            "add_to_top_of_queue": false,
                            "category": "",
                            "content_layout": "Original",
                            "download_limit": 0,
                            "download_path": "",
                            "inactive_seeding_time_limit": -2,
                            "operating_mode": "AutoManaged",
                            "ratio_limit": -2,
                            "save_path": "/downloads",
                            "seeding_time_limit": -2,
                            "share_limit_action": "Default",
                            "skip_checking": false,
                            "ssl_certificate": "",
                            "ssl_dh_params": "",
                            "ssl_private_key": "",
                            "stop_condition": "None",
                            "stopped": false,
                            "tags": [],
                            "upload_limit": 0,
                            "use_auto_tmm": false,
                            "use_download_path": false
                        },
                        "useRegex": false
                    }
                }
                RULES_EOF
                sed -i "s|RSS_URL_PLACEHOLDER|$${PTE_RSS}|g" "$RSS_DIR/download_rules.json"

                echo "Config updated:"
                cat "$CONFIG_FILE"
                echo "RSS feeds and auto-download rules configured"
            env:
              PTE_RSS:
                valueFrom:
                  secretKeyRef:
                    name: kyoo
                    key: PTE_RSS
        containers:
          qbittorrent:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4
            env:
              TZ: ${CONFIG_TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 700m
                memory: 1000Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 2800Mi
                ephemeral-storage: 200Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    service:
      qbittorrent:
        controller: qbittorrent
        ports:
          http:
            port: 1080
      bittorrent:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.10.20.105
        ports:
          bittorrent-tcp:
            port: 50413
            protocol: TCP
          bittorrent-udp:
            port: 50413
            protocol: UDP
    ingress:
      qbittorrent:
        className: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: QBittorrent
          gethomepage.dev/icon: qbittorrent.svg
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent.media:1080
        hosts:
          - host: q.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: qbittorrent
                  port: http
        tls:
          - hosts:
              - q.${SECRET_DOMAIN}
    persistence:
      downloads:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /downloads
            subPath: Downloads
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons

