---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: net
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.18.2
      sourceRef:
        kind: HelmRepository
        name: certmanager
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    podDisruptionBudget:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    installCRDs: true
    image:
      pullPolicy: "Always"
    prometheus:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 150Mi
        ephemeral-storage: 200Mi
    cainjector:
      image:
        pullPolicy: "Always"
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 200Mi
          ephemeral-storage: 200Mi
    webhook:
      image:
        pullPolicy: "Always"
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 100Mi
          ephemeral-storage: 200Mi
