---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: network
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.13.2
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 3
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 50Mi
    startupapicheck.timeout: 5m

