---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: lab
spec:
  hosts:
    - ssh:
        address: 10.10.20.99
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
      files:
        - name: Prometheus CRDs
          src: stripped-down-crds.yaml
          dstDir: /var/lib/k0s/manifests/prometheus/
          perm: 0600
      installFlags:
        - --disable-components=metrics-server
        - --enable-metrics-scraper
    - ssh:
        address: 10.10.20.101
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 10.10.20.102
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 10.10.20.103
        user: root
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
  k0s:
    version: 1.31.2+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            repositories:
              - name: cilium
                url: https://helm.cilium.io
            charts:
              - name: cilium
                chartname: cilium/cilium
                version: "1.16.4"
                namespace: net
                values: |2
                  namespaceOverride: "net"
                  hubble:
                    enabled: true
                    metrics:
                      enabled:
                        - dns:query
                        - drop
                        - tcp
                        - flow
                        - port-distribution
                        - icmp
                        - http
                      serviceMonitor:
                        enabled: true
                    relay:
                      enabled: true
                      rollOutPods: true
                      prometheus:
                        serviceMonitor:
                          enabled: true
                      resources:
                        requests:
                          cpu: 10m
                          memory: 100Mi
                          ephemeral-storage: 100Mi
                        limits:
                          memory: 200Mi
                          ephemeral-storage: 200Mi
                    ui:
                      enabled: true
                      rollOutPods: true
                      backend:
                        image:
                          pullPolicy: Always
                        resources:
                          requests:
                            cpu: 10m
                            memory: 100Mi
                            ephemeral-storage: 100Mi
                          limits:
                            memory: 200Mi
                            ephemeral-storage: 200Mi
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities: {drop: ["ALL"]}
                      frontend:
                        image:
                          pullPolicy: Always
                        resources:
                          requests:
                            cpu: 10m
                            memory: 100Mi
                            ephemeral-storage: 100Mi
                          limits:
                            memory: 200Mi
                            ephemeral-storage: 200Mi
                        securityContext:
                          allowPrivilegeEscalation: false
                          readOnlyRootFilesystem: true
                          capabilities: {drop: ["ALL"]}
                image:
                  pullPolicy: "Always"
                bgpControlPlane:
                  enabled: true
                bgp:
                  enabled: false
                kubeProxyReplacement: true
                k8sServiceHost: 10.10.20.99
                k8sServicePort: 6443
                encryption:
                  enabled: true
                  type: wireguard
                  nodeEncryption: true
                operator:
                  replicas: 1
                  prometheus:
                    enabled: true
                    serviceMonitor:
                      enabled: true
                  resources:
                    requests:
                      cpu: 50m
                      memory: 100Mi
                      ephemeral-storage: 100Mi
                    limits:
                      memory: 200Mi
                      ephemeral-storage: 200Mi
                ipam:
                  mode: kubernetes
                  operator:
                    clusterPoolIPv4PodCIDR: 10.20.0.0/16
                    clusterPoolIPv4MaskSize: 24
                bpf:
                  masquerade: true
                prometheus:
                  enabled: true
                  serviceMonitor:
                    enabled: true
                resources:
                  requests:
                    cpu: 100m
                    memory: 400Mi
                    ephemeral-storage: 100Mi
                  limits:
                    memory: 600Mi
                    ephemeral-storage: 200Mi
                cgroup:
                  autoMount:
                    resources:
                      requests:
                        cpu: 100m
                        memory: 100Mi
                        ephemeral-storage: 100Mi
                      limits:
                        memory: 200Mi
                        ephemeral-storage: 200Mi
                cni:
                  resources:
                    requests:
                      cpu: 100m
                      memory: 100Mi
                      ephemeral-storage: 100Mi
                    limits:
                      memory: 200Mi
                      ephemeral-storage: 200Mi
                initResources:
                  requests:
                    cpu: 100m
                    memory: 100Mi
                    ephemeral-storage: 100Mi
                  limits:
                    memory: 200Mi
                    ephemeral-storage: 200Mi