---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  TALOS_DIR: "{{.ROOT_DIR}}/talos"
  CLUSTER_NAME: homelab
  TALOS_ISO_PATH: /tmp/talos.iso
  CLUSTER_TEMPLATE_PATH: "{{.ROOT_DIR}}/talos/homelab.yaml"

includes:
  cluster:
    taskfile: .taskfiles/cluster
    dir: .
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  format:
    dir: .taskfiles/format
    taskfile: .taskfiles/format
  precommit:
    dir: .taskfiles/precommit
    taskfile: .taskfiles/precommit
  talos:
    dir: .taskfiles/talos
    taskfile: .taskfiles/talos
  workstation:
    taskfile: .taskfiles/workstation
    dir: .

tasks:
  default:
    silent: true
    cmds: ["task -l"]
