---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator
spec:
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.31.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 30m
