---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dms
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      dms:
        type: deployment
        initContainers:
          setup-multicast:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                ip route add 224.0.0.0/4 dev enp3s0 || true
                echo "Multicast route added"
            securityContext:
              privileged: true
              capabilities:
                add: ["NET_ADMIN"]
        containers:
          dms:
            image:
              repository: ghcr.io/fenio/dms
              tag: latest
            args:
              - -path
              - /media
              - -friendlyName
              - "Homelab DMS"
              - -ifname
              - enp3s0
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      dms:
        controller: dms
        ports:
          http:
            port: 1338
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true
