---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dms
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      dms:
        type: deployment
        containers:
          dms:
            image:
              repository: docker.io/vladgh/minidlna
              tag: latest
            env:
              MINIDLNA_MEDIA_DIR: /media
              MINIDLNA_FRIENDLY_NAME: "Homelab DLNA"
              MINIDLNA_INOTIFY: "yes"
              MINIDLNA_NETWORK_INTERFACE: enp3s0
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      dms:
        controller: dms
        ports:
          http:
            port: 8200
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true
