---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dms
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      dms:
        type: deployment
        containers:
          dms:
            image:
              repository: ghcr.io/anacrolix/dms
              tag: latest
            args:
              - -path
              - /media
              - -friendlyName
              - "Homelab DMS"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      dms:
        controller: dms
        ports:
          http:
            port: 1338
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true
