apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vl
  namespace: monitor
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: vl
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
        ephemeral-storage: 1Gi
      limits:
        memory: 200Mi
        ephemeral-storage: 2Gi
    fluent-bit:
      enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 100Mi
          ephemeral-storage: 2Gi
        
