---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    controller:
      strategy: RollingUpdate
    hajimari:
      defaultEnable: false
      alwaysTargetBlank: true
      defaultSearchProvider: "Startpage"
      showAppGroups: true
      showAppUrls: false
      showAppStatus: false
      namespaceSelector:
        any: true
      title: "Start"
      globalBookmarks:
        - group: media
          bookmarks:
            - name: Youtube
              url: https://youtube.com
            - name: Odysee
              url: https://odysee.com
            - name: Rumble
              url: https://rumble.com
        - group: Tech
          bookmarks:
            - name: HackerNews
              url: https://news.ycombinator.com
            - name: Anandtech
              url: https://www.anandtech.com
            - name: Moronix
              url: https://www.phoronix.com
        - group: Social
          bookmarks:
            - name: Kiwifarms
              url: https://kiwifarms.net
            - name: Poast
              url: https://poa.st
            - name: zzzChan
              url: https://zzzchan.xyz
      searchProviders:
        - name: Startpage
          token: s
          icon: mdi:alpha-s
          searchUrl: https://www.startpage.com/sp/search?query={query}
          url: https://www.startpage.com
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "start.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: *host
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        memory: 100Mi
    persistence:
      data:
        enabled: false
