apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capacitor
  namespace: flux-system
spec:
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.3.2
              pullPolicy: Always
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    serviceAccount: 
      create: true
      name: "capacitor"
    service:
      controller: main
      main:
        ports:
          http:
            enabled: true
            port: 9000
    ingress:
      main:
        className: private
        enabled: true
        hosts:
          - host: &host capacitor.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: 80
        tls: [hosts: [*host]]

