---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
  labels:
    substitution.flux.home/enabled: "true"
spec:
  path: ./cluster/apps/network/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 3m
