---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minidlna
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    controllers:
      minidlna:
        type: deployment
        initContainers:
          setup-multicast:
            image:
              repository: docker.io/library/busybox
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                ip route add 224.0.0.0/4 dev enp3s0 || true
                echo "Multicast route added"
            securityContext:
              privileged: true
              capabilities:
                add: ["NET_ADMIN"]
        containers:
          minidlna:
            image:
              repository: docker.io/vladgh/minidlna
              tag: latest
            env:
              MINIDLNA_MEDIA_DIR: /media
              MINIDLNA_FRIENDLY_NAME: "DLNA"
              MINIDLNA_INOTIFY: "yes"
              MINIDLNA_NETWORK_INTERFACE: enp3s0
              MINIDLNA_NOTIFY_INTERVAL: "30"
              MINIDLNA_MODEL_NAME: "Windows Media Connect"
              MINIDLNA_ROOT_CONTAINER: "B"
              MINIDLNA_STRICT_DLNA: "yes"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      minidlna:
        controller: minidlna
        ports:
          http:
            port: 8200
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true
