---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
data:
  bookmarks.yaml: |
    - Tech:
        - HackerNews:
            - href: https://news.ycombinator.com
        - Anandtech:
            - href: https://www.anandtech.com
        - Moronix:
            - href: https://www.phoronix.com
        - ServeTheHome:
            - href: https://www.servethehome.com
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Calendar:
        # - Calendar:
        #     widget:
        #       type: calendar
        #       firstDayInWeek: sunday # optional - defaults to monday
        #       view: monthly # optional - possible values monthly, agenda
        #       maxEvents: 10 # optional - defaults to 10
        #       integrations: # optional
        #         - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Sonarr # service name for that widget
        #         - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Radarr # service name for that widget
        #         - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
        #           service_group: Downloads # group name where widget exists
        #           service_name: Readarr # service name for that
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Media # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Media # group name where widget exists
                  service_name: Radarr # service name for that widget
    - Automation:
        - Home Assistant:
            href: http://10.10.10.102:8123
            icon: home-assistant.svg
            widget:
              type: homeassistant
              url: http://10.10.10.102:8123
              key: ${HA_TOKEN}
    - Infrastructure:
        - TrueNAS:
            href: https://10.10.20.100
            icon: truenas.png
            description: NAS
            widget:
              type: truenas
              url: https://10.10.20.100
              key: ${TRUENAS_API_KEY}
        - Mikrotik:
            href: http://10.10.10.1:680
            icon: mikrotik.png
            description: Router
            widget:
              type: mikrotik
              url: http://10.10.10.1:680
              username: admin
              password: ${MIKROTIK_PASSWORD}
        - Synology:
            href: http://10.10.10.100
            icon: synology.png
            description: NAS
            widget:
              type: diskstation
              url: https://10.10.10.100:5001
              username: fenio
              password: ${SYNOLOGY_PASSWORD}
  settings.yaml: |
    title: Dashboard
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    theme: dark
    color: slate
    headerStyle: boxedWidgets
    layout:
      Media:
        style: row
        columns: 4
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: duckduckgo
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
          label: cluster
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - openmeteo:
        label: Home
        latitude: 49.82245
        longitude: 19.04686
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
