---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          configmap.reloader.stakater.com/reload: &configmap homepage
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.8.8
              pullPolicy: Always
            env:
              TZ: ${CONFIG_TIMEZONE}
              # LOG_LEVEL: debug
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    service:
      main:
        ports:
          http:
            enabled: true
            port: 3000
    ingress:
      main:
        className: private
        enabled: true
        hosts:
          - host: &host h.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls: [hosts: [*host]]
    persistence:
      config:
        enabled: true
        type: configMap
        name: *configmap
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      create: true
