# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres-xyz
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  dependsOn:
    - name: iscsi
      namespace: storage
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      pullPolicy: Always
    crds:
      create: true
    replicaCount: 3
    resources:
      requests:
        cpu: 15m
        memory: 150Mi
        ephemeral-storage: 1Gi
      limits:
        memory: 200Mi
        ephemeral-storage: 2Gi
