---
# yaml-language-server: =https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  path: ./cluster/apps/net/ingress-nginx/public
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-private
  namespace: flux-system
spec:
  path: ./cluster/apps/net/ingress-nginx/private
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cilium
