---
# yaml-language-server: https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whoami
  namespace: flux-system
spec:
  path: ./cluster/apps/default/whoami/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: ingress-nginx
