---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: flux-system
spec:
  path: ./cluster/apps/media/radarr/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: nfs
    - name: ingress-nginx
