---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smartctl-exporter
  namespace: flux-system
spec:
  path: ./cluster/apps/o11y/smartctl-exporter/app
  targetNamespace: o11y
  sourceRef:
    kind: GitRepository
    name: homelab
  commonMetadata:
    labels:
      app.kubernetes.io/name: smartctl-exporter
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: victoria-metrics
