apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: perplexica
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: latest
      front:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: hajowieland/perplexica-frontend
              tag: 0.0.4
      back:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: hajowieland/perplexica-backend
              tag: 0.0.2
    service:
      searxng:
        controller: searxng
        ports:
          http:
            port: 4000
      back:
        controller: back
        ports:
          http:
            port: 3001
      front:
        controller: front
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: private
        hosts:
          - host: p.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: front
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  identifier: back
                  port: http
        tls:
          - hosts:
              - p.${SECRET_DOMAIN}
    persistence:
      config:
        type: configMap
        name: searxng-config
        advancedMounts:
          searxng:
            app:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
                readOnly: true
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
                readOnly: true

      tmp:
        type: emptyDir
        advancedMounts:
          app:
            app:
              - path: /etc/searxng
