apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: perplexica
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: latest
            volumeMounts:
              - name: config-volume
                mountPath: /etc/searxng/limiter.toml
                subPath: limiter.toml
        extraVolumes:
          - name: config-volume
            projected:
              sources:
                - configMap:
                    name: searxng-config
                    items:
                      - key: limiter.toml
                        path: limiter.toml
      front:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: hajowieland/perplexica-frontend
              tag: 0.0.4
      back:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: hajowieland/perplexica-backend
              tag: 0.0.2
    service:
      searxng:
        controller: searxng
        ports:
          http:
            port: 4000
      back:
        controller: back
        ports:
          http:
            port: 3001
      front:
        controller: front
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: private
        hosts:
          - host: p.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: front
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  identifier: back
                  port: http
        tls:
          - hosts:
              - p.${SECRET_DOMAIN}
    persistence:
      searxng:
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          searxng:
            app:
              - path: /etc/searxng
    configMaps:
      searxng-config:
        limiter.toml: |
          [settings]
          limit_per_minute = 60

