---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app perplexica
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng:latest
              tag: latest
      front:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image: 
              repository: hajowieland/perplexica-frontend
              tag: latest
      back:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image: 
              repository: hajowieland/perplexica-backend
              tag: latest
    service:
      searxng:
        controller: searxng
        ports:
          http: 4000
      back:
        controller: back
        ports:
          http:
            port: 3001
      front:
        controller: front
        ports:
          http:
            port: 3000

    ingress:
      main:
        className: private
        hosts:
          - host: &host p.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: front
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  identifier: back
                  port: http
        tls: [hosts: [*host]]
    persistence:

