---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
#  - ./config.yaml
configMapGenerator:
  - name: searxng-config
    files:
      - settings.yml=./settings.yaml
      - limiter.toml=./limiter.toml
generatorOptions:
  disableNameSuffixHash: true
