apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-private
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
#      containerSecurityContext:
#        allowPrivilegeEscalation: false
#        readOnlyRootFilesystem: true
#        capabilities: {drop: ["ALL"]}
      replicaCount: 2
      service:
        type: LoadBalancer
        ports:
          dns: 53
        targetPorts:
          dns: 53
        annotations:
          io.cilium/lb-ipam-ips: "10.10.20.109"
      image:
        pullPolicy: Always
      ingressClassByName: true
      extraArgs:
        default-ssl-certificate: "network/default-certificate"
      ingressClassResource:
        default: true
        enabled: true
        name: private
        controllerValue: "k8s.io/ingress-private"
      kind: Deployment
      electionID: "ingress-private-leader"
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values: ["private"]
      config:
        block-user-agents: "GPTBot,~*GPTBot*,ChatGPT-User,~*ChatGPT-User*,Google-Extended,~*Google-Extended*,CCBot,~*CCBot*,Omgilibot,~*Omgilibot*,FacebookBot,~*FacebookBot*" # taken from https://github.com/superseriousbusiness/gotosocial/blob/main/internal/web/robots.go
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        client-header-timeout: 120
        enable-brotli: "true"
        enable-ocsp: "true"
        enable-real-ip: "true"
        hide-headers: Server,X-Powered-By
        hsts-max-age: 31449600
        keep-alive-requests: 10000
        keep-alive: 120
        custom-http-errors: 400,401,403,404,500,502,503,504
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: 0
        proxy-buffer-size: 16k
        proxy-read-timeout: 120
        proxy-send-timeout: 120
        log-format-escape-json: "true"
        log-format-upstream: >
          {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
          "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
          "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length,
          "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent"}
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: network
          namespaceSelector:
            any: true
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 250Mi
          ephemeral-storage: 2Gi
    tcp:
      "53": network/dnsmasq:9553
    udp:
      "53": network/dnsmasq:9553
    defaultBackend:
      enabled: true
#      containerSecurityContext:
#        allowPrivilegeEscalation: false
#        readOnlyRootFilesystem: true
#        capabilities: {drop: ["ALL"]}
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.26.0
        pullPolicy: Always
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 30Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 35Mi
          ephemeral-storage: 2Gi
      extraEnvs:
        - name: TEMPLATE_NAME
          value: matrix
        - name: SHOW_DETAILS
          value: "false"
