apiVersion: apps/v1
kind: Deployment
metadata:
  name: k0s-pushgateway
  namespace: k0s-system
spec:
  template:
    spec:
      containers:
      - name: prometheus-pushgateway
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
