apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k0s-observability
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: k0s-pushgateway
  namespace: k0s-system
spec:
  selector:
    matchLabels:
      app: k0s-observability
      component: pushgateway
  template:
    metadata:
      labels:
        app: k0s-observability
        component: pushgateway
    spec:
      containers:
      - name: prometheus-pushgateway
        image: quay.io/k0sproject/pushgateway-ttl:1.4.0-k0s.0
        resources:
          requests:
            cpu: 20m
