---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k0s-observability
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: k0s-pushgateway
  namespace: k0s-system
spec:
  selector:
    matchLabels:
      app: k0s-observability
      component: pushgateway
  template:
    metadata:
      labels:
        app: k0s-observability
        component: pushgateway
    spec:
      containers:
        - name: prometheus-pushgateway
          resources:
            requests:
              cpu: 15m
              memory: 100Mi
              ephemeral-storage: 100Mi
            limits:
              memory: 100Mi
              ephemeral-storage: 200Mi
