---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tns-csi
  namespace: flux-system
spec:
  path: ./cluster/apps/disk/tns-csi/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cilium
