---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smartctl-exporter
  namespace: flux-system
spec:
  path: ./truenas/smartctl-exporter/app
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: homelab
  kubeConfig:
    secretRef:
      name: truenas-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: smartctl-exporter
  prune: true
  wait: false
  interval: 10m
