apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: storage 
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system 
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
    - name: nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
  #  volumeSnapshotClasses:
  #  - name: nfs
  #    parameters:
  #      detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: ${CONFIG_TRUENAS_IP}
          port: 80
          allowInsecure: true
          apiKey: ${TRUENAS_API_KEY}
        zfs:
          datasetParentName: storage/k8s/nfs/v
          detachedSnapshotsDatasetParentName: storage/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.10.20.100
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    node:
      kubeletHostPath: /var/lib/k0s/kubelet
  

