apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coroot
  namespace: monitor
spec:
  interval: 15m
  chart:
    spec:
      chart: coroot
      version: 0.8.15
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    corootCE:
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 1Gi
          ephemeral-storage: 2Gi
      ingress:
        enabled: true
        className: private
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host coroot.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls: [hosts: [*host]] 
    prometheus:
      enabled: false
      kubeStateMetrics:
        enabled: false
      server:
        enabled: false
    existingPrometheus:
      enabled: true
      service:
        serviceName: vmsingle-vm
        servicePort: 8429
        serviceNamespace: monitor

