apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitor
spec:
  interval: 15m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
        ephemeral-storage: 1Gi
      limits:
        memory: 150Mi
        ephemeral-storage: 2Gi
