---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: goldpinger
  namespace: flux-system
spec:
  interval: 1h
  url: https://bloomberg.github.io/goldpinger
  timeout: 3m