---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ha
  namespace: flux-system
spec:
  interval: 1h
  url: http://pajikos.github.io/home-assistant-helm-chart/
  timeout: 3m
