---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pixie
  namespace: flux-system
spec:
  interval: 1h
  url: https://artifacts.px.dev/helm_charts/operator
  timeout: 3m
