---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 1h
  url: https://emberstack.github.io/helm-charts
  timeout: 3m
