---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 1h
  url: https://stakater.github.io/stakater-charts
  timeout: 3m
