---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: weaveworks
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/weaveworks/charts
  ref:
    tag: 4.0.36
