apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/snapshot-controller/app
  targetNamespace: storage
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 10m
