---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: net
spec:
  chart:
    spec:
      chart: netbox
      version: 7.4.5
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx
      namespace: net
    - name: cloudnative-pg
      namespace: db
    - name: dragonfly
      namespace: db
  interval: 30m
  timeout: 15m
  values:
    image:
      pullPolicy: IfNotPresent

    replicaCount: 1

    superuser:
      name: admin
      email: admin@${SECRET_DOMAIN}
      password: "${NETBOX_ADMIN_PASSWORD}"
      apiToken: "${NETBOX_API_TOKEN}"

    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.1
        env:
          - name: INIT_POSTGRES_HOST
            value: &dbHost "postgres-rw.db.svc.cluster.local"
          - name: INIT_POSTGRES_SUPER_PASS
            value: "${SECRET_PG_PASSWORD}"
          - name: INIT_POSTGRES_USER
            value: &dbUser "netbox"
          - name: INIT_POSTGRES_PASS
            value: &dbPass "${NETBOX_PG_PASSWORD}"
          - name: INIT_POSTGRES_DBNAME
            value: &dbName "netbox"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
            ephemeral-storage: 100Mi
          limits:
            memory: 500Mi
            ephemeral-storage: 200Mi

    # -- External PostgreSQL (CNPG)
    postgresql:
      enabled: false
    externalDatabase:
      host: *dbHost
      port: 5432
      database: *dbName
      username: *dbUser
      password: *dbPass

    # -- Disable bundled Valkey, use Dragonfly
    valkey:
      enabled: false

    tasksDatabase:
      host: &redisHost "dragonfly.db.svc.cluster.local"
      port: &redisPort 6379
      password: &redisPass "${DRAGONFLY_PASSWORD}"
      database: 0

    cachingDatabase:
      host: *redisHost
      port: *redisPort
      password: *redisPass
      database: 1

    # -- Service
    service:
      type: ClusterIP
      port: 80

    # -- Ingress
    ingress:
      enabled: true
      className: "private"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: &host "n.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    # -- Persistence for media files
    persistence:
      enabled: true
      storageClass: ""
      accessMode: ReadWriteOnce
      size: 1Gi

    # -- Probes (Wyse 5070 is slow, needs longer timeouts)
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 60
    livenessProbe:
      enabled: true
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5
    readinessProbe:
      enabled: true
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5

    # -- Resources
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi

    # -- Background worker
    worker:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi

    # -- Housekeeping CronJob
    housekeeping:
      enabled: true
      schedule: "0 3 * * *"
