apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: fairwinds-stable/goldilocks
      version: latest
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    vpa:
      enabled: true
      updater:
        enabled: false
    
