---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      searxng:
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: latest
    service:
      searxng:
        controller: searxng
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: private
        hosts:
          - host: s.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: searxng
                  port: http
        tls:
          - hosts:
              - s.${SECRET_DOMAIN}
    persistence:
      config:
        type: configMap
        name: searxng-config
        advancedMounts:
          searxng:
            app:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
                readOnly: true
              - path: /etc/searxng/limiter.toml
                subPath: limiter.toml
                readOnly: true
