apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: amd-gpu
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: amd
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    labeller:
      enabled: true
