---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: amd-gpu
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    labeller:
      enabled: true
    nfd:
      enabled: true
    node_selector_enabled: true
    securityContext:
      allowPrivilegeEscalation: true
