---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: db
spec:
  chart:
    spec:
      chart: dragonfly
      version: v1.27.1
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    replicaCount: 1

    storage:
      enabled: true
      requests: 2Gi

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 768Mi

    extraArgs:
      - "--requirepass=${DRAGONFLY_PASSWORD}"
      - "--proactor_threads=2"
      - "--maxmemory=512mb"

    service:
      type: ClusterIP
      port: 6379

    serviceMonitor:
      enabled: false
