---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pg-agent
  namespace: o11y
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    #    defaultPodOptions:
    #      annotations:
    #        prometheus.io/scrape: 'true'
    #        prometheus.io/port: '8080'
    controllers:
      pg-agent:
        strategy: RollingUpdate
        containers:
          pg-agent:
            image:
              repository: ghcr.io/coroot/coroot-pg-agent
              tag: latest
              pullPolicy: Always
            env:
              - name: LISTEN
                value: '0.0.0.0:8080'
              - name: PGUSER
                value: "postgres"
              - name: PGPASSWORD
                value: "${SECRET_PG_PASSWORD}"
              - name: DSN
                value: postgresql://$(PGUSER):$(PGPASSWORD)@postgres-ro.db.svc.cluster.local:5432/postgres
            resources:
              requests:
                cpu: 20m
                memory: 50Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 50Mi
                ephemeral-storage: 5Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
    service:
      pg-agent:
        controller: pg-agent
        ports:
          http:
            enabled: true
            port: 8080
    serviceMonitor:
      pg-agent:
        enabled: true
        serviceName: pg-agent
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
