---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: smartctl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      smartctl-exporter:
        type: daemonset
        containers:
          smartctl:
            image:
              repository: quay.io/prometheuscommunity/smartctl-exporter
              tag: v0.14.0
            args:
              - --smartctl.path=/usr/sbin/smartctl
              - --smartctl.interval=120s
              - --web.listen-address=0.0.0.0:9633
              - --web.telemetry-path=/metrics
            securityContext:
              privileged: true
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 200Mi
                ephemeral-storage: 200Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 9633
                    path: /
              readiness: *probes
    service:
      smartctl:
        controller: smartctl-exporter
        ports:
          http:
            port: 9633
    persistence:
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /host/dev
            readOnly: true
    serviceMonitor:
      smartctl:
        enabled: true
        serviceName: smartctl-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
