apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: smartctl-exporter-nas
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  kubeConfig:
    secretRef:
      name: truenas-cluster
  targetNamespace: default
  storageNamespace: default
  values:
    controllers:
      smartctl-exporter:
        type: daemonset
        containers:
          app:
            image:
              repository: quay.io/prometheuscommunity/smartctl-exporter
              tag: v0.12.0
            args:
              - --smartctl.path=/usr/sbin/smartctl
              - --smartctl.interval=30m
              - --web.listen-address=0.0.0.0:9633
              - --web.telemetry-path=/metrics
            securityContext:
              privileged: true
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 9633
                    path: /
              readiness: *probes
    service:
      app:
        type: NodePort
        controller: smartctl-exporter
        ports:
          http:
            port: 9633
            nodePort: 30000
    persistence:
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /host/dev
            readOnly: true
#    serviceMonitor:
#      main:
#        enabled: true
#        serviceName: smartctl-exporter
#        endpoints:
#          - port: http
#            scheme: http
#            path: /metrics
#            interval: 1m
#            scrapeTimeout: 10s
