# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl-exporter-nas
spec:
  staticConfigs: [targets: ["10.10.20.100:30000"]]
  metricsPath: /metrics
  honorTimestamps: true
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
