apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: konnectivity-agent
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: konnectivity-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: konnectivity-agent
  template:
    metadata:
      labels:
        k8s-app: konnectivity-agent
    spec:
      containers:
      - name: konnectivity-agent
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 15m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 100Mi
            ephemeral-storage: 2Gi
