---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: netdata
      version: 3.7.76
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - netdata.${SECRET_DOMAIN}
      tls:
        - secretName: netdata-tls
          hosts:
            - netdata.${SECRET_DOMAIN}
