apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: docker.io/traefik/whoami
              tag: v1.10.4
              pullPolicy: Always
            env:
              WHOAMI_PORT_NUMBER: &port 8080
            resources:
              requests:
                cpu: 15m
                memory: 50Mi
                ephemeral-storage: 100Mi
              limits:
                memory: 50Mi
                ephemeral-storage: 200Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: *port
    ingress:
      public:
        className: public
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        hosts:
          - host: &host whoami.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: 8080
        tls: [hosts: [*host]]
      private:
        className: private
        enabled: true
        hosts:
          - host: &host whoami.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: 8080
        tls: [hosts: [*host]]
