apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: docker.io/traefik/whoami
              tag: v1.10.1
              pullPolicy: Always
            env:
              WHOAMI_PORT_NUMBER: &port 8080
            resources:
              requests:
                cpu: 20m
                memory: 50Mi
                ephemeral-storage: 1Gi
              limits:
                cpu: 50m
                memory: 50Mi
                ephemeral-storage: 5Gi
    service:
      main:
        ports:
          http:
            enabled: true
            port: *port
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
#        className: public
        hosts:
          - host: &host whoami.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host
