---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx
      namespace: network
    - name: nfs
      namespace: storage
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              globalMounts:
                - path: /config
              storageClass: nfs
              accessMode: ReadWriteOnce
              size: 100M
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/transmission
              tag: "4.0.5"
              pullPolicy: Always
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
              startup:
                enabled: false
            env:
              TZ: Europe/Warsaw
              TRANSMISSION__BLOCKLIST_URL: "https://mirror.codebucket.de/transmission/blocklist.p2p.gz"
              TRANSMISSION__DOWNLOAD_DIR: "/media/Downloads"
              TRANSMISSION__INCOMPLETE_DIR_ENABLED: false
              TRANSMISSION__RPC_PORT: &port 9091
              TRANSMISSION__PEER_PORT: &peerport 51413
              TRANSMISSION__RATIO_LIMIT_ENABLED: true
              TRANSMISSION__RATIO_LIMIT: 3
              TRANSMISSION__SPEED_LIMIT_UP_ENABLED: true
              TRANSMISSION__SPEED_LIMIT_UP: 100000
              TRANSMISSION__IDLE_SEEDING_LIMIT_ENABLED: true
              TRANSMISSION__IDLE_SEEDING_LIMIT: 1440
              TRANSMISSION__UTP_ENABLED: false
              TRANSMISSION__UMASK: 7
              TRANSMISSION__MESSAGE_LEVEL: 3
              TRANSMISSION__RPC_PASSWORD: &API_KEY "${TRANSMISSION_RPC_PASSWORD}"
              # For changing webui
              # TRANSMISSION_WEB_HOME: "/app/web"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 200Mi
                ephemeral-storage: 5Gi
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
            targetPort: *port
#      utptcp:
#        type: LoadBalancer
#        controller: main
#        ports:
#          utptcp:
#            enabled: true
#            port: *peerport
#            protocol: TCP
#            targetPort: *peerport
    persistence:
      downloads:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            subPath: Downloads
    ingress:
      main:
        className: private
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Transmission
          gethomepage.dev/icon: transmission.svg
          gethomepage.dev/widget.type: transmission
          gethomepage.dev/widget.url: http://transmission.media
          gethomepage.dev/widget.key: *API_KEY
        hosts:
          - host: &host "torrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: 80
        tls: [hosts: [*host]]
