---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: replicator
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.9.2
      sourceRef:
        kind: HelmRepository
        name: replicator
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: replicator
    resources:
      requests:
        cpu: 20m
        memory: 30Mi
        ephemeral-storage: 1Gi
      limits:
        memory: 50Mi
        ephemeral-storage: 5Gi
