---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: replicator
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: replicator
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: replicator
    resources:
      requests:
        cpu: 20m
        memory: 50Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 100Mi
        ephemeral-storage: 200Mi