---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 105]
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: latest
            resources:
              requests:
                cpu: 700m
                memory: 500Mi
                gpu.intel.com/i915: 1
              limits:
                memory: 800Mi
                gpu.intel.com/i915: 1
            probes:
              startup:
                enabled: true
                spec:
                  initialDelaySeconds: 10
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: jellyfin
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        className: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin.svg
          gethomepage.dev/widget.type: jellyfin
          gethomepage.dev/widget.url: http://jellyfin.media:8096
          gethomepage.dev/key: ${JELLYFIN_API_KEY}
        hosts:
          - host: &host j.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls: [hosts: [*host]]
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          jellyfin:
            main:
              - path: /config
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/transcodes
      cache:
        enabled: true
        type: emptyDir
        advancedMounts:
          jellyfin:
            main:
              - path: /config/cache
