---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.31.0-standalone-strict/all.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: nfs
  nfs:
    mountOptions: [nfsvers=4.2, nconnect=8, hard, noatime, nodiratime]
  persistentVolumeReclaimPolicy: Retain
