---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
  annotations:
    nasty-csi.io/adoptable: "true"
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: nasty-nfs
