---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              storageClass: nfs
              accessMode: ReadWriteOnce
              size: 5Gi
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
              pullPolicy: IfNotPresent
            env:
              INIT_POSTGRES_HOST: &dbHost "postgres-rw.database.svc.cluster.local"
              INIT_POSTGRES_SUPER_PASS: "${SECRET_PG_PASSWORD}"
              INIT_POSTGRES_USER: &dbUser "sonarr"
              INIT_POSTGRES_PASS: &dbPass "${SONARR_PG_PASSWORD}"
              INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
#            resources:
#              requests:
#                cpu: 50m
#                memory: 100Mi
#              limits:
#                cpu: 200m
#                memory: 300Mi
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.0.737
            env:
              TZ: Europe/Warsaw
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__AUTHENTICATION_METHOD: External
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__LOG_LEVEL: info
              SONARR__THEME: dark
              SONARR__API_KEY: "${SONARR_API_KEY}"
              SONARR__POSTGRES_HOST: *dbHost
              SONARR__POSTGRES_PORT: "5432"
              SONARR__POSTGRES_USER: *dbUser
              SONARR__POSTGRES_PASSWORD: *dbPass
              SONARR__POSTGRES_MAIN_DB: sonarr_main
              SONARR__POSTGRES_LOG_DB: sonarr_log
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
#           resources:
#              requests:
#                cpu: 100m
#                memory: 200Mi
#              limits:
#                cpu: 300m
#                memory: 800Mi
    service:
      main:
        ports:
          http:
            port: *port
    persistence:
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media
            retain: true
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/appName: Sonarr
          hajimari.io/icon: mdi:television-box
          hajimari.io/group: media
        enabled: true
        hosts:
          - host: &host "tv.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host
