apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  path: ./cluster/apps/monitoring/kube-prometheus-stack/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
