---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-metallb
  namespace: flux-system
  labels:
    substitution.flux.home/enabled: "true"
spec:
  path: ./cluster/apps/metallb/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metallb
      namespace: metallb
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-metallb-config
  namespace: flux-system
  labels:
    substitution.flux.home/enabled: "true"
spec:
  dependsOn:
    - name: apps-metallb
  path: ./cluster/apps/metallb/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
