---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: transmission
  namespace: flux-system
spec:
  path: ./cluster/apps/media/transmission/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: nfs
    - name: ingress-nginx
