apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs
  namespace: disk
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 1Gi
          limits:
            cpu: 500m
            memory: 100Mi
            ephemeral-storage: 5Gi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 100M
            ephemeral-storage: 5Gi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 100Mi
            ephemeral-storage: 5Gi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 100Mi
            ephemeral-storage: 5Gi
      driver:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 800m
            memory: 100Mi
            ephemeral-storage: 2Gi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          cpu: 200m
          memory: 100Mi
          ephemeral-storage: 5Gi
    csiDriver:
      name: "nfs"
    storageClasses:
    - name: nfs
      defaultClass: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
  #  volumeSnapshotClasses:
  #  - name: nfs
  #    parameters:
  #      detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: ${CONFIG_TRUENAS_IP}
          port: 80
          allowInsecure: true
          apiKey: ${TRUENAS_API_KEY}
        zfs:
          datasetParentName: storage/nfs/v
          detachedSnapshotsDatasetParentName: storage/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.10.20.100
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    node:
      driver:
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 800m
            memory: 200Mi
            ephemeral-storage: 5Gi
      driverRegistrar:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 200Mi
            ephemeral-storage: 5Gi
      cleanup:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 200Mi
            ephemeral-storage: 5Gi
      kubeletHostPath: /var/lib/k0s/kubelet
