---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-credentials
  storage:
    size: 20Gi
    storageClass: iscsi
  postgresql:
    parameters:
      max_connections: "300"
      work_mem: 64MB
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - { sourceLabels: ["exported_cluster"], targetLabel: cluster }
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      memory: 1Gi
