---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: iscsi
  postgresql:
    parameters:
      max_connections: "300"
      work_mem: 64MB
      shared_buffers: 128MB
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      memory: 1Gi
