---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-credentials
  storage:
    size: 20Gi
    storageClass: iscsi
  postgresql:
    parameters:
      max_connections: "300"
      work_mem: 64MB
      shared_buffers: 128MB
  resources:
    requests:
      cpu: 100m
      memory: 800Mi
      ephemeral-storage: 1Gi
    limits:
      memory: 1.2Gi
      ephemeral-storage: 5Gi
