---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyoo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.7.1
  url: oci://ghcr.io/zoriya/helm-charts/kyoo
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kyoo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: kyoo
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  values:
    kyoo:
      address: "https://kyoo.${SECRET_DOMAIN}"
    meilisearch:
      enabled: true
    postgresql:
      enabled: true
      shared:
        secretKeys:
          adminPasswordKey: "POSTGRES_PASSWORD"
          userPasswordKey: "POSTGRES_PASSWORD"
    rabbitmq:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: private
      host: "kyoo.${SECRET_DOMAIN}"
      tls: true
