---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyoo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.7.1
  url: oci://ghcr.io/zoriya/helm-charts/kyoo
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyoo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: kyoo
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  values:
    # Enable required subcharts (meilisearch & rabbitmq are needed)
    meilisearch:
      enabled: true
      environment:
        MEILI_ENV: production
      auth:
        existingMasterKeySecret: kyoo
      persistence:
        enabled: true
        size: 3Gi

    postgresql:
      enabled: false

    rabbitmq:
      enabled: true
      auth:
        username: kyoo
        existingPasswordSecret: kyoo
        existingSecretPasswordKey: RABBITMQ_PASSWORD
        existingErlangSecret: kyoo
        existingSecretErlangKey: RABBITMQ_COOKIE

    # Global configuration
    global:
      # MeiliSearch configuration
      meilisearch:
        proto: http
        host: kyoo-meilisearch
        port: 7700
        infra:
          existingSecret: kyoo
        kyoo_back:
          masterkeyKey: MEILI_MASTER_KEY
          existingSecret: kyoo

      # PostgreSQL configuration - external CNPG cluster
      postgres:
        infra:
          user: kyoo
          passwordKey: PG_PASSWORD
          existingSecret: kyoo
        kyoo_back:
          host: postgres-rw.db.svc.cluster.local
          port: 5432
          database: kyoo_back
          kyoo_migrations:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo
          kyoo_back:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo
        kyoo_transcoder:
          host: postgres-rw.db.svc.cluster.local
          port: 5432
          database: kyoo_transcoder
          schema: disabled
          sslmode: disable
          kyoo_transcoder:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo

      # RabbitMQ configuration
      rabbitmq:
        host: kyoo-rabbitmq
        port: 5672
        infra:
          passwordKey: RABBITMQ_PASSWORD
          keyErlangCookie: RABBITMQ_COOKIE
          existingSecret: kyoo
        kyoo_autosync:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_back:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_matcher:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_scanner:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo

    # Kyoo application settings
    kyoo:
      address: "https://kyoo.${SECRET_DOMAIN}"
      requireAccountVerification: true
      defaultPermissions: "overall.read,overall.play"
      unloggedPermissions: ""
      languages: "en"
      transcoderAcceleration: vaapi
      transcoderPreset: fast
      apikey:
        existingSecret: kyoo
        apikeyKey: KYOO_APIKEYS

    # Content database (TMDB/TVDB)
    contentdatabase:
      tmdb:
        existingSecret: kyoo
        apikeyKey: TMDB_API_KEY
      tvdb:
        existingSecret: kyoo
        apikeyKey: TVDB_API_KEY
        pinKey: TVDB_PIN

    # Media volumes configuration
    media:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      volumeMounts:
        - mountPath: /media
          name: media
          readOnly: true
      baseMountPath: /media

    # Back deployment with init container for database setup
    back:
      extraInitContainers:
        - name: init-db
          image: postgres:17
          env:
            - name: PGHOST
              value: postgres-rw.db.svc.cluster.local
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: KYOO_PG_PASS
              valueFrom:
                secretKeyRef:
                  name: kyoo
                  key: PG_PASSWORD
          command:
            - sh
            - -c
            - |
              set -e
              echo "Creating kyoo user if not exists..."
              psql -tc "SELECT 1 FROM pg_roles WHERE rolname='kyoo'" | grep -q 1 || \
                psql -c "CREATE USER kyoo WITH PASSWORD '${KYOO_PG_PASS}'"

              echo "Creating databases if not exist..."
              for db in kyoo_back kyoo_transcoder; do
                psql -tc "SELECT 1 FROM pg_database WHERE datname='$db'" | grep -q 1 || \
                  psql -c "CREATE DATABASE $db OWNER kyoo"
              done

              echo "Setting up kyoo_back schema..."
              psql -d kyoo_back -c "CREATE SCHEMA IF NOT EXISTS data AUTHORIZATION kyoo"
              psql -d kyoo_back -c "ALTER ROLE kyoo IN DATABASE kyoo_back SET search_path TO \"\$user\", public"

              echo "Setting up kyoo_transcoder schema..."
              psql -d kyoo_transcoder -c "CREATE SCHEMA IF NOT EXISTS data AUTHORIZATION kyoo"
              psql -d kyoo_transcoder -c "ALTER ROLE kyoo IN DATABASE kyoo_transcoder SET search_path TO \"\$user\", data"

              echo "Database initialization complete!"

    # Transcoder with AMD GPU access
    transcoder:
      kyoo_transcoder:
        extraEnv:
          - name: GOCODER_VAAPI_RENDERER
            value: /dev/dri/renderD128
        resources:
          limits:
            amd.com/gpu: 1

    # Ingress configuration
    ingress:
      enabled: true
      ingressClassName: private
      host: "kyoo.${SECRET_DOMAIN}"
      tls: true
