---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kyoo
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.11
            env:
              MEILI_ENV: production
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: kyoo-secret
                    key: MEILI_MASTER_KEY
            probes:
              liveness: &searchprobes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &searchport 7700
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *searchprobes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 400Mi
            securityContext: &securityContext
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
#              capabilities: { drop: ["ALL"] }
        pod: &pod
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 105]

      rabbitmq:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/rabbitmq
              tag: 4-alpine
            envFrom: &envFrom
              - secretRef:
                  name: kyoo-secret
              - configMapRef:
                  name: kyoo-config
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 300Mi
            securityContext: *securityContext
        pod: *pod

      back:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        initContainers:
          00-init-db:
            image: 
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.4
            env:
              - name: INIT_POSTGRES_HOST
                value: &dbHost "postgres-rw.db.svc.cluster.local"
              - name: INIT_POSTGRES_SUPER_PASS
                value: "${SECRET_PG_PASSWORD}"
              - name: INIT_POSTGRES_USER
                value: &dbUser "kyoo"
              - name: INIT_POSTGRES_PASS
                value: &dbPass "${KYOO_PG_PASSWORD}"
              - name: INIT_POSTGRES_DBNAME
                value: &dbName kyoo
          01-migrations:
            env:
              - name: POSTGRES_SERVER
                value: *dbHost
              - name: POSTGRES_PORT
                value: '5432'
              - name: POSTGRES_DB
                value: *dbName
              - name: POSTGRES_USER
                value: *dbUser
              - name: POSTGRES_PASSWORD
                value: *dbPass
            envFrom:
              - secretRef:
                  name: kyoo-secret
            image:
              repository: ghcr.io/zoriya/kyoo_migrations
              tag: edge@sha256:8a789c4c89cfb0f7e556109eed836a7a73cfa6334381b5f7539a1426326b60ca
        containers:
          app:
            image:
              repository: ghcr.io/zoriya/kyoo_back
              tag: edge@sha256:047014e64c223ebd440befd525dba2d880baee5e889c338d7f0956a5654a0af3
            env:
              - name: POSTGRES_SERVER
                value: *dbHost
              - name: POSTGRES_PORT
                value: '5432'
              - name: POSTGRES_DB
                value: *dbName
              - name: POSTGRES_USER
                value: *dbUser
              - name: POSTGRES_PASSWORD
                value: *dbPass
              - name: TRANSCODER_URL 
                value: http://kyoo-transcoder:7666
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                cpu: 4000m
                memory: 8Gi
            securityContext: *securityContext
        pod: *pod

      front:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/zoriya/kyoo_front
              tag: edge@sha256:57b82f30899adf49bdaef07755391d3b63a33c5fce67644de8f58b9120de9264
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
                memory: 100Mi
              limits:
                memory: 1Gi
            securityContext: *securityContext
        pod: *pod

      scanner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: &scannerimage ghcr.io/zoriya/kyoo_scanner
              tag: &scannertag edge@sha256:92279694b8a00f90295f3acd5124a130c83d8560e60803ac6fc96572ec153b05
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 1Gi
#            securityContext: *securityContext
#        pod: *pod

      matcher:
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: *scannerimage
              tag: *scannertag
            args: ["matcher"]
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 400Mi
            securityContext: *securityContext
        pod: *pod

      autosync:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zoriya/kyoo_autosync
              tag: 4.7.0@sha256:eca5415548a41181a59251b42c5ad8daa2b7a4f847d8c0f780b25a8da75a102f
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 100Mi
            securityContext: *securityContext
        pod: *pod

      transcoder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zoriya/kyoo_transcoder
              tag: edge@sha256:a28c662a7de800581e8f491f4fddd60f156208fabfa93e5b35608884113b8a07
            envFrom: *envFrom
            env:
              - name: POSTGRES_SERVER
                value: *dbHost
              - name: POSTGRES_PORT
                value: '5432'
              - name: POSTGRES_DB
                value: *dbName
              - name: POSTGRES_USER
                value: *dbUser
              - name: POSTGRES_PASSWORD
                value: *dbPass
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 8Gi
            securityContext: *securityContext
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 105]

    service:
      back:
        controller: back
        ports:
          http:
            port: 5000
      front:
        controller: front
        ports:
          http:
            port: 8901
      rabbitmq:
        controller: rabbitmq
        ports:
          http:
            port: 5672
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: *searchport
      transcoder:
        controller: transcoder
        ports:
          http:
            port: 7666

    ingress:
      main:
        className: private
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host kyoo.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: front
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  identifier: back
                  port: http
        tls: [hosts: [*host]]
    persistence:
      kyoo:
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        nameOverride: kyoo
        advancedMounts:
          back:
            app:
              - path: /metadata
      search:
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          meilisearch:
            app:
              - path: /meili_data
      transcoder-metadata:
        size: 5Gi
        accessMode: ReadWriteOnce
        retain: true
        advancedMounts:
          transcoder:
            app:
              - path: /metadata
      cache:
        type: emptyDir
        advancedMounts:
          transcoder:
            app:
              - path: /cache
      media:
        enabled: true
        existingClaim: media
        globalMounts:
          - path: /media

