---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyoo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.0.0-prototype
  url: oci://ghcr.io/zoriya/helm-charts/kyoo
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyoo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: kyoo
  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: -1
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  values:
    # Disable built-in postgresql - use external CNPG
    postgres:
      enabled: false

    global:
      postgres:
        infra:
          user: kyoo
          passwordKey: PG_PASSWORD
          existingSecret: kyoo
        shared:
          host: postgres-rw.db.svc.cluster.local
          port: 5432
          existingSecret: kyoo
          userKey: PG_USER
          passwordKey: PG_PASSWORD
        kyoo_api:
          database: kyoo_api
          sslmode: disable
        kyoo_auth:
          database: kyoo_auth
          sslmode: disable
        kyoo_scanner:
          database: kyoo_scanner
          sslmode: disable
        kyoo_transcoder:
          database: kyoo_transcoder
          sslmode: disable

    kyoo:
      address: "https://kyoo.${SECRET_DOMAIN}"
      transcoderAcceleration: vaapi
      transcoderPreset: fast
      auth:
        apikeys:
          scanner:
            existingSecret: kyoo
            apikeyKey: SCANNER_APIKEY
            claims: '{"permissions": ["core.read", "core.write"]}'

    contentdatabase:
      tmdb:
        existingSecret: kyoo
        apikeyKey: TMDB_API_KEY
      tvdb:
        existingSecret: kyoo
        apikeyKey: TVDB_API_KEY
        pinKey: TVDB_PIN

    media:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      volumeMounts:
        - mountPath: /media
          name: media
          readOnly: true
      baseMountPath: /media

    # Disable chart's ingress - we'll create our own pointing to traefik proxy
    ingress:
      enabled: false

    # Enable built-in traefik proxy - handles all auth middleware internally
    traefikproxy:
      enabled: true

    # API - init containers: 1) create database, 2) create pg_trgm extension
    api:
      kyoo_api:
        image:
          tag: edge
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:17.4
          env:
            - name: INIT_POSTGRES_HOST
              value: postgres-rw.db.svc.cluster.local
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: INIT_POSTGRES_USER
              value: kyoo
            - name: INIT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: kyoo
                  key: PG_PASSWORD
            - name: INIT_POSTGRES_DBNAME
              value: kyoo_api
        # Create pg_trgm extension as superuser (required for full-text search)
        - name: init-extensions
          image: ghcr.io/onedr0p/postgres-init:17.4
          env:
            - name: PGHOST
              value: postgres-rw.db.svc.cluster.local
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: PGDATABASE
              value: kyoo_api
          command:
            - /bin/bash
            - -c
            - |
              until pg_isready; do echo "Waiting for postgres..."; sleep 1; done
              echo "Creating schema and extension..."
              psql -c "CREATE SCHEMA IF NOT EXISTS kyoo;"
              psql -c "CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA kyoo;"
              echo "Done."

    # Auth - init container creates database
    auth:
      kyoo_auth:
        image:
          tag: edge
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:17.4
          env:
            - name: INIT_POSTGRES_HOST
              value: postgres-rw.db.svc.cluster.local
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: INIT_POSTGRES_USER
              value: kyoo
            - name: INIT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: kyoo
                  key: PG_PASSWORD
            - name: INIT_POSTGRES_DBNAME
              value: kyoo_auth

    # Scanner - init container creates database
    scanner:
      kyoo_scanner:
        image:
          tag: edge
        extraEnv:
          - name: LIBRARY_IGNORE_PATTERN
            value: ".*\\.!qB$"
        livenessProbe:
          httpGet:
            path: /health
            port: main
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: main
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:17.4
          env:
            - name: INIT_POSTGRES_HOST
              value: postgres-rw.db.svc.cluster.local
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: INIT_POSTGRES_USER
              value: kyoo
            - name: INIT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: kyoo
                  key: PG_PASSWORD
            - name: INIT_POSTGRES_DBNAME
              value: kyoo_scanner

    # Transcoder - init container creates database, plus GPU config
    transcoder:
      kyoo_transcoder:
        image:
          tag: edge
        resources:
          limits:
            amd.com/gpu: 1
        extraVolumeMounts:
          - name: dri
            mountPath: /dev/dri
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:17.4
          env:
            - name: INIT_POSTGRES_HOST
              value: postgres-rw.db.svc.cluster.local
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: INIT_POSTGRES_USER
              value: kyoo
            - name: INIT_POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: kyoo
                  key: PG_PASSWORD
            - name: INIT_POSTGRES_DBNAME
              value: kyoo_transcoder
      extraVolumes:
        - name: dri
          hostPath:
            path: /dev/dri

    # Frontend - no database needed
    front:
      kyoo_front:
        image:
          tag: edge
