---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyoo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.7.1
  url: oci://ghcr.io/zoriya/helm-charts/kyoo
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyoo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: kyoo
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  values:
    meilisearch:
      enabled: true
      environment:
        MEILI_ENV: production
      auth:
        existingMasterKeySecret: kyoo
      persistence:
        enabled: true
        size: 3Gi

    # Disable built-in postgresql - use external CNPG
    postgresql:
      enabled: false

    rabbitmq:
      enabled: true
      auth:
        username: kyoo
        existingPasswordSecret: kyoo
        existingSecretPasswordKey: RABBITMQ_PASSWORD
        existingErlangSecret: kyoo
        existingSecretErlangKey: RABBITMQ_COOKIE

    global:
      meilisearch:
        infra:
          existingSecret: kyoo
        kyoo_back:
          masterkeyKey: MEILI_MASTER_KEY
          existingSecret: kyoo
      postgres:
        infra:
          user: kyoo
          passwordKey: PG_PASSWORD
          existingSecret: kyoo
        kyoo_back:
          host: postgres-rw.db.svc.cluster.local
          port: 5432
          database: kyoo_back
          kyoo_migrations:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo
          kyoo_back:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo
        kyoo_transcoder:
          host: postgres-rw.db.svc.cluster.local
          port: 5432
          database: kyoo_transcoder
          schema: disabled
          sslmode: disable
          kyoo_transcoder:
            userKey: PG_USER
            passwordKey: PG_PASSWORD
            existingSecret: kyoo
      rabbitmq:
        infra:
          passwordKey: RABBITMQ_PASSWORD
          keyErlangCookie: RABBITMQ_COOKIE
          existingSecret: kyoo
        kyoo_autosync:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_back:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_matcher:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo
        kyoo_scanner:
          userKey: RABBITMQ_USER
          passwordKey: RABBITMQ_PASSWORD
          existingSecret: kyoo

    kyoo:
      address: "https://kyoo.${SECRET_DOMAIN}"
      transcoderAcceleration: vaapi
      transcoderPreset: fast
      apikey:
        existingSecret: kyoo
        apikeyKey: KYOO_APIKEYS

    contentdatabase:
      tmdb:
        existingSecret: kyoo
        apikeyKey: TMDB_API_KEY
      tvdb:
        existingSecret: kyoo
        apikeyKey: TVDB_API_KEY
        pinKey: TVDB_PIN

    media:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
      volumeMounts:
        - mountPath: /media
          name: media
          readOnly: true
      baseMountPath: /media

    ingress:
      enabled: true
      ingressClassName: private
      host: "kyoo.${SECRET_DOMAIN}"
      tls: true

    # Transcoder configuration for AMD GPU (VAAPI)
    transcoder:
      kyoo_transcoder:
        resources:
          limits:
            amd.com/gpu: 1
        extraVolumeMounts:
          - name: dri
            mountPath: /dev/dri
      extraVolumes:
        - name: dri
          hostPath:
            path: /dev/dri
