---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vl
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.11.18
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: vl
    server:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 500Mi
          ephemeral-storage: 200Mi
      ingress:
        enabled: true
        ingressClassName: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: VictoriaLogs
          gethomepage.dev/icon: si-victoriametrics
          gethomepage.dev/pod-selector: ""
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - name: &host "l.${SECRET_DOMAIN}"
            path: /
            port: http
        tls: [hosts: [*host]]
      persistentVolume:
        size: 100Gi
    vector:
      enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 2Gi
          ephemeral-storage: 300Mi
      customConfig:
        data_dir: /vector-data-dir
        api:
          enabled: false
          address: 0.0.0.0:8686
          playground: true
        sources:
          k8s:
            type: kubernetes_logs
            # Exclude high-volume log sources to reduce memory usage
            exclude_paths_glob_patterns:
              - "**/kube-apiserver-*/**"
              - "**/kube-controller-manager-*/**"
              - "**/kube-scheduler-*/**"
              - "**/cilium-*/**"
              - "**/hubble-*/**"
          internal_metrics:
            type: internal_metrics
        transforms:
          parser:
            type: remap
            inputs: [k8s]
            source: |
              .log = parse_json(.message) ?? .message
              del(.message)
        sinks:
          exporter:
            type: prometheus_exporter
            address: 0.0.0.0:9090
            inputs: [internal_metrics]
          vlogs:
            type: elasticsearch
            inputs: [parser]
            mode: bulk
            api_version: v8
            compression: gzip
            healthcheck:
              enabled: false
            # Add buffer limits to prevent unbounded memory growth
            buffer:
              type: memory
              max_events: 5000
            batch:
              max_bytes: 1048576
              timeout_secs: 1
            request:
              headers:
                VL-Time-Field: timestamp
                VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
                VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
                AccountID: "0"
                ProjectID: "0"
