---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vl
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.11.18
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: vl
    server:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 500Mi
          ephemeral-storage: 200Mi
      ingress:
        enabled: true
        ingressClassName: private
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: VictoriaLogs
          gethomepage.dev/icon: si-victoriametrics
          gethomepage.dev/pod-selector: ""
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - name: &host "l.${SECRET_DOMAIN}"
            path: /
            port: http
        tls: [hosts: [*host]]
      persistentVolume:
        size: 100Gi
    vector:
      enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 2Gi
          ephemeral-storage: 300Mi
