---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: reflector
      version: 7.1.216
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: reflector
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
