apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pg-agent
  namespace: o11y
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '80'
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/coroot/coroot-pg-agent
              tag: latest
              pullPolicy: Always
            env:
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: postgres.product-pg.credentials
                    key: username
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres.product-pg.credentials
                    key: password
              - name: DSN
                value: postgresql://$(PGUSER):$(PGPASSWORD)@/postgres-ro.database.svc.cluster.local:5432/postgres
            resources:
              requests:
                cpu: 20m
                memory: 50Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 50Mi
                ephemeral-storage: 5Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: 80

