apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "default-certificate"
spec:
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: "default-certificate"
