apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "default-certificate"
  namespace: network
spec:
  dnsNames:
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: "default-certificate"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "media,database"
