---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: searxng
  namespace: flux-system
spec:
  path: ./cluster/apps/selfhosted/searxng/app
  targetNamespace: selfhosted
  sourceRef:
    kind: GitRepository
    name: homelab
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname searxng
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: ingress-nginx
