---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  path: ./cluster/apps/disk/snapshot-controller/app
  targetNamespace: disk
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 10m
