apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ha
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.33
      sourceRef:
        kind: HelmRepository
        name: ha
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    persistence.enabled=true
    
