---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        volumeClaimTemplates:
          - name: config
            mountPath: /config
            storageClassName: nfs
            accessMode: ReadWriteOnce
            size: 5Gi
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
              pullPolicy: IfNotPresent
            env:
              INIT_POSTGRES_HOST: &dbHost "postgres-rw.database.svc.cluster.local"
              INIT_POSTGRES_SUPER_PASS: "${SECRET_PG_PASSWORD}"
              INIT_POSTGRES_USER: &dbUser "prowlarr"
              INIT_POSTGRES_PASS: &dbPass "${PROWLARR_PG_PASSWORD}"
              INIT_POSTGRES_DBNAME: prowlarr_main prowlarr_log
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: 1.9.4.4039
            env:
              TZ: Europe/Warsaw
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__THEME: dark
              PROWLARR__API_KEY: "${PROWLARR_API_KEY}"
              PROWLARR__POSTGRES_HOST: *dbHost
              PROWLARR__POSTGRES_PORT: "5432"
              PROWLARR__POSTGRES_USER: *dbUser
              PROWLARR__POSTGRES_PASSWORD: *dbPass
              PROWLARR__POSTGRES_MAIN_DB: prowlarr_main
              PROWLARR__POSTGRES_LOG_DB: prowlarr_log
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 300Mi
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        hosts:
          - host: &host "indexer.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: *host
            hosts:
              - *host
