---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: db
spec:
  # bootstrap:
  #  recovery:
  #  source: &previous-cluster postgres
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-credentials
  storage:
    size: 50Gi
    storageClass: iscsi
  postgresql:
    shared_preload_libraries: [pg_stat_statements]
    parameters:
      max_connections: "300"
      work_mem: 128MB
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 100m
      memory: 800Mi
      ephemeral-storage: 100Mi
    limits:
      memory: 1.2Gi
      ephemeral-storage: 200Mi
#  backup:
#    retentionPolicy: 7d
#    barmanObjectStore:
#      data:
#        compression: bzip2
#      wal:
#        compression: bzip2
#        maxParallel: 4
#      destinationPath: s3://pgsql/
#      endpointURL: https://eu-central-1.linodeobjects.com
#      serverName: postgres-v2
#      s3Credentials:
#        accessKeyId:
#          name: pg-credentials
#          key: S3_ACCESS_KEY
#        secretAccessKey:
#          name: pg-credentials
#          key: S3_SECRET_KEY
#  externalClusters:
#    - name: *previous-cluster
#      barmanObjectStore:
#        destinationPath: s3://pgsql/
#        endpointURL: https://eu-central-1.linodeobjects.com
#        s3Credentials:
#          accessKeyId:
#            name: pg-credentials
#            key: S3_ACCESS_KEY
#          secretAccessKey:
#            name: pg-credentials
#            key: S3_SECRET_KEY
