---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: postgres
  name: postgres
  namespace: db
spec:
  podMetricsEndpoints:
    - honorLabels: true
      port: metrics
      selector:
        matchLabels:
          cnpg.io/cluster: postgres
