---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/all.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: postgres
  name: postgres
  namespace: db
spec:
  podMetricsEndpoints:
    - honorLabels: true
      port: metrics
      selector:
        matchLabels:
          cnpg.io/cluster: postgres
