apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: postgres
  name: postgres
  namespace: db
spec:
  podMetricsEndpoints:
  - honorLabels: true
    port: metrics
#    relabelings:
#      - sourceLabels: [__meta_kubernetes_pod_label_cluster]
#        regex: 'cluster-name'
#        action: drop
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
