---
# yaml-language-server: $schema=https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: postgres
  name: postgres
  namespace: db
spec:
  podMetricsEndpoints:
    - honorLabels: true
      port: metrics
      selector:
        matchLabels:
          cnpg.io/cluster: postgres
