apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpa
  namespace: flux-system
spec:
  path: ./cluster/apps/o11y/vpa/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: victoria-metrics
