---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "default-certificate"
  namespace: net
spec:
  dnsNames:
    - "*.${SECRET_DOMAIN}"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: "default-certificate"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "default,flux-system,media,db,o11y,net,disk"
