---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.31.0-standalone-strict/all.json
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 64513
      serviceSelector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ['never-used-value']}
      exportPodCIDR: true
      neighbors:
        - peerAddress: '10.10.20.97/32'
          peerASN: 64512
