---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.31.0-standalone-strict/all.json
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
