apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vpa
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 4.4.6
      sourceRef:
        kind: HelmRepository
        name: goldilocks
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    updater:
      enabled: false
    recommender:
      extraArgs:
        storage: prometheus
        prometheus-address: http://vmsingle-vm.svc.cluster.local:8429
    admissionController:
      enabled: false

