---
# yaml-language-server: =https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: perplexica
  namespace: flux-system
spec:
  path: ./cluster/apps/selfhosted/perplexica/app
  targetNamespace: selfhosted
  sourceRef:
    kind: GitRepository
    name: homelab
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname perplexica
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: ingress-nginx
