---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: net
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 100Mi
        ephemeral-storage: 200Mi
    provider: cloudflare
    serviceMonitor:
      enabled: true
    extraArgs:
      - --default-targets=${EXTERNAL_IP}
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: dns-credentials
            key: CF_API_TOKEN
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: dns-credentials
            key: CF_API_EMAIL
#     - name: LINODE_TOKEN
#        valueFrom:
#          secretKeyRef:
#            name: dns-credentials
#            key: LINODE_TOKEN
