---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    provider: linode
    serviceMonitor:
      enabled: true
    extraArgs:
      - --default-targets=${EXTERNAL_IP}
    env:
#      - name: CF_API_TOKEN
#        valueFrom:
#          secretKeyRef:
#            name: cluster-secrets
#            key: CF_API_TOKEN
#      - name: CF_API_EMAIL
#        valueFrom:
#          secretKeyRef:
#            name: cluster-secrets
#            key: CF_API_EMAIL
      - name: LINODE_TOKEN
        valueFrom:
          secretKeyRef:
            name: dns-credentials
            key: LINODE_TOKEN
