---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux-webui
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx
      namespace: net
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    additionalArgs:
      - --insecure-no-authentication-user=admin
    image:
      pullPolicy: Always
    fullnameOverride: flux-webui
    adminUser:
      create: true
      username: admin
      passwordHash: ${WW_ADMIN_PASSWORD}
    ingress:
      className: private
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/name: Flux
        gethomepage.dev/icon: git.svg
        gethomepage.dev/pod-selector: ""
      hosts:
        - host: &host "flux.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls: [hosts: [*host]]
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
    resources:
      requests:
        cpu: 100m
        memory: 80Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 200Mi
        ephemeral-storage: 200Mi
