---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.4
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  interval: 30m
  values:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: null
        memory: 200Mi
    worker:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: null
          memory: 200Mi
    gc:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
        limits:
          cpu: null
          memory: 200Mi
