apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coroot
  namespace: o11y
spec:
  interval: 15m
  chart:
    spec:
      chart: coroot
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    corootCE:
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 1.2Gi
          ephemeral-storage: 2Gi
      ingress:
        enabled: true
        className: private
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host coroot.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls: [hosts: [*host]] 
    corootClusterAgent:
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 500Mi
          ephemeral-storage: 2Gi
    prometheus:
      enabled: false
      kubeStateMetrics:
        enabled: false
      server:
        enabled: false
    existingPrometheus:
      enabled: true
      service:
        serviceName: vmsingle-vm
        servicePort: 8429
        serviceNamespace: o11y
      node-agent-podmonitor:
        enabled: true
    clickhouse:
      resources:
        requests:
          cpu: 500m
          memory: 1.5Gi
          ephemeral-storage: 1Gi
        limits:
          memory: 2.5Gi
          ephemeral-storage: 2Gi
      securityContext:
        capabilities: 
          add: ["CAP_IPC_LOCK"
    node-agent:
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: 1Gi
        limits:
          cpu: 1200m
          memory: 1.2Gi
          ephemeral-storage: 2Gi
    opentelemetry-collector:
      resources:
        requests:
          cpu: 50m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 500Mi


