apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: coroot
  namespace: o11y
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: coroot
      version: 0.15.14
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    corootCE:
      enabled: true
      bootstrap:
        refreshInterval: 15s
        clickhouse:
          database: default
          username: default
      resources:
        requests:
          cpu: 150m
          memory: 1Gi
          ephemeral-storage: 100Mi
        limits:
          memory: 1.2Gi
          ephemeral-storage: 200Mi
      ingress:
        enabled: true
        className: private
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host coroot.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls: [hosts: [*host]] 
    corootClusterAgent:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 300Mi
          ephemeral-storage: 200Mi
    prometheus:
      enabled: false
      kubeStateMetrics:
        enabled: false
      server:
        enabled: false
      nodeExporter:
        enabled: false
      pushgateway:
        enabled: false
    existingPrometheus:
      enabled: true
      service:
        serviceName: vmsingle-vm
        servicePort: 8429
        serviceNamespace: o11y
      node-agent-podmonitor:
        enabled: true
    clickhouse:
      resources:
        requests:
          cpu: 400m
          memory: 800Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 1Gi
          ephemeral-storage: 200Mi
      securityContext:
        capabilities: 
          add: ["CAP_IPC_LOCK","CAP_SYS_NICE","CAP_NET_ADMIN"]
    node-agent:
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 1.2Gi
          ephemeral-storage: 200Mi

