---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot
  namespace: o11y
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: coroot-ce
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      className: private
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      host: &host coroot.${SECRET_DOMAIN}
      tls:
        hosts:
          - *host
        secretName: coroot-tls
    clusterAgent:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 300Mi
          ephemeral-storage: 200Mi
    externalPrometheus:
      url: http://vmsingle-vm.o11y.svc.cluster.local:8428
    storage:
      className: tns-csi-nvmeof
    clickhouse:
      storage:
        className: tns-csi-nvmeof
      resources:
        requests:
          cpu: 400m
          memory: 1Gi
          ephemeral-storage: 100Mi
        limits:
          memory: 3Gi
          ephemeral-storage: 200Mi
    node-agent:
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
          ephemeral-storage: 100Mi
        limits:
          memory: 1.2Gi
          ephemeral-storage: 200Mi
