---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coroot
  namespace: flux-system
spec:
  path: ./cluster/apps/o11y/coroot/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: coroot-operator
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coroot-operator
  namespace: flux-system
spec:
  path: ./cluster/apps/o11y/coroot/operator
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: true
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: iscsi
    - name: victoria-metrics
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.31.0-standalone-strict/all.json
