apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:oWcUk7U=,iv:wbCRrQ1aGEEbcPJR+FKPhxIoJ7gVS1eTi2He2LN+0bE=,tag:c+/JZRNt3DimXOgfQP+hfQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:mL1OCUcVME9E/cGL+KtP/fk=,iv:ifHb80JECUF/jfNxF25bC0RKdrlvjta32312uMIpOzA=,tag:LAtL2qTeYjfECD6LtYgyQw==,type:str]
    NASTY_API_KEY: ENC[AES256_GCM,data:biT7po/1p+jdTDviMfXunukS2/fBlv9w9onlsTM7sVnxhc73QhpioWr//A==,iv:TSjjVhVIZ3H44nlG6cafipovfy7vQnTlPbdJE/YZvWk=,tag:AajsGBRaIzqAGCpsaLY1uQ==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:OtoOsDNGVe0u3I4ZnzUlKOAJminWq1+RjJ6OpulO/d2V+53+5XfM9di65q3z9vFNduiAmP7QyghWJ2gf,iv:E+WmNa01n//NIGNTIpEr2Mw4q+31gxeMiUEhUeRzF3Q=,tag:UzSmS1xV8la9i8z0pyx9Dg==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:xr4Z8eOku38S1S5IdztJa8wKr0Vvo0epktGKf/Yamf5SXOEvCh3ZJhrHca8DB9VoTo7PoUvMrjKSvt/xAEPp1g==,iv:gEsD6cPhpYECge+AG7tAbWnJSIftWDC2/+aO3j/7dFM=,tag:K2+3oECb3860NGTmC3+rYQ==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:OxJNwXvNJdOPf0LFcPTJSX60Rk+bb966l0qDPUvS+IPunWkXmEvqklBe9okvqHFD,iv:6W8NUL9UGyfAGjg7M8OLBG4HTg7zVxobl0fPulX9an8=,tag:5fGVTzlSpGJn4N7lX0azrA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:4j926NJe,iv:16PtvCDtaTa41tuMpthYKgGcq8o4eODpoLzrS7zg0dU=,tag:agBlj9DDbogSMQ0c+nkHCg==,type:str]
    COROOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:I/P3VUBh,iv:xCrooXGutOLK75mvirr9IWVhoUF7Eo2yeB8D+SMqytg=,tag:PdNctOgiMQwGaTMno6zEBg==,type:str]
    NETBOX_ADMIN_PASSWORD: ENC[AES256_GCM,data:/EmU+NsN,iv:9Xwef9SH2tOLWoG/XcG2DX0RUSaRt/h6lA8PGIseNWk=,tag:n3YVooTgxCxQJL7AJBqTtg==,type:str]
    NETBOX_PG_PASSWORD: ENC[AES256_GCM,data:NGFNRK6cBtvxocb2YEUVQJeUdVk0dI1gJxJ2+6o30X0=,iv:Rp9+R3/3rOcthBB2oyv6vpLmx94CGUIz7AtQvU3DNF0=,tag:EFk5FgwybVPy9wk0sQc7Pw==,type:str]
    NETBOX_API_TOKEN: ENC[AES256_GCM,data:yy67rd+b6JOvaxz0PiKYimQLTkoSg6rrBv8Feo06r2poWAwTsrysug==,iv:FQ7OQTkolhn0X+f3EHL3Ti6uYMb2rYxzEKH/DQAYUCk=,tag:4qdmeUW14PaSk/d++r4DVA==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:THP/MJTWXSx7A3XffbcVb0lyu1386leRQBz6HsLiroU=,iv:z8sA3DDRFjHN1Wvqb0JtNANrTAwwziqMlYe+pazWEmc=,tag:GVaqcR9jksNpbtYOBBDqJg==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:ear3nmFd2hFK5tP12SA=,iv:HIP7bEp6pGwXtlymTvEJDonZpNPgQAb3pm0MGsUdvpU=,tag:rES7ODwzh8Svaw1Y/qNbeg==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:xovMQZZa,iv:tp2PfIloAAIg/AW8FCrG6FypE1dPrIYOEoFQixB0L/8=,tag:kDsZkLhHUsSve0SCTDF3jg==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:MspcmjjfdPpoDzCjgeU5/bPoWHKUkmnpr713H2VAxzAOM/qc8yq2xE00vaiVhlmY4cyFrK5zv0fi20LV2kF9T+kIPe4FEIjwtCsKRcUMyK6D+URbRh3FFeDx0Nb0jZ3RCMqKvXp4oDRrHD+ERoA+7FbmYReWOmUYFTJaL713YZVrPTOd1vcjEGBXiaF/Bxab2aRFMzSitaeGDlWXxWf42qv0DjD7OgAoH/4nNXfk/cpKK3fVbpx1,iv:k7dr+j3kSZaCvYG/082RkcfHzXM/6+B28R+eRAn/IC0=,tag:iuaSRB9PQtC6Ffxft50Rdg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:Z7uU3+o+aWFx,iv:4e6iFZ8nF5g/JSvjC+isxdK649VR6gdYJCENgd1MxTo=,tag:vcw+GIiixUJei5nLkHY3ow==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:fKKaDrAHlHj2aMJpECh3ZRK5NnxV6gP/U9wkjtqsQvXKEylhxhxjBqAx+lO7TQ==,iv:TjcxXaB0EP6iQREOOG3G0Tb/n6KzIEPDvmFPiBQr3wQ=,tag:x9XxHATAcXab+0CCZDvfmQ==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:VWdAfndJac9vG3njv5E=,iv:+NUXECX7Q2F97jfAopoPb6wguokrr+erVFVWOT/IQ+Y=,tag:+HUYk8eNyHqNFpM1jajMhg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:7WPKCIlWqaI5BSX3ByZxpGhXaIdPhzuYFvcqTmRL3KeF8lBMUfGabYzmTVm7mcG8JDbGKuQ=,iv:ci6jmrXwKGTrvLwM2potYiEap31z0WuEn+2Ad64Cv8M=,tag:pt9MqlduU9tfwBwepHV6mA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:89cnzFSkFIAFKLJa5gQWPlU=,iv:uRmHUtRP9QlpS/JdpQEcRDz1I/Caubr+Jrd9oqjngTs=,tag:u6eKMVllcJm8nf2FwnXF8A==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:bc/XYJ3+tG+FN/BIPcr9rgu0QtaNUscOXTm90FTBfk9tb01QuX/T90UbveDio7EX4jpkel64+I87rmHwzsI37A==,iv:yjWpWWj+PuPfOYgY0cML9bxqgmyTkNW0vkDu4mOyuSo=,tag:3XcdMrJSnXPXP48lqI+ZvA==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:eE7AzwKSBnk=,iv:jEFFBGJiqaeN1mVUP7e9UhtYdK+6NAqcQo6yABuiqys=,tag:OBFEv1ddEN/BPH+RiGaDmA==,type:str]
    password: ENC[AES256_GCM,data:979ICGaBE5SXMNJHnWQ5nBixT80L+1C48gvPCgi/Qujo5jSaW2+o3hCjW1sn4EPH1ll1OwVOyly03DGK+QUlMg==,iv:hbf9nBtE4oUe33X+g72jqKjsuOQNmm5ofS+qW1hmMFA=,tag:pDgmxFM98IOeILyYBYKZ9Q==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:W8BIohupu0YafBglapDXR5QHRQX0ZgllWZ952oLikxEc9a/SVsdvTYwQs3W2RGiC1Vlg4sqVexTSdnNaik13gK4uAV4nxZ/EYcxPey63ew9ad8HCTD9JWflmG7qDrthWKmiWXO5hAoYIzT+9qTAqdqcy9yHSVFEvlcdbx+6XFGy5dJZ2hNTeK1eoJvSy4ECsyV1NS9tn0+YpEdK0ISBw8aEuEZnXl3lfPglKS0jkBl7T8Gt5UMisFfT6PbBqklCSDplsKART8xG7woU2DWfEjCMHVy3vgRwpjE8LgZzw9PJlW7jE4Bw+Vz+saZjWANc=,iv:bc4+p95rLol3Wp2tv3FK3zs+PHNTQuZWVpZ/dARIqkM=,tag:Wr5QM2Mz0I7C9AOBPSr0ng==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:/6bTe4P9WRKRQMG7WnFQeTvoEJzy9KHyQGaXafXGwgPRU/h3+Yl6THN7ueDmTTW29gK+GqyX79tk6Miw6k8g+A==,iv:ZhhTzMmJJIZ/S/C6YEgnApVF/XcxPHxErcj3YpsBMwI=,tag:kp6H4jbfovyQxe2XQz3zAg==,type:str]
    PG_USER: ENC[AES256_GCM,data:ZkMphA==,iv:C5wvJkG1zeORa8FP5deXIdbQC/bEmur4yCLSDaMt1vI=,tag:UZjCLj6S+aOmwXtcGbcChw==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:cObd8IVkw6wqwu1wrGK1AfIGkrLYNi65uhOxkzbRk7/sYskZjkOEJ+zcDA9cPaLsTSBRwQPnqimkRWFdkLcw8Zfp,iv:bf7zTPRKz0+AM07GZbPsT1RvtRxyKzBFJGoY5McgwAk=,tag:K+dPQrCZtHVybpnljmqhNA==,type:str]
    PTE_RSS: ENC[AES256_GCM,data:FGc41XG6bbUuv/6QnL9IuOvivcs0Ekrfk/H6c6ekO1g6a0R6dAU+kO2I+sHtY73Su6mdbj2JiYYCFrTCfv2jhCImYx0+MngNJw==,iv:8WM2H8OIFwESPZEvPXX7nuUfzBkgYHL4zUGd6Vfg1ls=,tag:JVbdSOqjrPhn48hhEqOyVw==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:vJgELxfEKv5x5J1geAiuCqevB+SvJoFInRrvtCA2YmCC+GO6chi1f4W95mh8b8+YWPVE/2WtxJqFxAtroDMx1O5Wefh6veG7oRVsIpXXh6j6SbpwLQoN5+HlSQX1M2oETQtsAdDK4Mqxd66EcTv+N4wJBBMDRI1F1rXU0zg=,iv:WaYZfBFvCPY8UCCssuzNZISMtGZuVH5t5NnZGQDslsM=,tag:/MFbt1OOZOaWq8qeuJeyjQ==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:6puKiaTPUa44dUn9ZGnI8KiGAgKzKYWc0AezMuULPOEofe2Y3lgjAeKDYrnst5YUxVYfiDwzgErAh9MW7cIJzET9cAm3PvKVX6JwPf579uRxLE0kY18SY4+dHX7MJkTFPAPJc/mzEes+94rTo2eHAZ19d+qXz6NlrlX2espBDMKmxtEe7DkA+6AO7hWaRp3h/vpgAvXdvWywbk1B/KblHcIcRXw1ng80DWr4V7bnzJzniv7CDieUpMu0rUWgaHgMB1Hy22IrAeGXU65PNCdV9mx9wur0thVgGLTZt/Iaw7vkJLDMCE4XhSCZ888hl33/A1CbHDIgOiOfuWPc,iv:Sq+jpOtUYugj6S6TE4mMNZPopTaOxi90c61UWJa5uXM=,tag:8xENMd9y5A127a11G25ykg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LWWH4d7u9f7mCqDgoPVWlJbvlujZQaV+ZGw6dNGLM9sac2WNVUV7gVBprcPx3JpR5czR8XaDLlLtc/F4fMXJaarWJQ4AlFohE70L4dRWNbYDbCs0yg7wkIqoyUdn2Pq7ZU+KwftLd33M5Rj+/WHcmFg7qcpDuCP2LMmPtN63ipap9+A+oe6i+QaX4S18+YUKd6RQFkZ0KlataYOVSsX+56yk1J+Me1jQ2lTC3m8IbNlzsonSYptd8wB3fN82YF+ZE8TvuSNxdIAj6uw0ZYswcbelEkJEvB/ugE6pXO5lwUrFrdO9gB5/o3nsh2fd+mReFOdH6sIo5MMTfB3912DEXimKwFQjh0cXDrCQOBbVKPXnn7lQuElQW+GkLMhMHxR5BfwKB+aj+FW6NUxsDHgfJxERTqt44ps1dTyGVWykAkPEXIqL785wic9M8hJRP2EbrPyiRnEDXjxW8u7m8Y0Uek1Itz/SUN6pCAvLwRem0Ezh2xZb8hFftIi/fmwrtBdjDJ4q/djNAZg9r/3XIfrKMr8vqU6vsvaqppr3DH41yvjoR3gbZlkh89nnLqerW94O+oubvMk4AVjVScZjwYWtboi5meCgnBSSPIAQO26jU/e1vZ/+lM1B2ZvVjJBHj4r/pexaXX5bp4YEX27R9iwmwt8nG30+27XY2Je9D0PM8lfKLWNX7q4qfwnysCKjsWnQo1DoJtj6inOa5vZ5wy5L6DThEzWRgA6/aEEp+8LFTe5DICB36aoVyyiOUBfMLt4xNZTCTxfwA99UUC30y0L2QBC4L3TKBJQHb0qwPRUwQs1vs3em9a7BF3AQyY41bMJWgLVJ+/030Ko24XUT8NcfJKKIPAhcKT4YolgAPbmdyxuD+WZVq4Ef5vn1P/MH+BzwZBbUdXtjL3mXXJLMxMPiOL7lxIqEuMSKNQaGndXBsq/L3kh47pToqYcSTQuTKIxNxrvF6FaeC6MbqATP/5mnJ1Q1FMPStfi1fv7Eg/zehUsmkqyk4xbEZQipEvs+IYGvRHcRbkdGSSGlNQ53OVbqVBX38tzex74EYURxavKwbY6vGENVUkPFWgUIpi0nGqNG105YDFFdcxcWr0gF/z3tQ745b5Xjjo6Syu0dCDZ3ZURGa0YM6Pf7hEU4SyOdbHsEcVu3vC0M1OmQiZKzf3HXcEKpm24DJYyY+Ub+SFlDyDO0Yl2RRMS/IVYEv9Rc6CqzYSQqAwRXjkEUBzFD4L2yTaOwIvvdJlCKM8V10ZzfCIQ9Qimz+9yEO608Oa/yDtKKJrorZlsY3tx60pVMWzDzuBkFtp6+NbZHGiUbOWcMpkKbWsK/l3Bq0Z6C5Y3087zOt6idmbKXxP320MJdha7Mt2hxX0hPyjvRg7yJMGGs+OXaa/gcfO2Ob+pSnKRiPo2UZOmBAooC8uRcA7W+3vnnDzvvxMXfm0frJ6Puqrw6x3ocMpIpK4IjjCqrrKFGqPlQNsRC5izvixpcI5ILty+0FO+ZP16ZfV5C8ov4mTTomM1p2ulnmcaI8Gg46NrFAAqZuGicVGw+JsfqD6c0ez1dyxZJ957DWRqBoSoE5dKzsbHZhIvzXVQbg13TnHcSGj2KsspLzuI8TGg8R/p3AsHYclYAiideId345czRdZCAWthWb+gNOKh3FN9w6KLcGrvAuJpvyJCCjjJEEcDCfxZ4XclB+/hlHED1K7n0g0Fi+ni0ZAVOGTZFoCVkUDpCs/UmdRQQu0zqdpQyY6x1k+UG1gzyCjtOx8MUUfxn7OwV4UrsrtqVOCdHJNLwcUtXNsFVhK+ygFvS/c0rWvGJaMA4apqcLysW4atK5ofDEs+wnYJ1WykZZ56ydnOmJ3pE3IM/RKtEicysv4cNzUomKBSZkH/2M2z+8xvssd36Y5wGAUta6Pm14tfQi28y9dtkpbG2RagEp3whczNNWjFQo3jkfuyxibF64LZFRSzhvSJFj6dD8Nr03mSH1CqRKBOl/AJilON3N/S/V+g4J4VDPbF3nXeE54q3AAkbG051sKU+Qwltbr0eeRaWESIqDVsBMg6w8h7zgm/8FLl/QRZ/c8gTtluv5VBPBw5EZS6CJqOJrl+NVL7kkzTNJILFCQk2BedRKbtEedck0IRGUoQgQRtecmOocHYJIg2tzflHQHZ9PST5v5S8Hw8jaxz+4Gi022qjCHsGBSM3f9J/pKY7IizlfGMbgpZAfL04ePrbdEJqkSU1gvGd5tWqp0zdcjQyG9cFaOGyzOlxVFanFCmVgdybhVU7P2xa5UDB/ke/AzD6KbGtSt/5j/g9NfdoIkrWL4i+W328ErLlv3nYhMWAJsvRu0r74qtD5EyKZPYbFhwztUbgu4xfEyUjY+e7hMGQ4GDpMJjnDR9dZ2QmR1C57HV5w3Um7ejaHcTEUkk48On4vVtQyjhxU1MxYI9gOgZqi4HV1j9wLHbSNSgI/SQ2F+tjuoTAqFcPmeNgQH1wQv3rkYX/bgYdTbyFF6McUSwweO98IE0UjB61C4xUWYIAtiZw++8SoC4nbpQUAJJd09TbnP/qFvmSyTb5HKt3nTby/06rQXppzkTTDHPtw/sR9X+cKbp8umgGaw462U2RldwRu+QVNBYFQeoH4+f1YuWFskULLxjGqFOKtvpGGMQjMVSszDsYMv2xPynSfEfukNDKS5rIYehMCNJ+SDK6XHch4/CV+LGkCGenZfkH5U+BRp7Mdm/rhE7IpdWF86IzWadmhfhK0AC9AZOs6200KWn2hJhZ2whCAXHfKrF5V2wL7DTAlWdm4nzUbiivtEwRAWvg5yhRdEN5qVspihqH2oqmqOSDkRCWv9HIuspSc+va/cjGpi1pNirtf9ffXrgyVVkeguuy9yQa2UjVtlmywkwZ5M6tWZ7+V2w+TRRHgSCChDs/SR5JDV+yB7coN6jKriT1pPtA8VEOwY4AjY0eunicS9BSYX4VtSk4I9A3tHKqCQ44dVdHKfgosYNKZgu0myhjYacvavdWpiZQZsdy5sHevPDCdaFs02WGUFFEx5iIMzNn7etthw5LLoIRqyqJjTSi2M/Qozw8xs9V2zQOq88TRv2BIxdyZS19lEjQHBsGmwsIZCVQU/1IPNSkABGEk2/9xWWPSJ731yoXlu6oLqY/wGp6eW9USxhbNBRSVVx7RLPjFEfCKiZFVwjYCcE8pqeoal2IUJc1ckUgkLvBPjK31KzxVevJbUFiudmCDSbwZ7SAmX3AFxkZ7M/T9C3YVD+weIUY5DPu5//T/cjmwaYXQd0nQKy833QHngr4afM/rm6nwUk7EYfniw4SwlK+MjaR8GrktxRSZvcLD18FdC5HL8xuGHWjSEdU9L5ijijV8BDqdFWPZ/9xDjJOABr+/xQnD54dBtS8iTtoeg5WMA8wKUfpehZUVH+mBx+1Rbqz4QFxoE70+w2NSfKFD0A+yULHajaYceG3/gdl30o6iML5ENkMTleABp8yrOOrZA==,iv:jIIOFzWiC/4bapsvgoXprwX1+Yqw+Dl1gUv9zAdeVmo=,tag:YO/hG7JuLoZiRT0zcwPN6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:XmbdtdC2MSManMyKKTmF01ws83ldjQi5Yu/XMDfWUMGOx49CvyBzmCmCTZaxYzBeiuv/+OsWzckrQPkttgCZKyF0PAVz5G6uIxv8XqakR4Ni6Ra4ENSs8aSw1dK3vXAVJ5oNMGCfEJ2b3ShXAVPClNjb9Wn+/KI8HCGJAQp6HH7HbKIupA4AwWu/yLvTMAoCVUAUUglVyF7fjjsTcVrz5XDHVTbKnLZ/ySIUERlyhxt03U7slYFhl+VgLDlOE2snGdrKO3mJhrZefTTQNQD3B57JaQ8yQXL+Tl5WSLpG+I6nmZbInoq/p8YMneforc4PNIi9zo5dYM/SLV2sWR+cCpqobNt8ku9NTB2pCOMErAcKSnKMS+GeayEOIraDTsNEXbxHy3hkVIAXpB1Won5UGYhv7A9Z/7moYMyYRv01/1rrMCUNrJoR+ZKUyOqvbb4IdV1KZfiKwCjdYSm+dR7Qeq5qOAW8uPune1ejzKKFFHBxuGBqzvsoiQ6aPHliVlO4lNkdkqZ+H3wDbnYlA2UTugj6DENC7Z8NYeDxVpYHnGFQ8F1+6PI2LdejYFZH2Ljl3iF8FDvI7uc3xoSzLdsAazjrobU5L6qwiRPWs9j8x9T56NVqHpeH5gBoQq8kfwcG3bapfo3+coId+mqDQZ9gbHZA4DzoO5XSxvMGRIJHJpEzsn6j4Legf/Cg+cyo5hB76rKFJbyf6YIZSIe4xK+y6XPIHajri31A6Q==,iv:NQBW8bFe5Z+e+urLY/5ooccH8Jwzhvi7g3WEcQ/0f+g=,tag:wRsunCUDyYQdv6dIIm+Jsw==,type:str]
    known_hosts: ENC[AES256_GCM,data:MU2E+P6c/YGda2UNeerRmToLGS7FAJf2iYQsmaMkbpm3XkQfAJ7uSTI6HP6TXnNbEwfrRLDm7MQ3/FKeLK6PUnal4Xar9i5IRKevZO9JXOefYE7ySGiEfHHfsUQ6sG93MVrxYpo7FzMBQAoD092wfXYcBeL2Vy5smJSbGhm5EuVMNdNE3VIG9OBZBulhxKku4PscBota9hEAoe7yUhnBCtpkIAytK9udcb03,iv:HfD0pmCoV32TLL2xPRxn/V60YBZFBMv3p8yzdcyGYUA=,tag:G/FBNgW9FCdbAP1labGaXg==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0NGSzdiS1EvU1AyMVdt
            VU1DVEFCQzNEeFIwZDJiZ3hqbktPLy81WVVNCm54U1AwMUtGNEl5SHdFelV6bEZT
            V2FPZ3dKSzFCc1ZCTVJ6c3BPOE5HNlEKLS0tIGc2VVIvbjE0WG5xbjdJSnk3LytZ
            SEl2aFl2a2prSE9hY2NhT0ZPM20wNXcKw5xLPVqbxf2+zA/lTudFlvTxosjcB+ne
            zjdYPNS7a0N2HclcapPrr4gTXSVx63e93yFqzkosz+JTc8mtGnanAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:30:50Z"
    mac: ENC[AES256_GCM,data:Vj8ALEpD6GrFOHzO0qTVBcXMSxNrUlf+gASwjh9ApKZtTCyZ15uhTIGd7DJqyecIQIRVJQeIqagkPhsnCvk5I3HQvyL1cvujMPyCjIFVgCDA3AAYifzu5AvmPPmwdBD9tXy/9LNLupr7isT66jevxJec7Ez2lDmXy+qn5oqf2u8=,iv:QsFL/b+r84XzqQbv1GpcyMZQmQfpon1J36tcpm87vvA=,tag:OGuHmq/e4yqGd0viVO+bkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
