---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CONFIG_NASTY_IP: 10.10.20.100
  CONFIG_MEDIA_UID: "2000"
  CONFIG_APP_UID: "568"
  CONFIG_APP_GID: "568"
