apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Q0NEsg4=,iv:zBgHS9e95kbJ+3EI0qy+/yKjdq6JjOHE9+ko1HF9mrc=,tag:+6l5RZ4T3sdup5BCLNrSkQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:Kw5Svc3rPmK52X6y52kcQRU=,iv:KDAlhaFu1+Iz3U/yxL1KK8NyRBF7EGe3fFmuSQhEIs0=,tag:DTWBQ4vPbJkunn/v3eqqww==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:d32JQxuuzIlU6gnTlktyOQBt+wQ/VJTdJ5LuH07Gbi6cOmgzbOw3WaetTRVp29IhTbU9O2AkQ/JxU0ir22h+ue8HnQ==,iv:0t4A7ZA0y9qyrXpwdQ62DjD4ZaV0uS2jTkrkSHqo7V4=,tag:kATta35IVzNR+UEYPfE5LQ==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:3sKlpKaCd82V5gWek0V3wJ9bA3ZGCyLVAsCAdQ+mhwthCoOOXW9fQSo2jSLppU9g4Js8JVdfaxmwKkiX,iv:5iYiqQWADEp5YMRxemTglYWRLoFcRLaz+HG2R/sq2Xs=,tag:H9mDkgGlp52ma3dxtOWlZA==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:ESDBUGJfePJ1SUmdKc36TUndJiw1Gk+p4WW4YUbCoY16/ubsVATGiV+uk3vYkyS4ihBmQw5IQ1eEMxs0q8K0rg==,iv:BlCXmixQ9eFtm2BwJd44q0CNDAFD4ZPJwlsnzYw5g4Q=,tag:hE/gw8bFR509DeCC9xNHyg==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:nr1SmYeGtYLjl3X7YoxY5UzKTP88cmEY30r2Z2jWuf4iQLpCD3LSsKwelBFe8s7uENw=,iv:msnrI1AwvF1Ct7jtRAGKiHmGioOF2D8/XMjnbzv2i+g=,tag:HrVlY3j1W4f7m9ULwUBOyA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:R8lWSNR2a4AZOr5MG/Jk9JXT4UlfzLirD/lfsTJELPw=,iv:jG9RaCgSvR1LsSN5tqiPpLpwVaBc+QkHJmWU8a6ORUs=,tag:LtKCCn2uQcligS5AvB7o3A==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:ZmMku9NilsqheRGV7NUlA225zDcPrdR8letxGQKGtnlxpz42PdSc6+cNvzyrKvPFGmg=,iv:sWQ2HRzi80hD7zxM43P3q/WpnMUYVdj+IXarfHdMnPQ=,tag:Zu3fByWKY46Cz8tkBzpuiA==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:lFyZEw9Idg3BkgeBCp9usIIGUOM3i915YceG6T20DgQ=,iv:SZ0B7ip32EpShlLmvDbdIChrOxMTVTuOPHHsbSSbgB0=,tag:3JjwY721FzgQmX91rzO2ZQ==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:9Nu0TES8xnBbWWvDaTIgW9qbzKyCowwTjMN5CkJFewCOABZ/FkjKqZZdpnTu729FlbE=,iv:Dvr/cnYRrdxRrM70vM7/CMxgyFETkW/1/H5ZsETvn34=,tag:5TFDFfmxAdNDymw5GXYA2g==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:WPW7PLSp9C45M07FvWGJvlVGO+my9gRT0ybXeIVnnOQ=,iv:tdXTCICyk2f40JmmyPdK5bsACvHmKuXTGIoiCtUonss=,tag:j7lxHD3wIV3/cQl43/sQjg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:LKvus7YR8p4OJ8XSVUs2vvYaanCbVjBhE+8PJVYwuUUtkNGTTPDMgR+VQeEqF7yZi6Y=,iv:Nb5a4ZjdgbyoPcAU4XSW7vWLPGyXN6hWTS4DUzOGI9I=,tag:Df+5T1vba1zqPrJy8uRlkg==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:N+fcHs8mJ+GgCyIjFag=,iv:iZRKaMLPeOF9ge4pKMWCT5N59NvJJ+I4kUY5EKo4MPM=,tag:5SET3aAiTx7khWit4tdfRw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:oeVNEk+ApXAu,iv:l3xXNoqQNlrUgDJE9cHwsKuDzpcHRjAVhzUwjqcD2O0=,tag:5ENzUOHwQlQcYIN8nmxaMg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEJiUEtFNkk3alI1Yi9V
            cU9odWhkWWRHVFhJSWRkR1kyMDVkMTF0dkdRCi9xZE5sMEVHeXEzckJkZEF6ci9W
            K0NoSUNhT0hod0V6WjBpZCtPZlkyRUUKLS0tIHNtYWFtWDJEbXljbzV3UWk1RWhN
            RW9qTU5SQUZBb3BuUjQ5T0tYaThFVzAKeOWw2GqAPvpUWioPwv6n8WFUOhoR23bG
            n6hmkDIHdYyUek0KGFAOsNYpx2TISRBilBipGZhvVijuA8ELhZESFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T23:41:34Z"
    mac: ENC[AES256_GCM,data:G8Y9doPtbmBjz5muTXp+v31tlLglqefGeGbzTEF72BqYmelhDPket33Z7TPe1GrI+zwKmZTxhGknE8dP+fPMzIak85xOqIJL/dQTgSTIg9B3434f91sHqIWWerFyfKx34pFnQwXTDwI37iZZ2UmH5ieZfkU+3Nk1AFeMK2AsW7s=,iv:ElGii36GvYdHMHW+J3BGXUOQ374WxwQmcBLpXOiOwuM=,tag:M12mhn3euJJubSCyr3DijQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:wZHDsxhsh2nnipR4qa4hLLQL5OKmCDVCMmOarT/m7upG6ixgSs1rZQ==,iv:MbSOjbX2/d3lCe93LG1W8bI8SRR1WSotL6zm0QkhwUw=,tag:wS3EY/2bJfMEdd4fc1bzZw==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:mqzoUx4nh2+VTTEAWCDRcDU=,iv:qWXe9P2u5VVwASYRujOEHfm6lC95U+KEmQkKcFWdvJ8=,tag:t7owXC3j7TXuq2dompvoBw==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:0lPRDLIo7ngpMeW5PpB1BZyYhL35Oy53hIUFGieRUuSz6HtPU3jZoSGFgAX+kPvkhP9AZKqzryalPerRC52ZOw==,iv:1jWAbTPFW8AWzgGa0ZH8na5W2icaW1Dwr/RVtKbqL6Q=,tag:CpKZ/ePAkDZJTzpCcq95Iw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEJiUEtFNkk3alI1Yi9V
            cU9odWhkWWRHVFhJSWRkR1kyMDVkMTF0dkdRCi9xZE5sMEVHeXEzckJkZEF6ci9W
            K0NoSUNhT0hod0V6WjBpZCtPZlkyRUUKLS0tIHNtYWFtWDJEbXljbzV3UWk1RWhN
            RW9qTU5SQUZBb3BuUjQ5T0tYaThFVzAKeOWw2GqAPvpUWioPwv6n8WFUOhoR23bG
            n6hmkDIHdYyUek0KGFAOsNYpx2TISRBilBipGZhvVijuA8ELhZESFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T23:41:34Z"
    mac: ENC[AES256_GCM,data:G8Y9doPtbmBjz5muTXp+v31tlLglqefGeGbzTEF72BqYmelhDPket33Z7TPe1GrI+zwKmZTxhGknE8dP+fPMzIak85xOqIJL/dQTgSTIg9B3434f91sHqIWWerFyfKx34pFnQwXTDwI37iZZ2UmH5ieZfkU+3Nk1AFeMK2AsW7s=,iv:ElGii36GvYdHMHW+J3BGXUOQ374WxwQmcBLpXOiOwuM=,tag:M12mhn3euJJubSCyr3DijQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
stringData:
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:gMi75A==,iv:lxFh+cMq46J8EWKjGn4ier73KKDl2gDX5Ezsj67z9P4=,tag:raYL7pfW1+eIdbvzmWXn3A==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:elyKbjU=,iv:Iy1KyjVxGllUpbP3bFXXkFuhAe2LOamt76xgBXSRPYk=,tag:of7h30jY0YZAFwyGHdLnBQ==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:bjSLGoLuypR60610+PXxteTN80nWuRJjwJFqeZ9wwqzeUiyg+BHE93xQBrzqAtjxLpRxOqTD+ttqB7CsioO+eQ==,iv:xZRrbFPQx4yhfDbpj7ARrJ6XaNkFBB/MOq81rL38TaM=,tag:MVOz7Wqk5JJIk8Jbw5a0ng==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pg-password
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,database
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEJiUEtFNkk3alI1Yi9V
            cU9odWhkWWRHVFhJSWRkR1kyMDVkMTF0dkdRCi9xZE5sMEVHeXEzckJkZEF6ci9W
            K0NoSUNhT0hod0V6WjBpZCtPZlkyRUUKLS0tIHNtYWFtWDJEbXljbzV3UWk1RWhN
            RW9qTU5SQUZBb3BuUjQ5T0tYaThFVzAKeOWw2GqAPvpUWioPwv6n8WFUOhoR23bG
            n6hmkDIHdYyUek0KGFAOsNYpx2TISRBilBipGZhvVijuA8ELhZESFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T23:41:34Z"
    mac: ENC[AES256_GCM,data:G8Y9doPtbmBjz5muTXp+v31tlLglqefGeGbzTEF72BqYmelhDPket33Z7TPe1GrI+zwKmZTxhGknE8dP+fPMzIak85xOqIJL/dQTgSTIg9B3434f91sHqIWWerFyfKx34pFnQwXTDwI37iZZ2UmH5ieZfkU+3Nk1AFeMK2AsW7s=,iv:ElGii36GvYdHMHW+J3BGXUOQ374WxwQmcBLpXOiOwuM=,tag:M12mhn3euJJubSCyr3DijQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
