apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rBxxZJA=,iv:a5C+RjzPD2pJ7+JWZBQKGLvtRdNgYVEhLqUMeclm56c=,tag:fk2DjbbM6qUb5DlF8j4cTw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:f5pw/RBQFXO6l7g2pV55G8A=,iv:bJJkyRgC+1BOx72Fmm/00n9wQ8CqCObY6WPDrHTqny0=,tag:RtYHYLMZr2dnDCNBMWzG5A==,type:str]
    NASTY_API_KEY: ENC[AES256_GCM,data:lqqSapPpcxev8qc8wsDQ8EGMxvoHNKSvxee4X4iCzIv+OUmEVCQJ3jSwAg==,iv:Rtk7lYjrm8HFoW0AGDBouJDjJQBCs0b4FL849+M0KPw=,tag:Z5T0l3NDBI/QK2DT6Z8ftw==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:RtR52VjXYEVg1b7fhAhWQFRSBl6tmTl4JgZqvx0NVCt3DXZ8ewapYqIjgwWf+6hKOPH40Gdq1DvC8Xan,iv:QyNo6F1SUjJhP2LfdpHnzDlXFC0KltI7+X9ebzuEAv8=,tag:cwdc2W5XQD88sQMuamS+KA==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:XukRR2HIOGDAIZ6jTuADcmNmFbLvH87NfHtqKW3IAe4VTEMLPcOuzfhFnAqkATef54+EH2u1mltQw+as/dUxQw==,iv:DJl+cpSP8X44hH+pj6IRPL8ayjytJjgm63l6Y8X7JFE=,tag:30vjswSOKhr8EMAIZdkG1Q==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:c40/bXZIz85fXDBsYkvpLulLBk3eGtHzVNjn8vXFU7tINhlow/+6VEIbuK/SCOJz,iv:pDXdunm9QUKmQgAU5Y5RYCQdNuYlHhO2ZiJyPcPu9d0=,tag:WM7ERLcaEHqmCfZ14sw/4Q==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:BFuaqMuG,iv:QooKzC+p70cg/grJV9QwcJaMZdLV/RgIcALjlPYC2HE=,tag:YsUi/XLvYslSLyWXVtNxCw==,type:str]
    COROOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:TpfZKt7t,iv:dd7v9cTqYjaM0RuCuYDhe5S94Lw8HGrTVYD4T2XmCp8=,tag:mnrmlJvY5a2qdrMAp7P55w==,type:str]
    NETBOX_ADMIN_PASSWORD: ENC[AES256_GCM,data:3HVLv7/Y,iv:sNnFTUaSSN6rEFv8CXCxnhqXuWLgmuiG3tlDWwNpMIc=,tag:2ZHxCy/fA+rR8WkOkcsWlQ==,type:str]
    NETBOX_PG_PASSWORD: ENC[AES256_GCM,data:M71RDP9eEyp/uKbQMpyF7ILBJvti1oYuvEgnv18rlDE=,iv:afb7vRsrkgUwx8fFftzV7qrQPehcyN/ZzbwxpJiFqNk=,tag:/HkvjN9Us3VEjoSVo+kiAA==,type:str]
    NETBOX_API_TOKEN: ENC[AES256_GCM,data:+9HjJunuvwNdSkivisAA+kV7/D3eQcva2hAEUKBJTPmhE7s4j//oqw==,iv:kddZxVHYSlR2oc+NeY+gviL+w8SSeXSLPoYMXqIVctU=,tag:JwugA7fdxQJQQa4bUxkihg==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:j1wdnxzycBL5TfYlunDjTlQskHvXgGUeWXX0Yt0zmgg=,iv:Pzn8Zl+OEEmDeI4wOZFGRE+ebOymQ51psCKeC3M+beg=,tag:QZkwGQHiR05qbIwffOsz6w==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:BhRriwod0O33ioCA97I=,iv:cmRlpNpTrmsY4oVnsVWT8GUqZ64/d2vYzczo53Iqx/E=,tag:HDCP8A/O3PAIGGQdeubntQ==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:d7meVg0E,iv:mKviI2+VV9c/nPVzNlgaH2hpk2RUBUyVUHdky9Ler9k=,tag:Z7zOlrmD3UR5ZxwG/cBD5g==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:Fgdg24w5JQXovNcKMlgQlmU+mFkTu4WUaIAUmHLNrS4/H9Ft69J399MiYqL9MTmNMOCz3m8G/tDL2vs4Ls6DoKRJ1VzXnu4pvw+CWwlxna1VFp+6ITAOAvDnRh6CwENbBA6h2qvwCii+Uj0VVQfroDeEmvBvQB+Y1OGwTPOcz5d8n8Ic1QU8KygZR3YrzH1MosxWl6qyAQzGuuPh1NBwVHU7GlD2h1aIH/LGgNzPf2b8KVhHocku,iv:L8v9p2SFTUzs3HP7AyJip6dJri+iSqP9n5td5oeh0Jk=,tag:B/e7ZZvHGWm/mEKo2b9SXg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:Y+GVuABC+QVy,iv:FS/LeeLbbtffJ/vWmu1zGHxaOxsrBnqM+5DcBgAzJ2k=,tag:Y7yFFXGdH+ZLo676uIAmeQ==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:7rQtel8ls9j2RNB/Nc+CPsJB/NJYLES7oIyy0dRN7f+bgpzGxpXqZ9h10RT58A==,iv:dOvRp/lYRvQy0c3Deh1Bds1UBaOE4MLac/KmYxl6H7o=,tag:Db0McENei+Y5jDKGMmpv3w==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:U5l6cfcJZAa0YOrI9y4=,iv:mFExdJd3ddSYGCVUAA8w0oniKW8faV9jHP+WBpKpPFg=,tag:iZFj5p2s6FXRnqJyIke1Pg==,type:str]
    HUGGINGFACE: ENC[AES256_GCM,data:57cGLEVlevelSz7z56hHrZQJn/2mqaryC2xrfPuDXDgFgZdnuQ==,iv:Z1QAOP95haUBKUnqmRrIg1EC5RwMc2y+vohnBgO88Js=,tag:BHXRw/kL5BpNntDAnc/V3g==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:xApbqEhnROx7rCeZBqfHV7UgNArqEgb6PyWZSjWv3NRAVd0wRIwIvPWkZa5IfbPvMtBMZRo=,iv:o9JZnnQKMkoLthxvulOTuX9w+6i78veF1sCMZqXaioE=,tag:+yMBowy9Ik/RivTTgABI6g==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:hEb/Et/oldrETU5KLELZYrs=,iv:on9dBiDeB+Zrco8vxf1m9tR6ahxrRYvm3MDnQLSDGuc=,tag:O+y2LACYZFB7w1hkM+Re3g==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:+an7B0zWY8IRXcJ4oQnRva/gkCMXsK9j6ivg4f3pldS680nVz5vJe18eakyNxlB7HdGXH9Lcgg/imEWURyxokg==,iv:JajKxqwRZGDNQcsLHXCQ4GTKv5Ns1PIe0QX76HJKvkQ=,tag:gU1m8h9sngImH0YkFjEBiQ==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:EpTjR1N37RA=,iv:DH5r2MEvXSPxAsFUcMpKRNUug03k1UnCeih1l1WqEo0=,tag:DckQk2DFQxFuxUkKeS9Hiw==,type:str]
    password: ENC[AES256_GCM,data:wyalK7ns9OaL1y+a/2jiMt8AI+yb7hcrZUcoydv93kNsyrGivJnElgQ1uYmoFVozxmkh5e2WN3NePxP6SrJinQ==,iv:3rTN+dAfuRdl14oTsG3AOwFGZUgLkDExENDoVDkKb8U=,tag:FHYMDBB2r2pMlNTGum3OHg==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:Wm216GtKNUTJNR4ZGyRxrbey6Pxp7sLg0SmLWB5eaP1CEzp3E7F5MTtgpbGFfxDNKfKO2U9cuUJJQa96fxWvAGvGNaohK/WDKd7+Nz2ai7cNhfF2oDb02J4A8mkMDsElBPH9+S2mUGiiLWgvSGsoo+JpE7C50j1Unik+HC8MBdB62mYJi7tvMWwz2vzeOiWHWox5HqF5ULQQ4PhPeTvfbEk4ie3sHfjOCbM4mF3mIzBjCmdVwofjJ/y8zrS5WgzMwPqnodIuNNGZjnsNFKfPam2rE59hInA0sIHCDLzntrqDLEITYIBqSdSI8Yfai+k=,iv:LKvfbwi0sgK1/y2jZvQUo0EbFC7jn1M0Yg11iHrk1+k=,tag:0gl4TmRNYCCwgpcbQutoZQ==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:Ut+2gdTrkqdXhXdOW0vlUz9afA/Cy2jXkiZnRdBg7uFF47tqqgGVcdkLBb9YmTsLDZlJk5OKM6BUtgz7Sst6xA==,iv:71n0yV9JL9bJbCRwisYWDWy7aYnznz+DogidgE2R04A=,tag:95b8zOlRMt2dRS/hN7Kcew==,type:str]
    PG_USER: ENC[AES256_GCM,data:TIC+2w==,iv:zpCidEw3BKV1Qwew38pJmUlT0ztklz5Fpj3DWVkCO9w=,tag:diiNRK0Q9ZkMt1JYqnAR1A==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:2EG7ej71xM4aOf4t7w+4zZqolm4UyzftlndrxDYdyKZah01LyPjx0VZS/Ayyf+ScTNEZLW9M29h0dYkwIH2biCdV,iv:UDQIQ6xMpBRJ0FR0XS975rFBbcSlnkHDLzDWyyATvZo=,tag:weAy/Hv2Y3pEKsTINzLzvg==,type:str]
    PTE_RSS: ENC[AES256_GCM,data:oezueznjzTriDsVfdJ47f3vW9Vnz02t2nWWdR+Yd4DYe3o/LzbqCGMUoWQ+Q77OcAio9FamqF+XcgLeavP+tYWxu2iLZrDwHfA==,iv:7c4Yihe/XZgIBJVjyyqSKoZ86jUw/Wbf6kCf/dKTXAg=,tag:3GaZhb4IpD/fEBLuzZyWkg==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:ZPuvn3jhWXRokeKBZmihkvNOjAHfILQLLsR5hQBN4718yZ0GK5IU+XeUE/AyyPNfJeuEXpbTRxKJuYg90iNglFpLkfu+haxoxH/ga0v/r2NsNOzN4RJLr7GNzuywQu4GaxY8wSz5BfO12ehrWHJynQxh93C75FHfCSpU4Sw=,iv:xpgG6urYaI92rsLqNBnzd4iHiI73q59T+NyLoFXIgm8=,tag:vR6sgFeR7YPzuUteh6D9Uw==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:F86NomORkHoK/f7vFqqwZdQCF+09rMKX83j6C/arPLRVAliN3dCj2BTUoy4TJeXtNdeCPw0cSyrHHWsThCzKDzjLHXkaGmyaBoGBm7MHyFeaeRyHs89PcAtrVdLZmLaQBS9JEdIEZCuaX3uyMlxtdyEVtDlTyxBRAEid2fVav5+XF8ovIqsAcMatTsiiIHKQx1Wb6qoFlDIxrwk7uZkr6WLoO42oLZIX4DhdHqMRK1PAOqnOeWrI6s2HbjhO3im/VnfJlzVCLsuxRj0bSczqOBnmWnU6sqN9G2oyxAOr23SoDURlJ2WqgOlbDOrorupRCHChvzp/VH/f22yD,iv:sLWTYESH3CA0Wtju7+JFWCiJv4KmedMeVpS11O3RE6Q=,tag:edSG1LF+nSikNDhYZt19BA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:o/urQjQId/NP1lVlk36VE5kSGXO20XATbncHAaLQKVPTfEabXmTugZ4O0/95Pc4acE80g9Qzi8CANHBWwEcaKvxIhbEbbuSWJI0mv4LghSay4EbGmIvwhnyys0KfYQP0EDXPrtMVf+brNqt/0OP75zVQkQWUWHbGdIFJ3cPR/TWnO30D75g2TILnuGa+ho9EIUPpwIpRdikC3S6G48QhDpP/mfEgo+s6Co56v4mV0+nNPeEtnrai7M4oFGo4xnx2hgIS5wW+0yToDF1T4RQeTlFzhHoS5RJbZHbtXedBpPjzetybivb7mRo5b/z7CNtYihryYJwGGu85vhrEgW+QLQzR7WsPTkp+r1iPeDl7ZcdOdJoK+6sJLTEZj4FiW+5fX8giSKgsrkd0pPiWdxYo7YHAzigMFYcdgYFrG2NAK8rOxV3GUAPN3IMFysjQESsOtNbPEU2hGIeFo+wpC1nz1BYfyLadbhMkEjAx407ndMJyqzoS9+41mBqE9NJcxNfvJLa04zHsah2vR00a+oBmOtFiQBLyYm6lduOm7K44fzPn3uVc92xfV+rA1cdcpacDRLoMtXAxdjSRzMknxyPKjiAaodQLB416N9+DCTMy7hZlyXQk2OF7qzxklRda/puF0IIgtpFuIv4kOdtKftlgmWLKZz0RWQtSA+uMDPyL5LjdHy5lqG3SI8pwLGfS7BFB+Assd2r6py9dEtFMd2f0LN3ncWlPi0oGeZijHcVuK2BSLkmaeE2nv24tnqOFerDUSl8snaZq1kRh3O6SHf8YMHcJQtUQVRZgZlBWk+a1urzv03lyqcSTYYTa9f4q5WIjU8eGTUO5/+YaaV/Z+64fDd/4nWvmGR7xKyexj1yyN6zZ+KswlNhY0EIhwdxwA8y40F2Ww/eu5x/pREIAfX4I8B3DrsAXgLwolkUoNYPWblsx1tMYkk5Urqfay/J4/AFM1NTN+Hh4CSM8BO/Q6cki3UX4B+viif4IqP/dW/raSW5NAC35K0ioboO3pztRA1dClklSwE7AjF3EdxIEgAtq0rg+HhhuWBNY7aCpy2fI/wQHhne3veNEa/89nT9EP3gxRBNlsEp9v91grNkpxXNiWI+NFIBypUo/0AQULJEbPf2CyTuIw4dLdYJ9vsts1upp0iKlBdvfuzB+Wpca/0JeFj4012hgFoc/vCL9hJC4nqdVLq5Y+xsSNXcpXfPJ0cNrODc2aBJZhSoJ05D70+scygikI5LOMp3tc1rbzwRCUUt0tQufr3hXSDEBhr/t+hpHF9L+zlijdbtbF1YVZibCR3mrGmD/ioKcY3cVU1nRj+sbEv9RY9kLSBTVNVosaFb/pREAgkkwR19rSJ+fIFDHJ3DwGLpXS4k/9aLd+DwRnRHDvvOSembRfwQlt99rKl5eyk3sAC2L60bdcKfq/Km0zWHZhuwA6WzRHskzsa+LRlb9GIXKC0zk09nOf1QsCwDCXP8bZ8XLMK8uLsU1V0IjP2cTR+0z5J8c5VZaomLfdUcdsz04nvzYopc1dkCQBE5JBE9y/F+Zwxt6jXueFVeZLoetuM+sOH4Qd2FW3Tu6G9/VsLZ8NkVEfGfwxWmZg/7Zu2p2fdWrZ1DLmBf/w4HoaZFtg8bTM+JwBkA7CqdAijl6aOOLiJjAEHjoRJxAEZfbbJLMU4XIZw65jBXPtMWpgSNt1IkVXnh1zGbqv1MCFp+demS/K6ZOQAYh8Nx1QVhAgU6E058I45/1Zwe3cU2MD7rEA0OotM7zcLXNVIfaa2AKSYiuQvD1DNuZRAqEEamHAWH70w1UNfcmKJjvpWyrrZ5iiguUBoXFW9jdfNSIDWiJBOSuDeStKocr73OFD/BTfwUf53+5P+XUQp2AK4SEcMieW+wQpgWS2wubbE7A89uXptC9N+wzdbByjUk4INS7b5m6ST3+0Nsdk44ceHeQODZ0NulGCCU7BKOSTMBf5qNP0C76YzN8Voa5RE5iIX958wnJGf1PuIo0ZnEYNL2clPNKP2sW9j9sqLu5vyyl0LNWa2W1+WzyvbJ6x5cU8ybfMhB3h4u7OPWpPEbtNJ8FuB5NHVWlpSvgswOkhem5wfC/uu0VdXM1Iw9JjzT4FA7GtUHEc0SNKsxO5jd9Emh0cUt87uhHOICxTJspXUjKlMj1rFgzGs3BBDL/Y++jSRhj573hA62IKLh1F5gW/3oWHMzKF432l2XORhBq0o03PRKmKTMFVKBvcGXRco1o7qHW4/Nb11/MfmBdIXtN2OrRSMShwePU2FXRpwhr1hhQj1Yk50Bg1RY9L4LbGv/YkBGhCyw7GUZvgE7X/5/gK/QdVfNDj/W9q2EFS2yV3XnUgGAZRQ5pL+cblxGFc5QC6GwSlmcUbokMoTupGN6YpXRUCYbpWYJ2f04YPN39MF/YbzZnfUjK226/2dp10hax5UE0GBnFMzj8CLzDRdJrHj8lLndmMROkhNM6nI2UKvyoMo0Q04cPs4qV3Q+qDYSancbhGEf67w3lPBJbnECQAhKhoKiXylBzCk6/dQlewLKJz5uYeq2mA31ZpWahxJiDbuoKFIklTPnU2Xpx8cb2kbdGioEpVcc00QpzTgCOwzYsA1v8SFxqqtpneZ2jEiu7C4mldkWqPE61WiEmt81wKlwjuK7L9M0pBGTPN7kWQQmn7P/167B/s9Nqc865MS1dPuRkzot+WJJKQWGyVg0tEFPX4H3vVXbNEnQwO9kiqsewqNM+hE093Xh830SZZbrSVCGPTq8G91J85uK5hv6WLfMq7PMmiQGGQsqXWNitDZofGzR4m8YO9FwV5RuA++FtTOxxan0lgHDqIKZHb+OiQ9FC8683ks+Mxqi/Vqzo9V7YZ/z3D9lOQecKRgBgtEhoq7KPwwi1uN82uGuvIIcnEcLC0iQ05PAh02/CUc2bVfC53Gld16m6y41rv+bvHex31VPdbaRz/dY+V24SYRTyMsOPvf/n6QV902jlN7q+2HMSnH4CJ91SmhQfBNdXgqR0DWPStvK92iFw7tDCuWw3hLU/Cd885O9hyd9fit8PzWKW7FDopP4rVe86xdQbn9L/aeIXt/5pchPl3jEp6hdn+YANt6EEnrjnQYozI2w+fXhFdjpYJZEqgPiUUXyckm3ZQiAIzjgFsp1sRDn/d+psRSASDkKSBYN0UNRy3SJkRePbzWuZWCdO9Cr1/HgmvWNL5NLIA6yqAiuYNQPds1VcALtqFvtHXs4JR6bcV7UJ/I6exU9iSA2SlwQ5EKq4KFeaI/872k24v4qV7DU78X7TudrGh0OrWNalg0JqyT+oFiUqFAUq8FgZ7bd7sCIJl/9i10im2vCOyduQSZX8flo+r/mcdCOZZWgtWf0B61Y2UqMFbpA5oUDpo4A5R8IYM/0EF1iSGUl0M1ER4p20F5mfXYnSGxZYUjzewj9twPr68TtRvaSMhNLvKEZmufSh2dD1Q2f3SE4feAFFPrymQA==,iv:GaVCHg0VvrZSNNSt7mTJH/eWI8xR+9z2lq5kVfjJUKg=,tag:PLgIPwbq6dclSJRy34cQGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:qFCgqJy0RLG0NfhLv8JMOF6dZHHXpkeROz5j7lj+rQigjSfoduXEiEUKYWWyNxifkwBPdrBlaNS0drPaF2KaX42lF5JGtvyB52FHDImpMjLEXUMgR0Ot0XEfRIthLkzMqpQIuL/yCTp6XE5zgc/ayT7gqYDm6s5RfNryzRHUNl0FlPiQ+6WJeOHc2sWKLLDWjWc6SajHc7tkjctHvKStmI+hUfZi28sEoupf4JcsBUCvzJY8GC7VQtKCiLPi41LLz/AA3hx23N/uTz/zcvoSnxC4dhUtqIk4cN4R4+VeCK6LC4IYkq9SLgJAsD45U7p7dox3s53b4Ktp8lYQmoLg+IIH0DvREUQkUhi2gBC/35qSdhG9CSfbeBP0xJ+1vaC1hgbMHA+Bit6AKGAxeuvpdW6XIYPw72W29vn+7BdK0Nv75utaG5my9yJkhS2GTwS9zk3+k4HmNkVhuy2S0jGXilZGpmWZRdQiTUt0jsfTwoGR7i87MuUbf6EGvpxdPAvbTltRmOzc6LTaMwJlTWpcsqMfXKpeZB/RGR6e/NqnClKsAqvG+S3NO1P4MnYsur9/DaSJDiiFs17rjq6CzAddtrxQ0IvS5mP7Tuk3jPNzKd2E4UNI+I5fUKsdcphskYYFQBVKvTWztMY605ibT5I71vbWQ5UdSlSYEdMnrzUinQHmsj8Dj1Fs0SPoM2kb2XxfXGNo5ihAtB3TTSGK3fd/2gw07GM/hhBxvw==,iv:CMhEwwZezsx5KLKwri+ZO3U1N7bT9LBBC4whRnak1mM=,tag:7Yv2xp95cPXIrYHZi0EWYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8oLeBICspie76rwPZM1OnfVHC+hzNhLk51LcbFUA5VnXqrTlJxBMenq0o4aeHvrFBaGJRes3OsuB9GHHf1RecOIEBShopM+XmtDugA9XDsBLGMw/0XsbDElVoU2IndPrKfsiM7qLPW1XHVmIHpit1OB7aHhTE5GFPItOyTo2b0MbA5SWYk9BlL7Nl9SERm0duMSGCWeYGBoTpI/ig3M+v5fuE5AWEIJmHOof,iv:ErvjHYzD8zwDEQJYLHiP2MUkxvcKXacdeNiuU2dqg1I=,tag:GVlk4Hv9xUYgt+sIdf7mkQ==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3pPbUgzNFVyUW1YbnhP
            YWlTODZwQys1VWp5dDc0ejRVU3ZEc1hQRGpBCnpjSUtIeEZIcjFmeTBOUGFITmpD
            QkpQVjgxY1JGVU93ajVjNWNsenE0MWsKLS0tIDlqSzFYb0IyZEs0d2NHekxCNEpY
            b1ZpNVp1N1E2WFZsc1hMUnUrNWFkQ1kKwl58nbOZohsxOtdloB5KqshIxHb11m9/
            40hl8OaL9wTVvIwHEAEVm89xAPesJB7gv6xa/rzDJvpdPYaltp4Bjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:59:18Z"
    mac: ENC[AES256_GCM,data:WTM32CpUkA5fGr5IyEFp0IdIA1ujOeZDDXYTbkDuX4C3nNek7bN6nDfNydzEc6Ts4TKKZYn/J5ncub3iOjhFS62H0dWbYGtgPb/ebW8zX6n/MIBY6+QcmHKxAITYJENLM2IEys2m7rME6vB+3sekNP/HTcjGe6NFPs+Cw84JmYU=,iv:+vmjPWCHklQev39o4IBPoVVuh6Fk+7vM5UPTIu1ntfE=,tag:p+7FP5+eL5cicMLsDbiGrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
