apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gRzy5BY=,iv:imbPiJ/KSMpKWEZeHYk1hcukex3kWfOAiZArUk9pj3c=,tag:wuRWgZciRtDlM5UU/d8yHg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:e0xnzvzZxReFWQFOfGuURpM=,iv:MZ98HHgfcTZwa9mCnEp8+5rUv07q0K845Wquu7kfgz4=,tag:7p//9b4ReJOFdCTS2ysvyQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:XCdN2SsjCGDkX9EjUKUbUud5Ik4W6rJ0ScuQD1NMig3VGg44cE40w8HGc3s+IQEXNwsFuFIiC/GBh00HHQyK3t9ZEg==,iv:g7Qy8nrzxBVLYL3GL2jq5XJ5L614wKrkeyEjft+ltzU=,tag:+EjJp9nIoxj9rUX5LPygAg==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:iTL8XxijDr3TzrogysD9sv/v5tml+CsTiS2qCWhllS6x6wOGq+Jr+B/QnAlg/jjtBgKStyVX3W+7pr7p,iv:P9Th/3Zu2ew8hCN8A8tGDq8RrupOC6il9KRt2+wQun0=,tag:8WWpxrM7GifHgJwS6++4Xg==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:yeJw/aoMCnWZXxdkqAEzv0+5OyIGUhSW7VJwSFCM3zMLkB0sff9zhg==,iv:Pq0EBpKamWxFj5TZTvMh+71cPUs1SFqZL1ASDqjx2Jo=,tag:AU32FHyIhsHb/qvFr5DXAA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NFhzQytEODl5eHJQMVZM
            L3liQisvMG1xb3RsemNCdk41bG1BbVZhZ1ZZCnVKZEpGOCs3MmRqT0s1UlFvaFd1
            dWtIeW9IS3ZselpVc0Y1cm1MS2NQMXMKLS0tIGJMVHg2NzhlNmZ6c0ZDcjkwaE9v
            ZlJhdTRaZURBVHBkSFZFK3RFYk5YanMKYEDf43PVTnuFBUbiM3gYO85PHjVOKmrz
            VAig4YxfAt2iHaO+qyr0DXA1F9qx28DLz7xTEhh40qa4tD0Xl6tKig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T13:17:20Z"
    mac: ENC[AES256_GCM,data:j/et3SOGIi0haHU0TbtWQOFN7nI95P1sBvcPs85QgUA8OccrIvz3AJRmJHnExe5gtvHibaharmdQZGnQiFwmZiIXSg87yeYFMYGS9MY6rOF/BEsO0ulKUvdLWtppJVa82rmOkAUpOcovluq+i6JatSH/IgKL7aeIbOdtDJ+qyoo=,iv:dJdVzJ9Y67P4GV6Pv+0oghzSidSevr8G+XquotlbsNQ=,tag:Rg2C4KXDfwByctlgT+f/iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
