apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HbxLcgM=,iv:mUohKMUkifwUQM0sDIEvodCzNoZFCpShrWsmG0mNeIU=,tag:zahHs7fVR8u3flE5eju5Tw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:TfCstQI9Crs0k/EYC5WxI7o=,iv:7yNlZoeiBfsUjbf7KdsF8w4g/8Hb6g+3SrqM1L2GyhI=,tag:O/fJHqekoVzl95C/qHiZ7w==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:nIlMOY+1VcV/o7jdvm93gT/b303Vqmf8wWxP96rQUV0ioioc+T3ugggqrk3KnJ/MUMPPRk86Y+3uP8OvjIOnIqE5zg==,iv:qMMEYS2o0cv67w1nBpCZO9c3DHgcp3A/15nyLX+fV7E=,tag:b8rGT/r886CyKNLM/HMi6Q==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:nqWcJEt+kghzEUq9LGxkBo4M0Xgz/0E79YN6NOxtxTSdd/+l8sUiYJNLJ8K1L9A3cF0ag7kWAgASwSDc,iv:anLMn/sMse7zO/AFLoLQ26yEmvqWPFxHmeiViXxf0Pc=,tag:B+U8QnwPV99Y6mPyw5NsdA==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:Y8c+r9+ovzWq0P7itPsuS7E8RXSvnZf6ZKb9FAZrFUsJBiGe6O55gmgp7UTz3UESwejRr6NxMM2iRX+CemABsw==,iv:HwrLVKoS3jwY6FOZOff0qrmBOg+32IbTVNCrBIfeGuM=,tag:xAsP/AwmxlW1ALaFIAuKKQ==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:/osDsmC+gLUhmy+EQYw2lyQVetIoupqOP4ttLHAqPJI87z87zmf/mXyYlHixYV/fPkI=,iv:/fNERcYrkvbyzsef9ibSKuuT6bIKsNftWc0y6P9Q9kE=,tag:rgBwkcRs5Zpg1mAPLi/9Fg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:6OvlsMQ+MQL0XAskNpOOJUmQ4eo4ZIDDB169Wc8wLac=,iv:2QfXrrnhR1rnB++K6SBwO58n85ZATNPKvQgHlnGCVYU=,tag:YhjlyxeXXQG+ayOJDWkX+g==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:6hcuIktW/Tlc7xn7bUUJB+Kz9GSaCO3vSvY0m8B2KMiOVM3G4gIDM7Ema3EFqwUUwiw=,iv:30nCFBaCVT0YP5/8zg5mhtjE1rEx314Z7wgjnpx3bHU=,tag:WywNGoRS2fOpCHkAGX4qOw==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:AVIR5Y8rRonhlcM42YQl95OGngLO52aknm1fuA+nj/k=,iv:Ujz1gEmLFiIGecuuFhTPHSLQS3TVP8HJGq+cw0s7kaw=,tag:WPz9BhZTdIeoPLW5NN+BWg==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:dHesL28jJae7gcY7Cl0cs5aO6p9hC91KjLMFrQYp4/OWuDnU63VIXuI3qU9ekrThcFE=,iv:wPHTUfI8AYo9I4VdHEG43Oivd5ZNfdyVjR3YbuZ91Wo=,tag:8YkHopnRaQbGdV6HY5+okA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:RhT0u96dxq2lOpdIEftkRekVf0Hhwtk8kdyqAOm4xhs=,iv:Ns1n6YTYhmvmaAFS8ozDCPSpVs8y6gwoq+n65eP2TgM=,tag:5zunTwii3rYbuQwTUdLOgg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:HJkmNsxlt9MuWRRVQvEre562ayKiMGugf8jS1juMFwgHzwtJdpDVkw78g1Rhds6myuc=,iv:fmEl3f92VZnlXZNGNtVb555EANovvoC67WFGSKwNj4g=,tag:Dmi7LvgvBSEe+qysl6kxCg==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:0jnehkLliUu0jIpTgVM=,iv:lnslQED40j89EpLMvZeiqkTceL2no6eXLYxzn+j1WI8=,tag:rK7RrZ+l+nKHmzVUjHwKHA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNjA4QTB4a0FITThBM2wr
            Y1ZIbUVrcEpjbUtLSkg0bmMxNjcyNU5lTjBNCmFVbW85dWR1QmZZVmxEUmNVZFFG
            ZjBqTHdBT1luZVZwWG1XZ0lzZ3JRaGcKLS0tIHBRQWQyMkdTVlJoT0FnVzBlMjlx
            VHFMTWZ1a0x4S1ZOSUIxZFdoODFOUjgK7WYLH9gl6KmV8cyWvq1OeFo1T8Akxz/Q
            qWMFbCwLvttEBglICdHaT7BbTi9gxZPC/t8ZRMeyhao74vVMjlC/7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T04:48:59Z"
    mac: ENC[AES256_GCM,data:aTWQw5fTS7Y7C2uWAQ4MXH+LLIY+U6G8AHk/9vJGOaVa03yGuRs8xQ/fb7TO8rVfqJywU1HGFPNVQ48cHn6kYE3O6BhqTPepWryu/9vGAMZcSPv51RzNgr859zBSpNmAdKEXeW0ValOoZ8oVvov3U3eg1PMfOT8sCo82C+Sbz0U=,iv:B0bQHYXCNK6IDDJ0z36I1q/v6iZqW5J8hmEYvqi11hs=,tag:s+Gp/5ysvJG1Cxjsoyasuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:g7yh6SkdtJsOhhRXr30bSTI6rjOwMVbvmx9HzEodZGkuxRnTJGr/jA==,iv:6sV5yvKCe1pJIc/UeA8/OJzgtcqLUu8ZeiW/0A8kZA0=,tag:fMfGKspcf+YfhqCwK/goIg==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:KaGBf+PL6u//FAq8py/c3tY=,iv:xTQd7MtBX03vtYqH0GEerNxwISXA1z+zCE0Tdi+4ET4=,tag:Bz6Hy8QjnEFDxXKNtD2Faw==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:8dpALl0gVgj3enDmtE0qy38/h3Gn8F5opOwABoamfNoPJzvlbu221QIby/Ra3F+TJj12hUq4uL/FlRiNB/2kjw==,iv:kIG0zyN30rKnmWY1gPI68bNrrhCgz4qtHk9+fZ+oApE=,tag:NwTa/apA0oqWS/A+3lcWsA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNjA4QTB4a0FITThBM2wr
            Y1ZIbUVrcEpjbUtLSkg0bmMxNjcyNU5lTjBNCmFVbW85dWR1QmZZVmxEUmNVZFFG
            ZjBqTHdBT1luZVZwWG1XZ0lzZ3JRaGcKLS0tIHBRQWQyMkdTVlJoT0FnVzBlMjlx
            VHFMTWZ1a0x4S1ZOSUIxZFdoODFOUjgK7WYLH9gl6KmV8cyWvq1OeFo1T8Akxz/Q
            qWMFbCwLvttEBglICdHaT7BbTi9gxZPC/t8ZRMeyhao74vVMjlC/7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T04:48:59Z"
    mac: ENC[AES256_GCM,data:aTWQw5fTS7Y7C2uWAQ4MXH+LLIY+U6G8AHk/9vJGOaVa03yGuRs8xQ/fb7TO8rVfqJywU1HGFPNVQ48cHn6kYE3O6BhqTPepWryu/9vGAMZcSPv51RzNgr859zBSpNmAdKEXeW0ValOoZ8oVvov3U3eg1PMfOT8sCo82C+Sbz0U=,iv:B0bQHYXCNK6IDDJ0z36I1q/v6iZqW5J8hmEYvqi11hs=,tag:s+Gp/5ysvJG1Cxjsoyasuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
