apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DDAr2qg=,iv:caHixRWG4yxPsjj6EkTCR1IqcGINe2g05YQEv5eiTZ8=,tag:P6PPPiPatqv75zqfB1Ms5w==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:0mN/QW239WaL7YgOaV/VZM8=,iv:0Alc+jXnmh5JvYDccoJGUk+fTlZSjfzBPhKMwet3vu4=,tag:MjThmUOdFVUlgSS4XwScEA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:ss+1u/l5fEqVBEaEnQ57v9CIS9cZ8JRcs0k3RDILzmjpHne3OeylR9dSiFWL7+XSyy3xIwh3Zte8+3kOqd22z6JqWw==,iv:YXFf1WcLgfmTir3XJyhOMZ5gMv/fBM/mL2XwrxPAU5Q=,tag:EivM2o35H+wgZTLgA08C5g==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:7nwI+oaTcPgJX8gw7xxh2eolAUfrXRg0L0AL6OIjGHNMOlrxpqsbZD9oGJlYQgIn6jsjMjPK8TkIUOff,iv:UUMWTGvIkzNNw9A35SuqaIj4Sh0jbN/j9mUL63ixdWs=,tag:V2rv7ejUg8Dy5eH8xW8+fA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:A53EgsdYTSR2CAKspYco8mvrPW5YI7JTLD4VPbPNWfjpEfFo5Icc3A==,iv:GVsym5zW6Up23NerfKKUcsDMDEPcw8VOOBS/arps+q4=,tag:SDMoY40ku1yrlEtoMp/d0g==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:sO+3JgHOakAzyyXkV6IOxk8V0eSHq5RETg+kNWjpPkYvj1sdHGik/bJW59vrcwoMIXwnRbP6Bs6g8e2fDaR4Eg==,iv:ps55AR+lBLUC7w7rco4tLq9zMXda/WWlpklYpbj2whk=,tag:dSHd68jCSFiHtkewJm9fIQ==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:d2I622dzpQfBmX3lpIEnI6P+md7RunviJ4biqIMk6qHVi+dZPf5MTQf314dzk8YWfZ8=,iv:dtbn3I9YBhc05wnT9uLESmY1Kc85Wzwpwr/dvBIpIyc=,tag:Y7Tspp+SEopQxvw1wj+CcA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:Dae61fgUDClyRhC9INkkXS8dwmU2zCQLXz0N8HoUwbM=,iv:SbCP5roSabRPPDW0zTnVa+TbIN3bXUfOi1koxJV11pw=,tag:kg2Wn/wB5WROgmNXAcXKGQ==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:GP6YC7r2pkxg60ivb97dAC7ZxqxbyIg4/BiR8sR4+eFQrpK60L1H/uKUp0dInEcqUpo=,iv:INoQZLTAy2F73+wKQn73l/dYVUGdrFwtJgfjYcmrDdc=,tag:hncgzj0LOpB+R9Xyb4cI7w==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:syd+D6BuZnb1DtqKN9BfrhwkF3TWNpTthpPOKwhpD8I=,iv:y/+9WDQejfsVUbECotVyMo5zCu2GN2jw1KgEAMvLHjI=,tag:g7SC/4Fv+pvSE3GQkPxlfw==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:dD2kSJPlfK152hDS7GW4MahzInE48glFRTdGeRPVL5hbrall8te5MCCCVibzW6/4fyk=,iv:3yPfrHbfO4w+qMe3VhqBpxriqny2tnkIVnIu0MyXyGw=,tag:e4+QZF5wkkvddE0eLZ9thQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:sgv93Cj8OTRwdrki65x2tY8SQ7PqReyLhRxApWn31yI=,iv:mxVTqSpm04WJ9iAFjgb2YHdbSJbA2Kxkvd00+559ILQ=,tag:tTRtVm8tWpzX6KnH6DTVgw==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:MR/WnjZRxL7FLXDqCIni2jfLwJ47ylP2y95LrrJjBaU2aIFliUKpfqNdi4ZghGznYIs=,iv:qIYBjvCmj7kLgtidzghXisfW4OyM7/sVeODgYIahmOk=,tag:J7EZoj5LLBkCAJS/xIzo9g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TktJWHQ4TlpjUUpPUElN
            V2ZYbmFBSWo3cVBJMm5ITmZXU0RzS2U4ekJNCm82SmdlQ0tKZnVjQit3U2FRUncx
            cVk2SGxieEZweVU1TDBIOXllQmY4aEEKLS0tIE9WK0c1d1RxRjhUUjA5M2hJOXVJ
            VE9OMFNZYlZ0R2hLSjRvREhDMGM1RXMKM+pkfx18cs1vEi8876yZLXlzSAhlK1M2
            mOuJ14M3xjb0uh48wiIvxDoZ7F4ErVJDBE94m34EV+jxuciitdSC7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T14:55:05Z"
    mac: ENC[AES256_GCM,data:QelUkhj5hwxS7Woj9+7Y9p+YTi/+anI6h2MXDTPmvxnD82ATa8S0Jt/izN8vmusV0L5EJCvXflMHemFj/Ya85G0N9copmwjVIN1eIRIhdHwLGGPxmu4dVAxY7XyPAysrxG5v8MYtqyrhGN1B9fnQXmmwdGvcG9w7uclgkxNBBwE=,iv:oUXMstvvvq4X4Uj2ybge8qbFbDwjy7WEkFT8EwQXul4=,tag:YYEeBjqoZ2iEgbuzJlIb2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
