apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2HmJXwI=,iv:n8y+xuGgS1dBSdzzuYFqiyBhEX0jKaYxSDLxedA6W8g=,tag:aqbpYG7tempTKMllk7q1YA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:h5YMU1UXoECDGb1bl3UJmcY=,iv:Uu9ncMZB5KVXJOBAyi+6+kesC3Tv1eVOa0PdxqX5LYg=,tag:kX2Va/7tHnaceP2xUak0oA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:1sJY9tAcU87YAn8ojDjuSTriS3Lq8BHK99gbp3KYo1vgB0iCmkVQCuIPfI/V09+A+dtN45gChQMOhND1PJHBbzHdYQ==,iv:nPU9EjNMZ82yYfuU5o1yW3RQpy5zUK1cCYkaaR2hziY=,tag:VnT1XVf/sJqw9yCPlJTjzQ==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:Y/Hpe9yvnBNgWAtXziOx7/VcX5XVK7o8Hi0XCNb/3u6keyHrRxIffT0cLMixzRUZrW7NoyZ7dmNdvcG9,iv:h5eSfL9+UyPSmkyYkCEBxrC8FQP0wCaAN/FalfK7l+U=,tag:Igim8DphRCRwABsOxFH8ig==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:FtM9QHfmEDWrxBKIGLTeBwOzMeGcVx1vh4Z7KZyDYFru+hxTtDFN8AIRp3MHBfCVO9zmW7AQtsm8oekuDR20hg==,iv:js/vochR/R3mRhr3r5Ct//aOcZLfwE+BdB3whQxIi7s=,tag:sC0mExSGyxi7eux20BlJXQ==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:EKR8STaqGrCfTtUxzxIu3S3mxbByBptn5ofo4HFRxh0zT09bLhHD2OtgRi/uYg4S,iv:jalJs7vEKfm6oZ01I6CyvnEJxlwCpp85wi5Tcr2iXx4=,tag:3fayNSwprfAVjpOz2DdMBg==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:Hgc54UyY,iv:GA1LJyDrRVXSY4pIjteuy+zwsXB4EnGkgMEIYtOouxI=,tag:EvElFwc3SaKuJBKzuwgf1Q==,type:str]
    COROOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:Jpmwb7UX,iv:InN8TXeS7PggakHaX+FeB+Bmj0mRB9meM/GCfQKYssY=,tag:wn2AINMV38K4XLl2J165pw==,type:str]
    NETBOX_ADMIN_PASSWORD: ENC[AES256_GCM,data:lYQ45iZV,iv:qdlZKNsU57Wn29YKcXwz/EuIYbGWqt77SMgBlXWLnQY=,tag:7rDzFAwey1+5uj1HKc76AA==,type:str]
    NETBOX_PG_PASSWORD: ENC[AES256_GCM,data:ogC1Ssm7ZpLz5nibdNBFCB+Bfr+YUCFxJbAse+rPBwA=,iv:vUJpogbbGBfjEjKieVaPq588/X2Ec43J/pUrTqGzozQ=,tag:bqdWT7LYM5qbVaMDQk1mbg==,type:str]
    NETBOX_API_TOKEN: ENC[AES256_GCM,data:ax72+AQhjAREqJm6f45MXjk3S2CffWvIe6d5t8aaveMtKN9rMVwCEQ==,iv:UF5ebo38FjobqXMQMsi3IM/W6kagogHWV0hak6Hq17o=,tag:8NhCMb+hnyjeDusAW3j0iA==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:jOKubg3OjCQnsKHstAPc/eMd0OjCisudm+B1Igs2gwA=,iv:7SWa/PfR78RMx8hlB5tBAbXdZb8AkMh89vmiUOg3amQ=,tag:kgwyEm4w7vZhDmfEC8PkYA==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:2VRDUvbT1DF1Mr+LExY=,iv:/d7lfOXEpOPnktCCPaCOb/6+NDgrEmgKKRJQmM4IAqU=,tag:gAOZWlO5JK5ac1V2BME5xw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:lRHo+Nie,iv:L8CzyRC0tOuwi50TTDWlqLxQkP7FBIkgnQTYtZULzrA=,tag:aEFHl5FYfQgCyIq4nGEp8Q==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:Rvc8SyC9g/gIuDdJv0vJZiSHBA+7f3zrPXISq5rPTTWg+1QnZ1S1UCP9VsbVEqxonVl3Diy/euN6HhTe11qcRAl8+tNgsGIwLGNci5kwBgLkr+S5A/zKxqJaKoL01vrwveBBwBAxyBd65nHaLL5hvLHS6mHS5R5ZaZm0WF3sC4qasTiCfPEYIH5ZV1jyg8/raLq8OAEJ8/eNFEwngj3vywd7V1ODgvNnGWI1sA6jTdbcFmH9KIUO,iv:LMzJtgS7hzQbRIA7UQK9vUp40FCCxzgwcm7nTtmIO1E=,tag:J3J9m/Uzg3OSMpUKmEhR9A==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:YCppLWdhMf1G,iv:/3skC0EQK+d/vZFcu2fAiIoF+redXoU47zwMxgZF4uw=,tag:2ZbCZc35oWNjLMLBNP5wuQ==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:6RrwsFF53oDw05mkDoakzn5XeGSNX7pEc4sj0fJjZNVadt15g0Y6zb0PFIdC0w==,iv:ntoDGBK2B/2pnTM429BJiKSDhra1BOx71pNH6IcSlz4=,tag:tb1VIZrx8NwpSJpriqpTEA==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:4g8t9Tc+Bwvud98JNLE=,iv:pd9c8RUypnZRIsaYgqt9k/uG5AlNFWf6ttgqqLUnSXs=,tag:lg64r8ceN8WoSygwAemKCw==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:QiOKnxwvECodECh8CV2nkwuEQ41fasPxrRfBX20IgVbPaJPkTLGrUA==,iv:idJchlNDSBD9ovnSR+vW4OhUZzS4cCTvLrslromWoQs=,tag:qw91hoijUmP3l1HjqRCqHg==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:+0I3+K4bpqC0qdpzM/zk9ZM=,iv:O2G4AeNaFz5cMxijOGtCRD/pLaHlKzrtplLErx53Dlc=,tag:uOCJqb0IljKRb+Rht9S+GA==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:cfWSZMHZ6hxHZn4Omw1MC721BegXstfqEBVPJflWaeS/EGxtOKEKWRFGjye0tM0n63MT0yk9QWBUQWZDjeH6MQ==,iv:TcgEWziX6lLfELAIig+ZVaxpM6UYcFbV8Q1h/EGx4zI=,tag:LDHuWCU5MaTjoHDSnTBCtg==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:CreY2DniB3o=,iv:xsVd/DrodOwxQs8z6cVSdXn5WIW9KAncy0l4Irqn5xA=,tag:vMXyGT/wcK304EIcBcXYHg==,type:str]
    password: ENC[AES256_GCM,data:oiZSxlxNZpYssqf7Gs+fPNRoCTiqN2RczgiPnIy8DvjzbZNOhaL5tJqx9hhoAVNsPgtBk9ThP8aTsfrdi2/s/w==,iv:kkUnBe9tx4azuJaOn5eDieehQ2njKOI4/l+Y4zy+GLw=,tag:8glttOzs+3MgZ5w43VfHyQ==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:sOecoqdTeZNAINS5cVyadLQ/oogXZCZkXEvyPlTGfZ+3+DK8dpb9TYiNcJPP7xUkrDv1qE3E5leCd1UjONfgXYDdy650QwmkLaE4wT4SXBhzPgxt7NRnOieAdUbM5owJnZ4Q3/oAkpjg62WtELPEDKqrjs6Bpm+GBOJTi5+XLyIRdTQXZXKLBkcL8jYXkSFNY9CmGLnRs+jAc0tkk1eYfrNZP4kF+Lzs2Dj08OiY0Q0mhsTa0DO2bJ0Bd312TElTPE7lWn9V63CubH4pqXYXcK8pbqG8O0LFlL72RyBT4UwzLunZjQONfyhEiENLKUQ=,iv:VqdoAkekI3m0730Q8ku0Tauf7soZajEP2ZS5FGMmL2M=,tag:8Y5NICglB3bBMDB5CAb6rg==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:h7CVXV8nsW8M35v305+DgLHL42rzUDDinGqXDUghyTVSY/+WlxhTjxeJyF8ewpEQoWJIyXMRDTDoFnT4xSndwQ==,iv:j/fTOQ2QHnk3dOGjSSW5mFEdRr6Usl/Xs9TWpm8XTi4=,tag:o0wsjv8Stsfj5qN7APZIGg==,type:str]
    PG_USER: ENC[AES256_GCM,data:f93ikw==,iv:gAdG4vG/DTndAK8RNPWjUnw35Cs59aFAO9SFohSgPpo=,tag:KBkrh9Pu1asR+LXgiPFf0w==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:KIfq+6Ka3dfpAeAJ8WxEESzUc/uU5Ar9lPlt0doImgMffEvj2EHedS7GYMzF0JfelVcr8Q6uUBBzQFmQDFe8TaZv,iv:3W2nraYUWPYHh8RA95MMz7Rx5PCjur2vukcdE7rAkzw=,tag:Si6BBBeUbd9npjHMHr21hg==,type:str]
    PTE_RSS: ENC[AES256_GCM,data:6IR30qkaZJsiQE3SdP5BMNNuCMCYKEQG8VGLmsb1WDrznnMm33CASQInmj8nxacrBK82UbRCnM7A9kyfGb8fhmBHY3yXWdXNiQ==,iv:Z8Hd7ouo8pDMHKVJfA+dxwWz7IYHF72ucNDPqAKb9AI=,tag:t5c3Sg4shB0rvqTWYI+a/A==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:MSGkJSx3eF+sIojfJsdGtG1m3GWfIhzxp+b+QQ5DS5FVh0CHAZfo7iKPAhvtBxzPXXeiHk03Pjhry7Tfwc0ZJtjNvdX/Uikck4t0yMkN+r7BPO6sNBRfOCnY/rRS8qNY8jZyxtvHwwtPZhuTmdIOJUqslKTBtI2GtHy6lsw=,iv:2pF1L4CCTVVldQ7FwMtOmtWM9IuW+Y4OFHNsiR00aeM=,tag:Nx/uU4vjPxIdfED4C1nq5A==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:X1pV4CetrINsqcHYdDAwCPkPwAdIpJhB71zoVgyqjF19cSvqfbaWAfyoysgN3NteozhgZidJGaRsawDucCSxsGHcSBwvPpwhVpNhL0+xP0+UpihzNcuVSRKAavES4pQCPnPPj6LG1gx+/gPmXYvxg6Bi9DIeZgxRIHogWooXxD4iNgHthvK0c8krWWbpuTz/7m2/C9u2pXOMw55ODPE/jEN+zMev08bGc1rIk9py8CERzibqTEUOIX87+ZHrgOsUi38ki9LeyptyT0bbUl4RPdHUeR9OE9F5FXkePFBI6xN5ZT/1om5SRc0Y1Z65CQykWvyi7rtZO2JbfXGc,iv:uBZjMWbEl5gxBDaRnO31i6y6d0lPt4sswrkPnZFLrRY=,tag:aWXTschwD7vI9UrltRES3A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jIISFKpBs+LFwoEItZLhcAkh+t+GB8/HsUWKDqR424el6Ywb5LdYeWT1OezBJbj4Vh4V5ZVDIM4j4RAdLXDgclOcOAHH3QkAZc+JLpLX5Lki2g/JzZpG6drgzGJIpONOB23PYxB1TGPoHocsf2zzxs334c7Gc1h4d+aYVIsKBS2vFYWxnlKsHnPE0s3nI4qjmW6CDlv2Vt13fLcMgR3jlcIf1Q6Dn3p065ipGk8WbE7GSIK04eKYoAK7GnZhcEX5J2fikmF3qqyQ21tc1STLWi5Eyu9YtPbaaj+lxBoKla9efsXWsbkQn7UjmRAs7LhC0IIQeRw1o4erlD+jhxjB2lTemoIv9cGz3iY4Ypf0uDmw7Pq1jbXz8QDHrQucezdVLnKSNv7LdcdjQiB3iU9Q5Rs91Hrh3iTi+3JDwD2/rr8Kgshe/LadWleRll7NgmSJiUbCdABlXi5uVBEFZE/rSddyxDPQJsnVvZjqxcNDOk755pztBsqV4uyxd7vigITfdXGjgZh+cN8zOvBolIascd9qHxBimbbNUmcEW6BZweNb+8LEc8rFNvFBpcz/2P1d0f9t4JAGQDrXHGIKaAHAsjWj2nvuhZ/yhVnFC2u7I+qCXQl9lzdRA7gWJTeYurWG3rDVXUU0bHda03d8ZdiKCB0DTT+hafQCLOIKH6NaT8u0QthrgYUaKITttmshYaG58qQAEeOqERiTaiIxRHA9FhtlhkI/NxdNNHSfUMDNskK1VgGLPbS0u34luRAJCDjnbxq13R0wTMsuihA5WTaAKotbpYfLqqMhkSe+h5/dYCUuYQV/vNFhdWpeGiiKSCnoEEM8yVmYcdvYKKfJdT+tZbHo88n5wT1TAgW1LB0A1obApbxuwa1iMzuGsMPypTqzpgE+J7UUZmlsC1u0u4rKFB1JCCNM4G6hWFaQRqSvtWO91+SrCsv+yInz0peKWjn0pZWeHTdoZpfBZA3br39MWu1uR8CtJ/NeuAG+mHJNKmuJs/v1/UPzFiuHrTvOBauJcl1trAAcA6w/Af2uOPhO1Pr3XlNJfLgUBQ7jp9tLw4TTPgxQUqrmryodUuktNNM4IrhpRDrQFv4Ah4Zoihd27mPwwiTvcFxen4Cs8yjg8bf9K2XQLgdTMl5eGyJGsBaoAcZjXtHdfzoq5D91suOmIDkGPyA+zrm6RVonX6glA0gyhqmJgQSrph/s1WiYQlcyskgi0UggalEouc9TdNzXO4CA7xxVh9UPvFqEsWmRZn9NLYQv5fSVw6u+H+A7Qqfp7yQvqlMUovMuzZrkhdJovUk2E6s211IZCMDop6tTLVC+ltQYRzTvckpLQvak/v+4LG5+SIPQK0O08ayMKsL0KZDAAPpFh96Y0pdgQV7aNh3/aaQCdd3CUvp7Un+foEx8pfPLOSyiDvZxgcDnSe8TVQb/YBAw8ASOqo603r+uqH4LH2VRItI89KHatdwt4WS8dCVyBtyM6Y68Mw76lwoyiDum8jyNQZe7CziOSBy28PO3mDkn5k60RM4+XuoMEkpR/R50k8IwcCK33YAfSplM9y77tC28b5n/kkZ2T4WQHLhCEgM5qmDFYGxiho9rmnX3MBv6Cni/5sAT5v1W3ugDaP/JbMGofZPEI2HEReNb35+dyBt4Tu1k4creNO1DKHWXa0fyDBYwisR/Zx+CqMVRnK08oRkSIkOA0MPhUUeRWIwFuesulDAQ+jN+CTXKzIia6/al4643PlCzupE3AsALFf7XWtXa99JLKGP7yBXo2FgRnzlx4A6HfTKlj9isazJUDlkH3nj5SftRl8xFeE7l+nnujz07x+MghhugdIWN83hAecghVtdWlQdD994LAc1D8BOuJndyp0120ZLCJDsc3poyzGWF6VwGd8Ou/VguqtrjrDA/6Pudq3npyR6G2M1A5+ML6mZ7UUcttl98nf1s+KOGbp8sE/3NhceafS+6kvJZNn4QZCy3JknNY5+60B0yWe3/hv3P3IogVjrzJb5JpJzvl10h4YdirZNCVE6jR7fOpF8T4o7yaSKq/2/9mdXkBsohgvS6cdPPk9Is4ANg2PRmbyxR5AnV9rGOgfchq1TdXUasOPA3mVo/AQLbSzD+b5oJGx0i0+tQTDzp1ygY6X76USLPqIqacnNUctnlu7blrsthdJn+79TylleUuPMymOZ0rV+P2ULzx4jhuo+13fCqf91j10/2bwCOTRTUHeU2p8nVl7QTS+kTDV7svtWK7FAMmQPinsn0/+PBvkmAIney4lLS9dhvWXbDFxbocMx3aRixw1fjjJM3tBM/Dr3XC5gZnjHMEmlXEc70fkuhPsgS8hl+M1GDZSiDVodGeF8n45cB27NRmK0PpOuASMn9NRD5mLxgOxEkQQqm6H/YmlBIOkUaymGtDicYxltlnt63f05K0mZoEr5jEXLNGF+DZgDnFVul1i3IbR6/4GkAgpR4IHcLvaPKAChojLVH+yG5EG/mqxtFGDfqxWwhN/ng6dXeOLHAGHb3c0YIG1gGpZI7W2/fhFgPwt7V1FA6crxhD+CQ7vZRrlz/oA46q0vPEVaFg+zCaGruyect7WcNzWZBEYPLmEQoV1FwT/5iLSASmlBaWqnx4vhc6w2YCX2DpYvwkLXRZEhMGxu9Ep6NZE553aZkDXfRhIx+TknJ3ikYF5RGIYwASIdemCnx4NZLMtR2YD12kBNV1sqiHpIX099tl0+iPb4fgxxblmBLd8Ewxk7bGvDQqxHsqGZCwTmrWXMREFdyAOFBpFwA2AjqRZgjOv9xOiZVwEJ8BcZHMrf3PG8CvJaXjaNRSfes6I3NZm/+YlYShl44leRjFcp2GeN0BwfCjvsjtVjqwpWTM+NZIQkQHTUQpsUceR7KcgKJLIqKzODpSOBYev7d7+T2f4bXJu79S2R0ysec3ffeHfkRhnuN/6eZEiELDIHIDM5H2yNjqtn9FECsE7JEInVD19gTZikzQi4ECuBuzJujKMBYk36tMsNx+mnATunYt4pQG3EATpIo+pGYeKQfSA8D+Sk9+ndLXZMbCzGGIOxORaXN7oJwfUye2iTQXIQE8661C+XRSOUJBuTwbPoNCxbE6vMiJ88geIsYKZU5WEv2+18wrtIsQB2H37KM1iX/iQSmZ+fbVKsJ/M6gXLA8J7OQB/fKvxx0NiNhvdWhieQCC5/7zoPCrs0POUChmANz1w/3HbbqHEsuVAlBwCxNN4xV5EyyUSTncf+rCRkasj1FfBa7Fw0NQhJI99b0t5YTF9xO8qXmOssQJ398ux6mMlL9DZVVG+TF0VEqPlYXtyxb3yBbY17QBtYprPrSAVkwqnJcvCF6J84ym69jcbODWUptZa0gzzygNVL5+AZYK+/N1pg141FF7Q/3EqpetZIapp4dJcesCXGAypQ6uGa9L/sq29x7LYGTzguk7De/weojUsNKwhbdo6ObyHRN7ZXAHAOZhLCmFkaTgLZ2Dw==,iv:0wA4XESrKFypQtpShhnGlk2bQCYuIhE9mCPIfP4F+GI=,tag:2gC2RqAlR16aH68tnHT4SQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Uwc2LL+KXzF+cxjmuj4J5jfDzo+OqOxgsmpeC5TwxkqBbanXlNSa5pQlNRXR2Fc8eed8MPBOjiBSAnsCVkFRDO85MOi/bRWuuSBKZaSboHUOAs/eqEBYhExF+wCTOpz6xcV45nWu0pB07NJOItP0dte/SmQ1a7C36atc7co8TzQdFaa/1rUWt/c8fuK2wR4alP+/g22x/YVCaf0xJW8FUkGXXJewK+9SUpZGZwQUZGRKD5sffItsAOAtKZBLPhhjqQjvwJd/ETqEqCklOpgzZsdG98yNOvi3uQvXsezl4fmQl34LqwYnvk5RivbLcW/x6eJQSaisQvIfYTEwikhckuKxGDH9qrNhQMXCUCmobepYb+6pumwi0tRRr/snzQftffipZeV39wpLQetxCkqsQebSV3z/J9zPB6VTY5YMOizAK/79Y9sXMId1Mm91sox7x5j1Bpi6AXdqQ3ySVTTF8Ce+T9+vrx6FkSCxbL74PJFbT0MriqDctVwPVJDifnTHG5/EyNoP9bzvy4eLT9DlngwJ+sQdtQwEhdJ3m7XStC651XDzD4FdFKVsg6IA5SRs8BlrSqIdH825Fm1TPCNusThJG9/1JtgV+l4o4fGzyrnNvAl/nQbKIBIrtepP9hrsxw9lfQ2cDjPKB5SO3e7iHJJWgIzDyz2edi1HW4IxjStwmIYJayGkELDCtU5J19DPZt8WsPqFdRThP4EU9D+wEtWlsEr5VSVxQg==,iv:u9nWOBWd3bXx5lcdbVHfAe4YJ5LZMku1VM0SWFc9xHk=,tag:famdwH0sVsetvZiyq3GxTw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Dt+5dpGLyavnPpkWAIMhDYSwrYQsdLN1rNVTTC7184xnTa6tbfGiFxX2tIVhxPjDTTAexzxoImmbx3i4upt2s69ruj9XtDnWEVRFw5NveT6NSuBuJbgaBCXA6NOARkrYoAuw5lqYARxJpppEvMwmpsFZqwe/WT3bbJMJVSOizMG3QqKPCsUt/E4eBscvPQNhbrMOOpbbXmODRHgoLm+BtM7RD5XXa8ivBT3v,iv:Ev633VXzgNwuBqWtov/b1mexWTrcO0/LArNqY/F3AaY=,tag:qwpZqHbjBOohX3K0Lol5uA==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUV0hhb2R2SmR2cFBaTjdN
            czVKK3NMbDUxVWQ5Zy90T0N3OGRPTTM5bVRBCmFqRENZdjRnbzlMOThrVUxMYnVM
            M1VOUGhFazhEdmtjdkMzSVl5cnpsVEkKLS0tIHRCNUlTSGdBSklrTE03ekhNZkdN
            bUJtYXBmREFreHl2Z3h2M3phZUhwbHMKzobVlQ4yEWjFrdwqTn+llUXdpsk8HeMr
            rOvnUjB0/DNMoW3Uksy5CHWWZTJGyW6USquOyOtRcucyxIxcO0oXnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T16:24:36Z"
    mac: ENC[AES256_GCM,data:i7xQvdIHh3xcW/wlkm9ce3d6ucQZSdaoH1W3z0Wg9/oj0WPs9my9SyYiOM5Z9MjosqZ9S1JMrreT+6Gaf/mfL45rI+bIRRa/1O4SrEyFIJVUUOdSOEn+We0K9w+KNbpL7PKnwsFwp405ziUjbjd6wbqDMFo9d71Vfb+97cRmSig=,iv:PQkplSIcNft5D0CqTXCpIqGoJjmxzsetv9NX5zcJY84=,tag:SwAD4GlvevBPI4Qd7DCfEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
