apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vzF5yfs=,iv:xwA0meBZFs7Gukkqe6CVIGmNGEdivc7zPqevfKjaMIk=,tag:QAdNu4Ym9OSuLiVW6gZjsg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:3TKoTJWFl4lmP8Cb9nYCIf8=,iv:IRhhA/XJ+jjPyNRBhhAkgndO+e376Botr/hyyDGNS+s=,tag:/1rMRRm7biF/flar1ZHd8w==,type:str]
    NASTY_API_KEY: ENC[AES256_GCM,data:R8QXRBZ/D5QYEN5WQvwbkIuMuBdOBvZHmPsBG2EpqELu3vXD+DnUYmkHdg==,iv:SZgJPp9nsMv7zp5vMPjCDs33+lwyiRgt77QXI40d8zY=,tag:7KMmA6jbWLwC+M55V4Ua0g==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:4YmwC2UMFkE320Gd8pqcj1xyzGAdpIvMMAYRL/H4SWy3y07pswhYyA4aGX1Vb3HvmjZN1d4ARPHaTp1a,iv:MwJ9sL0q2U/Y3uMDJtWVSqvGGrLxdphxBG7dI9fA0ck=,tag:M62gndM4G4STWkrhTFFWxg==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:h21g9R158agsZW9h8sectTa8wPaMbsuVCQZKjnd6Iop8IfLVQR0n8gbTQHE8EnYcIAcmV87Wk7diI1S/1nHqdg==,iv:fEphR57aDfzeBPTrKMTXDErCoMuW4xcrsxabQDgSqvg=,tag:Zjm6kBL6POvP0G4g99kdzg==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:FAJk/fAPeP+L9VlRhhv+Xcpn36YvNCu3rq4ex+cboDHQVh4zsueGCE6d7T/RGtz1,iv:tnddBWtEE+K29QxfY1AzyTfu59UUXuFkwfAVZB8C0Nc=,tag:RdyZLt8+J+Mk1J+VPQG2xA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:G/KLl7YM,iv:wGOecup3Mg+i+nTBOHEvBE+SYBNP1X8AmeCQlxmYnhs=,tag:cbno7Xn4FaS0AhkdSR4Idw==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:dIhmSG/6,iv:sseYsMHuM8fqpi3nosk4NPyjPPxHH4Uk3RtgJFvkhdc=,tag:3FtnJWj0WT7HkjxfCl4C2Q==,type:str]
    COROOT_ADMIN_PASSWORD: ENC[AES256_GCM,data:mHscLfsR,iv:A8pstOTncrMasxFlGKaTlLgUbYrpxxZycUVHceKsYOc=,tag:m8Cv34RhT8eTLyZUVdP4Vw==,type:str]
    NETBOX_ADMIN_PASSWORD: ENC[AES256_GCM,data:Htv/UmMm,iv:N8fTXaKkx0004jdJXHF4+p2ERZ9ta+DVNy02pkWPNYI=,tag:pIyGILRinNNTJMiEM7oH+w==,type:str]
    NETBOX_PG_PASSWORD: ENC[AES256_GCM,data:PI+6a5XchIcUxqW74JylUNw3LeP4DW0Pec1WUXnaKwo=,iv:fnZXfwQRhY02wFh8B8/8xYd1RqufT4boBBxtzcySfK0=,tag:kzu0jewGtZqjGBv2mdXcnQ==,type:str]
    NETBOX_API_TOKEN: ENC[AES256_GCM,data:WgS6jn5WY/GzP15PO1ncc6NQJLs95BjFbARIQsfufhNG8s+asKAJlw==,iv:B2aeIMJAs2Nz+Io1nbLW6lDS3cf2Xt//y6Dgow2aock=,tag:OzIZJ//NUruB8rM/lQi2FQ==,type:str]
    DRAGONFLY_PASSWORD: ENC[AES256_GCM,data:m34L1j6/p7sQGyBLFcfJKisx2BuJ8bs/IT87jP7a/dU=,iv:766OHev9ygIBnZLuNIu3YG5NPuUIroNKwVCM/PCHuGU=,tag:6wnHfg2sdrjQv4sjZHycLw==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:C1h/1d/QSBsUFzSlbDM=,iv:csqY0BeLoKKsck2SeOKdSpJBKe6g+WaXphJgGRDdYSk=,tag:R5hCH8T7pgSqdkqJHHMKEA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:J6jEliS6,iv:T/A9Ctfvaxsu6u9buNUN4W9YeMDdPU4+0nfYfyabaE0=,tag:LjZdczCeal4M9IhChm61mA==,type:str]
    OMADA_PASSWORD: ENC[AES256_GCM,data:Am/J45ZtqdTk,iv:0iblhyALhNF/AtEo9RlEOXdvVOkFbTaz+dEhpwx+MSA=,tag:QrM+vNv4YZN0KzoROmWjng==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:S7AOEP0WCtcFXbhLYhlXbmPDkB/N/Vjb/iOOrzGh+Gk5UPDUgrWLBPJc+ibjfoBX0u9U2DAmnIfVjBVfKOwv7jbpjB/edtcE0iE0L4i77tebdBYu0j3I3gGNkyVX/1yfZ0TLH1daFZc3YY+HdsxmVg8cFuUTtzYJ/7ZoyTW2kbhJ30U+ihgNyyZiX1UFR9TPHecahu6967irrL7swNaGTwGXjq4qIYtqR5KAEiKpO5c/iAIdBwOh,iv:2TN/CxnSvaY9nkgmALmxQiRxdeDukvD0PImfsAiSNGE=,tag:Zt1jBPZKham8K1jwP3vLMw==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:qjlR0lKJKt8X,iv:Aa/X/PcZI0g9sFsff7zw5CL03VY1Mjzzd7vOwQb30Iw=,tag:9C9U66Mxmu9whhi4g3kBKQ==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:KcNuAtSGm62+byRSbbVx1mA46BkxA/6S4FSY9xxLU2sH45RIOV1Qrk9a6R/1bQ==,iv:cqLOBoN3aepi63XkPGiRLPkmQN+ajHoR/fPzQgj1RuI=,tag:K9Swr67UwS2C8kq3pSSCEQ==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:P8vgXvHftoOmMwhrvOs=,iv:hOOHVA5M235qPEq4W3oPuCNIvT3tVe3eU18mvrV1WsA=,tag:oK2M+1RgWCxCntODPAw5SA==,type:str]
    HUGGINGFACE: ENC[AES256_GCM,data:v11OdvKwlXMUlG2L3NjXL1znA/XQpI3DobdHy1UZKeu9yE6t8Q==,iv:INPxeGcaHMqOWMckRBzmS7C7bmgbaeZs6PFIe1KYNNg=,tag:tRg7k60nod8TBwZ+e6IF/w==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:j0Z+Rs3/+M2rFia0EEd1NY/l4YIw70qd9VskNHAN6cMINgS5DvZ0ythr7JPdscUL1pdowks=,iv:kFFCIXhlSW4K7Sc7WEMScsEPOV95ORUHL/7OvuAexp4=,tag:mnRwBf+T/PdFok8BsTgTsQ==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:KGiBRhKl+YsNtHDm+sBRJj4=,iv:uIwulSUxPqYl4VlDxhiJUM9i0h5rc8tvbobqcCy8eAw=,tag:1t864/713K5pweak9lJWnQ==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:U7TBp1BowNLUo01/c1acLzzji3adSGdNvweUXl9dUrwTxtH8wsanwyE2uoW+oFOHepC3DCMwFWM9r2jxRIDU6Q==,iv:koRLJaIF9jIer6b6kELhobFiVaetyYX5W3Iho8GwPhE=,tag:Or4Ki1/FdAOte2NG+r4WfA==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:fd9/pnib+Fg=,iv:wP4E0SpllJHqcqdXozzstGzp6u1Jsgj3NjrnYCVYBgA=,tag:nS4fXwZV8ydbrM0IAf2cTA==,type:str]
    password: ENC[AES256_GCM,data:glMly9imneILKFha+SrRF+M8ZC+xyimPNycQV87Vgwo6xxQt1saU/G5t+wjqEi1a3q9N3dawtC2XaTG5VjT7tw==,iv:6eOREGVtZOJ5DFQp0K5HYcC0pCXSNZdqU+IRmFM92dg=,tag:x3fp1rXdA7oG2R/n46El7A==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:P49Fw9hNJNFmT2zklWY75vNfIDtYCvQvmGxTRtM0m9LeQaDzO1YvFByttu10ghLe1JdHpIFBh3RGT6bNQ61ZUl9wNCdCz3HncYEkOewDuMXDeJN5+pL9hlpBp2p1xVXg0mbbw8XTCAF4l3/uKmSlOFLpu5hW8nLIEEG3wDBUY1pory9Rbp2a6e/IODpNRa1cFvnxKp6ZoPlEZEnchXqfYFii0kMgOI9py4N5ftXczHouGUAl8stEa2YGJxCTfS9zUC2csqM5XztjPiwMgwbC1kr/ThYhgQsQtn2JgLXpOF5TEA61lR8YLmU0e/SnmUA=,iv:vLYS4xB9EGm8q7vxLur2A3l24pnVDl3TwzKog+7aem0=,tag:+LrCTHTKP9F6+BpGSg7dFw==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:HLA+jS9r4RHUF3XT2NxbAeJqCp9Jr/Vb+kEcq/Bdj9ovVpS4VoqxydZLBDgKCjLYerEos5BbzSg0gnemuEf+Vw==,iv:emvlqTQNnQ+AjyLpnuj6VPiNXohYQfpFRkidpj1dt70=,tag:bvoMu1olsMEecxOEaB0vjA==,type:str]
    PG_USER: ENC[AES256_GCM,data:jVPF3Q==,iv:NrQ6BI5MsVjiztnBjL9uQ/4IfW6s/oslmL2kMsg2uqs=,tag:Bjqn+jpJBT7R3/LSkUqKjw==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:aBI3DAH1cogqxKqd9XrTiUjyEkVJ7hpA1GUmyMNNKZk5u404fg+HGvqx1M361mU3TffPun1IXZUapJDMrIFBKCWU,iv:zKXtA42Tfg95UPeiH24JCijyircI3qVYKcrHd0DWwbU=,tag:Qr+4JDwD1mQdkEc0aWJJ4w==,type:str]
    PTE_RSS: ENC[AES256_GCM,data:F7ZXnJXKNQbwxeuzqQwcM58PDxXEUhmubWkC3TV791UZLipJsk3oDbOCHVibFyOlfn6FqTNIYFQSM/Cr9LYR/70fyoiJ/66QMw==,iv:DbB9p+U2dQf+sI5pqDBMDqPsdVT7mbPbdyXYsqpW+Y8=,tag:ifpUj3yrHtnQlgH1rU/sig==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:pL+YvtEgjtQLuLJD7+w3QbNCjsSB2COR8uKDumqk+c/uGOmPA+8CNt1mLoANfo1t3LJeX/4/FDDVQ6ofhkuS+WFgiaWVxhtNHGNNKOB1je24+DoN0a36SZjUxaylaUSjj75WoKsKDADHSen8J8LIrBlVVAO/EIdiFdSZJlo=,iv:4GAuNw7eyKYcDcM5Wp5h8jY0fh4ieDBoL8DtCr+DPqY=,tag:a8CLUfXHub7jkmSh3uliDw==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:mtxy4dM2tikBJCphC9aFEB/tMA0e1mY5P+lCP7xu2WNxx+04+wAfJn2uOwDczCsVvxLrPNmyvXMDkK6o6JN4RCIO2gKGenaJKdvtKA0t806AHZonwzSr0t7C/VhYMVuf3WDq0N7tgSDb48Qrjcpqi0wR62jo5zspVeLHZaXgehXdqIwSsJF3pGV02rXOrRM+se7QvpIOH0uFezvDGKDqdc5i3XrEQmcTV/22baAQmQuFWJJ299v0dHdJFpXcQCm1h0PaZCteWfJw6y4rENC68HpN7nF2w4Aofgg+/hLa0PXSRWY2yHn5OKZb8HAhjPetiyjkn+9mIj+8RWI0,iv:rq0owtLP2j7MCqNKY/V4M6snCouVXE17O/pyNx9R5tc=,tag:g2jdQfUvw/dB1A35kVIrmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:C4e3QL/UkvYpaxpqOp3HW0JvRwbn6BweO3WRNO5NdXwjWDT7AchbP7Pw7hz9eKeMfvxInJLvQnsnGspLTcMzihry7K296UNiJIvS47ozaJJ06Y7yIg9lnvJD6v8UdpY1JzR4P3Y/b/6ssjN7senLe+91eF67mrq+KyFog/NP3JSKdjoxwy0EeQxeSZKBk22ytTKTPEa1gBwNW989sC6Cj2gIBT5tFajzaXeZiswsHnflfQ5mQCzbOGviuT2VwxBNDYqMEnoRn7im6wjaT8ub8MoSEAjpGTIw1kJkqUEy3PpocT/skOKL5rPb2suE5Yeea6b3VENLOC17w2fg5wB2PzzAJOus+n6uzx5gxAtNbjZtmQYJ+7X6TOBf7BrBPzXWDDnZyCy5MniNRPbgvFri83Jlq1vaDu8Duj6nyVmLm3XNnN0WWplLGi0vs0OT3he091KYaSkoy4C7CjI0LD+PT8X4lGJvmoKM87ZVDudf0pb8PpOPxu9+GHEqEAykNnHZ83plPJZHLPvoljHujUhuN/uE0KcErdc0vIxnaW66UJr4lpdvxE8ukiD5x0ZpI7MZgl0gO0+IhvxI8vco2NtlkGBG6fY41v29baxl6S3EfmGVS1OWcGQA1txfi/o+G7smOzX8pGvVvBrC4oj95gEQd2LQvwTfdUmZ+K7B3q6zRPaFxCnSt0xeW2bJHfmdz9pdoiGLeIb0DeQjmsP2lygzVaHmmsKGOqP14vt+wHc1JlIlhj1MERv2o0jM6nosaMspF92FqSMVtKlsSUI9BXFSOK3dDKNiBcxyyxZ8EcYZPgRq1FACxZhjJVmtuI6Yt2C9czlGdzIurV04FsPqUJ3WJA7Cyd0v72+HF9SD8zs5I4iGryfau6cM4TGGucxLlIaD0EIqrgjDkC6Nkg9maPpPPHamIjaomJ+xVH8Nr+n2SxUcoYOFzOJe8eWKCJ0U3/X9IK0EuzVty8u58rR6KC6e6i4zz2VmOMIoFn2/yHmTF0Hqw0Rx2sWEqsk4+t7xD9YI1s/m1bsrHKT3Pb42pwgiwGvgCnAaCXKQjAIY/lj/ime72nqgpDz9vztH/vFDxInHgKZJuHK8NX3oPITla4pkAkE0xGZk5xebtnUiZTOlbxt5RNhtB/EBw6nnTsPqu+AVq7AQbeRpjG/6A5vzsGUtz+eaMui/DwbHU1MOScJYah9dLNTpildeeEmmWLx7IQ/63Cve6NoF7Q1GI7g0c9bg4/QyhHR6Jh1z9CcjTkYQUaGz9Kmqv3voNWjpDo3BB3JgrVRDvY0lAwYWyMF7TXINAjPHUKOi+unhTS+GZavqdTSo2CkV2fHXZ0F0FIJBYhWOLLAKAfp5YWvhN3by79l/T0symA+t7P6Z6ytWNshBKTtyGEdtB1ox/I5oFNyxwh8WqDv1j8FaIYJ9G4SKxwnIaSwYCHv5N+dj3a3bVojyVs2+UGLxx2TajyyWTHdXxzd28i+kqkz3Lqov0OBkKZpZWZGLKOrP7aTTMd3mnB1foJbfCMbXe5AVEMSdYhQ4HBhzXVDD714Rb6DleuAPCJtnDbjGHGNVsCqE+fbhMinz/fH0B9R+gMskFB3ADnhVga+HeAGe7XHctKkKsOXGxWbI4dWNW42QZ9QHQSNIAYYlKazSYdQrK4QmHZFl6N38xNXFdKDkJSZvyEBDZsKpn9Rl73SHvQAsgOpH+jqDLQ9bGCkJ2mtsteh+215A/gUnfrpURyrxu5SE9OVUgIbNrChRXSHrzbdJLZnk7WWqAmitqSTlBgLFQBQJcXFiCUVmYKtZPn/tU9TyZ7WkR82Adpn6vuhNXJsmDN1gT9giFmSrEcLoh/qCOnWMG9arOOrZuK+mYIRjj/93BFdb3fuiWCsn/IpgROzcatvMCyNsewi0vmR9gXtw8PA8e/cGUAH0qadwHCpCI8yw/PlnYRDO9iUH/Zetr0Fl1xH8Dpr83Rss1uzHNELIXc+f3SyX67JkojVF1yGqOFUYpxpt6/fhVf5qdmwTE14YBqbexJ/AwF8kjrGuAqCW+LxRTf8qOq1j4d73pAWvayWeQ7TOy/99phF5GjLyh94aeHNAZVdbt3CVvGHNmAs6vEazvbVg1Vyidx+Usw0NeoNPN0u7yTKhjKY9FBYL2a572e5upeFDIRmmyB4WyGpUMZ4lINFLAc1N88GSQ8drXpPzdnJ+hAszuq8EkvsqyWj6gDB2aDC3oj/Ff2TLtLHCG4i/B5s6aeEPaMiInx4KR0q9uhSM90Pab07viJ9jBu55/U6pqBL7Eh/8EXNFAS3Fi0x4hMIbd2xOsRBbe22Rfr0vwoAoJ41vkatOJVABTsgvNr3hPTUsO8sO8FZzZC+bxi7a/yAh6SIcJ8IjjfENT5D8eriqqLgO2QRhYJsHh92qy8KWU+wZk6wUJG0gKhMZ55/osQoyDtIQUoYr2Qz91zzygAPPkbuA8XawOeww19J+VZ3Fat7rzrgHNBkM22xZl+b81Pon0k5V6iexfubUUSk1o/3oFyS5WOFtp4MfUDsvBW9HDLO2+KNOu982kbNZVUZ57r9FRqtvmIylEceXgbdmADkUSOntoVRnaJmCDic65s6Ge9oP3O+h75TlpzBWrIbwlEZHJ7GpxB8BA0wpePSkdFr3G6aXsITD0/sgBqxLTxjZbLRdiYqjDjePtJWCkV+hFNPBUYg0Lk9cAEoOQAyUAK6qX//rC7mHcAXRgyAnyD/1avulJp+gmPp6Wx8u1wGQYq8myHypfTrFPx3MMys18iGFmICW7RAzh9CAkb38LqN1AWIcniZgHOxG41wmnzR325SCbdO/GJhL2avz28yvhYP8CMaraliUTC9HFmw8NSu0dzTX9caPpYAvGBreZ+Wgf0U/NIBFc0w99dZPGLJhvpGXxr/lACNIPrcVQrDt1pnjcH279XuKnos6KJF4UFLZeBa+pzvk79GlUTkEm61MSVUQERE/AGnlAd2vxg0vzIl72EBOxgJeGrbF9D/oy+SgAnPyUhzTL4mZgQ+mDCDPevIxH7kD8rs3E2fI4SDo24+Xn3YUqoOlYyuZALrrIiWcpaZ5wkgsy5Add6X99bgFUdoijePORzP1O7TMb1t9rft2je6OkDTKD50MuIV6x3QekDg1p6VZcLNLv781KHC3alXl5nldE3AQKHlPDIGfSPBbRGITx6hM1GzCDpeM3pxLo9gw1cxBKEYv5sA/frWoRlF3at0mBIsFCUSXF7WeVET/ez4qsWD0zwLnbpobjpnIF/lX6QdBFpXoXkFBJRdzYUkYosmoHpg9LSEakEgr3JsKOE/b0IW19vZoAiKjBRKFyHNhEj6CM8J32vqIjTJYKgViwwRzGpiC9n7NO1EDcGer6cv/1KlboYUqxPBGPa5PoZ4hRF5kBKQeYBlFcfR/sMR0q6ae6vwX4JMty0BfMXqZjl6i+C+g9xJdNeTc6aS//AlqNRRgoPET/+QJOi1IyYYc6g==,iv:fVmcsJnMTGvgE61rZqhIT3mPn6fl4lXoDk0MCXl1nDA=,tag:S3grXkPGpeSnGWvi14SMJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:UTo/wN/lKZu82PcBUGZqXYW+KwDMt7afK9OngDZH9Gftbg5YItd3VTT6cveowTL4THCa9PYpSs13msjbzbk92R2P+f8ZXeCUTsIg2UkamY0yBCs0qLijdjpcGVYeyIV/DMpYUj+i4juIznSkH0g6CR34w+02suR/CJtIw3PhxfZzL7oHhopjRk8ckZrEngfTRkhYokePd2A+JXuJFMm3OGUD19UFxL5rOQ8s4c4+9FWdlDWL69HnGLzRgQyN87EN93653Ys2x36GA7wrX+cCs0GEQn/2zNcmESUpFTKEmSi2q4dA/qpBOPihK794MEgtGeMfBxDKyl/02IboapCgjMa89OBG8liNj8Bw+m4kDOcuBfirAzAphf/CNVybWCv4JwwaUfuDHyL4c9FPDeG8vkM6M+XA/5yM71UEeyAjXPb7Z1zEnvCfvKd9yIew/Ly2bTtJGEfw1AHgbmNiW7AvlVyN7XT44Vnm2aT6wvPQUe5arFFPyxRi6ZKmRZGnnT/L2j3XcGSUBwYZbhjfhoSWlIt+bzgb9dxkPIFuJEj8EZyd3Np08+FpcdejLy0aaDVOzCSKLu58Ys34x5bRud0Hr+65GYfn1zJMVaZWNopQ4JHxYncks5gfgi3firnzGiK9SZm02zka981pPjqLLCoztUA+Rn3q1FUsW3EWH5aJTjWWHHP93JXPmVsqrVG/U/kmaaSRJFjCpS6iJck1T/0xT3AHdJHwfIX4QQ==,iv:kbNX8Vn9Ubs+iAz7KJi+5ovj/FkhNZmN0PjJZA2qJoQ=,tag:4NbPpHiBvxuMweMznVdVlg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TetIt2Tml3g7lqZZKo3B8jIQl+6hip4388JvDXF39S47iaZ7tn3NNf+ARaK8icBK03Fm4cn7u+a+ZnL5TLB2Jws+BDJHXFJX6kIlSm8rb4SU1q9hiSPyxBXr7bBVbrKalXyZIe+PVE8luEnC2H4uqqQ0lcF6Z/OpGoLb/Kv3vL9SI4Hd3RJ9rVcM/2cXiUiee1dhZj0MZgKFueMEDFKQiCy7cAr3f8mDcGEy,iv:WZ1CLy4d7+yEl8ITs/d8qwr+A9/H7ESBrYYpROdnB4Y=,tag:Je/Sexwlh7e7QyBciueGeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaURMekNud2lBYWJlaWJG
            dXJGRGRmUTJRSW5RYTVFN2xsRTNQZGhqQVF3CjhJclBjU2Z2RUZ3MkNaS1V2emNq
            eVJ6NS9kZ3dzdHZURWpuSm5NTktNN2sKLS0tIFV6V0hyWlRyU0tnanhoY3ZOclJr
            RU5rSVBBUXBUdnZBbm1sbGdZdEE2eUEKPyzMasdJNy3tjE9rPGV66WT9BowqXp00
            aDcmbgSbwFSmocnfOMfEuokLIImg2+Ag3Tt4elQDHH++d5syO0tamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T20:10:23Z"
    mac: ENC[AES256_GCM,data:8RRY65dlTQsLJu6YwfulLsswBzmnwFcl2hTLJVpzSNsd4qOOglINc06aa8JPY79sCoV7Zj3919fhbcbV89e/XFXY9zH9yjMBM6e/cp8hFquCyjP6N/OGwS4S052XyEXDur140PLJ4gx7cy/Qg2iv2gKG+4NqqjhLZDalajlSM5A=,iv:bmdGIORRl8nr6Av4AMdU7S3H5BgZT1EzSRVcP1QXgt0=,tag:kI6Vn06ESpJd6OS7njEzFg==,type:str]
    version: 3.13.1
