apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1/AvPR0=,iv:Qk60J1hERqJAh08O/+R70EeHJr9PPRuaStVNwD6fHl4=,tag:Q+/ui195MkuC4w5I5ixRDg==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:7xjkJ80yQ6KQGnefz+P5fcw=,iv:/iyAmf9BeVQAbsA3Ct//UgFDfPWNekm5aYZnYQezjco=,tag:3fqgZNKFmfTm0wigIrPKwQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:SnBSqa0eTzlcx4r53zP5obH4YNvWaJKX0rbe5+lhsJIrVhhdtu+SChZzeGlCs/JibzV/F/F+ZLRClrThc7J1vkIu/A==,iv:N7kt+19HLqhMcDmZAvHrKpM9Zlo2T1EZGsQbEW11b+Q=,tag:xkYR++T4GGY5Z1TS651kug==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:yeTEdCweBP7VjEMNXaln7dK7fnts8cHd+lIUvToKsGJjBE4xEkHpMYoHvtE4H8jiSBpH/Fu52krqnPIF,iv:/92GHNgnm4RqxXwKkgIc/5T7fxuIFoZ8yHNnlCZTw1U=,tag:MMjy1jMgk2nz1oamKHuDiQ==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:KwDvBR0i+pmZt/DqdbiwFeB21IcMFoayLe8B7/BczNhPyueQlLS3FTclUfRVFmuPCf2sJyWjVPCo7HvswxyAxQ==,iv:5Y6Q1YZCOR9bGAsGEMDAf4/Drzza3edE8bsWVsITVUA=,tag:V14P3iAUiaUs+u6o1b6AzQ==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:qGXlC42naQggE+04zeQ6G3pTmcx3N/ALoQs6TXEFcGQpWuf1rw+Nho1yAxsJQcG8,iv:Z/psKgzUF89NYnFIDmC7FFyEQBTS0BS5qf4+WWZhj0A=,tag:wzrcKUvRhCQmzgmqdTRzJw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:bTgiTgYX,iv:6I6UrqxgqJlpk7x9QxFDCF8RtAtUitPjRiXu8/jEziQ=,tag:jPj2kl22CESdzAzmbGQjFA==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:tmHNlA+6Wai+6MglmDA=,iv:mWe5c1HJ00+TflWDljU+UVkv9ZdIHqLKMebWhWPjHa4=,tag:nQJpbe5ninb18JdWSU6obw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:gzipvEf1,iv:3qiRuPwjYHka6XYLPeOCMIEVsi1hUrVltYrnnul1hto=,tag:C7H+W7cQQ7qV+LDI0mOxlQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:r9V0kwEIznqvfi+E166VAc/hvES3PA3lK2gYaJk6QqrKeITZpV0la0nfoPz+msMP19s0Z0yI3oeGs00a3OqFSjjbzC1WN0yXVrgflWOdDT6WuQxCsZ+6eByxzavNEVKtq9l5QViDvGw3Rji+n3kjjucxTx3ENAbpYSHrigFk4l04vcVLU0bIcLLvs2yKrcxBF3ROT1D6IOWt99EZj6aj3lAX3/O/hVJg4zLqZvTyf8M1ObpGE2Jg,iv:PYsgXr5xyv9cnOtJfJ3wr4iulsYJd3X0Gt62aHy9ADU=,tag:JeNrQ67Iupikd2w7mWh4Pg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:te0DqsdVimfQ,iv:l6Z6uil4rDKfOvdIpsyLc/RZ8mFege4u/hey0gi+HS0=,tag:yZLffYcgHzpU7DFvGLIF6A==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:2o4lE03YwDRQpCL4qG5si9EZJ/4ruYlrm7W8VSmfqMvd+1erPe5K8Tf5Vr9d8g==,iv:rqF8cBFqbEx5eB40qQhWlsHfiRloDb2pzMn6LSqaWgY=,tag:a4NupRw5SVykpUQ9i4RFgA==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:fmT9E9iMeOBZXPZCDAo=,iv:RC+TWHbbXkC9Dj2kdxyYJVpsn4Bicvdelg3+qhpEy9I=,tag:8NDZAwZ40qJUXeoFsvZ7qQ==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzlDZTJkckd3MWlEVkZJ
            cVJCQi94WkZKcXlBcUt3ekdNV0R6Rk5JVm1zCjYrU2YyVEdXaUlzd3lWM2JzcWhN
            aXJwaUQ4TEJpTlZMMU1oSTh3QzZxSXMKLS0tIGwwc2FqSitqTkdHak5iYmkyeXVQ
            ZVhzczd6TjJEaGp1VW5aS2g4WWwwdEEKUyGJLZaiFyqA44QCoKqYFKLSWIaIdWJB
            /B/rNQdjtzDDYt9uiw/bCXddCcze820GD36J2UZ1rf3f+aWKdghhKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T05:38:04Z"
    mac: ENC[AES256_GCM,data:CUsjrlnitK/IEyp63BlyzlRNiu4cxgN0ROEEJUpR5Nkak3BAwzAyJ8XXfPOz1eSpEQ2/8MdbZfp4PZz1JGS3L0+xysbUHqTdeua9zu+ha7QQQyWf2LucWBuUZvwval7fpvFA3BRYgzCGk1SCTJ169vaCAk1hIboKX1vytdBoLj4=,iv:cJ77wDKZC2CcpcNdckKxuWryyzVxxrD1HdI5Qwl1l1I=,tag:KtKHkwP6ST/99kH7gKaY/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:Y6KQckh/KaMuYBBo/NESYgM+DtBzFSEGffsGhvZiyEayLRNx//ZDAQ==,iv:pwe3PEFEsGqEUpRqvmLHLH1GmrLFF/6VmiqguXz8wqA=,tag:IO9caJKUKDdfwSDmNTFIDw==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:44G6qwqrvBd02nuAPPPiSrg=,iv:3Kq17YALWOLJUuuDPI2Azq5WHCUHMivczfbBLOfZM8k=,tag:BEL/poqczVHPFR3Ooskl5Q==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:Eu+139pbNh2D+gwWLZtKal5YO+WUncrmJWupa7vvfkT6JeEaWxAI9v2jfbJ3DXqRKkTWSrpxnsjYYHbf9LRRoQ==,iv:tkDR/dTZxyIizqiq9urRKlScWw8iBG1yblqAf5+z8dM=,tag:MYGmfEehUg8LqK9A6S4D5A==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzlDZTJkckd3MWlEVkZJ
            cVJCQi94WkZKcXlBcUt3ekdNV0R6Rk5JVm1zCjYrU2YyVEdXaUlzd3lWM2JzcWhN
            aXJwaUQ4TEJpTlZMMU1oSTh3QzZxSXMKLS0tIGwwc2FqSitqTkdHak5iYmkyeXVQ
            ZVhzczd6TjJEaGp1VW5aS2g4WWwwdEEKUyGJLZaiFyqA44QCoKqYFKLSWIaIdWJB
            /B/rNQdjtzDDYt9uiw/bCXddCcze820GD36J2UZ1rf3f+aWKdghhKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T05:38:04Z"
    mac: ENC[AES256_GCM,data:CUsjrlnitK/IEyp63BlyzlRNiu4cxgN0ROEEJUpR5Nkak3BAwzAyJ8XXfPOz1eSpEQ2/8MdbZfp4PZz1JGS3L0+xysbUHqTdeua9zu+ha7QQQyWf2LucWBuUZvwval7fpvFA3BRYgzCGk1SCTJ169vaCAk1hIboKX1vytdBoLj4=,iv:cJ77wDKZC2CcpcNdckKxuWryyzVxxrD1HdI5Qwl1l1I=,tag:KtKHkwP6ST/99kH7gKaY/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:4rePNSVwGgA=,iv:wKmFqOHqPZ6otaYfiOXPBDB5RQxjC0mqhnL+IGpg5uY=,tag:8Vwotb10wyRYhqMrznRFVQ==,type:str]
    password: ENC[AES256_GCM,data:eYETNTWNqMwcoHT8Y8vpTt3XrrxGZ8vxjUq3RD2jgfLJOQYqbcDzBAPPgxKn9mHSPJ4PqV7oNRK2o0+lqb/XEQ==,iv:lE+Za/hyoeSxGBbXC7weNso3AHywKNR9Nu/CXor3Ypo=,tag:yTA5ifRBQQz8TrmX2k2MfA==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzlDZTJkckd3MWlEVkZJ
            cVJCQi94WkZKcXlBcUt3ekdNV0R6Rk5JVm1zCjYrU2YyVEdXaUlzd3lWM2JzcWhN
            aXJwaUQ4TEJpTlZMMU1oSTh3QzZxSXMKLS0tIGwwc2FqSitqTkdHak5iYmkyeXVQ
            ZVhzczd6TjJEaGp1VW5aS2g4WWwwdEEKUyGJLZaiFyqA44QCoKqYFKLSWIaIdWJB
            /B/rNQdjtzDDYt9uiw/bCXddCcze820GD36J2UZ1rf3f+aWKdghhKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T05:38:04Z"
    mac: ENC[AES256_GCM,data:CUsjrlnitK/IEyp63BlyzlRNiu4cxgN0ROEEJUpR5Nkak3BAwzAyJ8XXfPOz1eSpEQ2/8MdbZfp4PZz1JGS3L0+xysbUHqTdeua9zu+ha7QQQyWf2LucWBuUZvwval7fpvFA3BRYgzCGk1SCTJ169vaCAk1hIboKX1vytdBoLj4=,iv:cJ77wDKZC2CcpcNdckKxuWryyzVxxrD1HdI5Qwl1l1I=,tag:KtKHkwP6ST/99kH7gKaY/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:kWul2nUMDPLJ7HbktS/urGkUaxfSHFXsPChUmn0kz+qmPZvMgt1yjdxD05wsD6DmCQ201uYpnKXslQBX9/BQ1L2/7bZqxwj2wrzLyrWajq0/RCKUQB2WrLhYuOsTGHLu+sqF7oMXhiSC/86VCLJqL7+OPfWeM+Y03sdmXSpEsYTzd9zSS+gHs4zXsuafeaVZuguIxnB6V2akanvHd8iM9Qr3O0h0fJuHg88h5jwohw8F0gvw43qpdd2SJdewjZz5je+8Tp5VVn1W6ri77L4n2Q2ZldHt5gSogBnmJuTW/NAXz8Nt1zjoo7qvJmdrrofsCdpx3zFTVx2l42hJ,iv:MY12lbOcF3J83hJM5qLk1rBtc7RcDfV82h6iK4GolZU=,tag:z7Cmn6Pov5PLWWL2vy1BPw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzlDZTJkckd3MWlEVkZJ
            cVJCQi94WkZKcXlBcUt3ekdNV0R6Rk5JVm1zCjYrU2YyVEdXaUlzd3lWM2JzcWhN
            aXJwaUQ4TEJpTlZMMU1oSTh3QzZxSXMKLS0tIGwwc2FqSitqTkdHak5iYmkyeXVQ
            ZVhzczd6TjJEaGp1VW5aS2g4WWwwdEEKUyGJLZaiFyqA44QCoKqYFKLSWIaIdWJB
            /B/rNQdjtzDDYt9uiw/bCXddCcze820GD36J2UZ1rf3f+aWKdghhKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T05:38:04Z"
    mac: ENC[AES256_GCM,data:CUsjrlnitK/IEyp63BlyzlRNiu4cxgN0ROEEJUpR5Nkak3BAwzAyJ8XXfPOz1eSpEQ2/8MdbZfp4PZz1JGS3L0+xysbUHqTdeua9zu+ha7QQQyWf2LucWBuUZvwval7fpvFA3BRYgzCGk1SCTJ169vaCAk1hIboKX1vytdBoLj4=,iv:cJ77wDKZC2CcpcNdckKxuWryyzVxxrD1HdI5Qwl1l1I=,tag:KtKHkwP6ST/99kH7gKaY/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mCmCvQjxiipzc9J9ds098ram9+ooRH6BIgOpPeQNQRlDHYXYoz8GKadFsoznOETAWk28ZW9WKy0le5+il1XLSrPPLKMTAhAKWwFotI4AEMHqE9kn1VeGR1nhYw2WwEnGgHC9CiDbqQ9WRikytvTluvshoRf+uav9BLDV9WJNZOygfPEBzYWVz4IEEHHeDjVj7+qM0XO/H0wjA70OwKwczRkFxTU5un2pAd9ZgxSDfHzRO9yNnqHiNmzUtLN/5qH+3+8GE0PgOOxzAKtyLLwE9Z+tJzEPkkGwdKXblxx1wApC+gcQKhoU7XsZMNwtCRizrR71ffU2qrg82JuqIoGRvsnJ7YUfRG+zZwKrXnzan2kXUR4gACRa4GM6afTnh8QDO9T2cBwQDSF0FX4hdNNWj7WKfVXc+y2xKFIV2B5+CdN8+3JEtIho7ygyRuUybJ2O4OrK8K+ssmy5KrH2VcjLdE+nestNk/S5EeG9r5gReeW9Ro4/crzQUXGTqPaFC6S7amVeqYyTeIZdTPwiIER/JOnJQSxSCT4OPtgHqRCXiug8WvfQWzlDK+mPlnLjN32PU9elRHmH31NxArT5uIWCTS9s6RX9gS5Cl4PWo0T77twU9S3+DLIjHlZ05V85KX3Y50KOLPejwI/CN6mHo8x9uorL+ndxuUnOQVLd2wFXYEStUB+JpeCJBzGR/VwDZlM6OKuDF6Hs7+ghj6rHg1qPNspiiOITq45Ct7Ea8Qya1+PM3CC8MywSXXvWW2XHoeJcSF6CRh9B1qFd0FXr3EKILXuog3gp7f2MnUuImQpcnYk3M5zvqcGugyV4mrXtI/YhnOBXnBr6SkbLegS7BF1NRpPEsRoYwjNUB/mFC8lQcbeQHLLzrTMz6TTTg7rVKI1pl2LaGgxRWKwHVHcL0EpnwXQkqOhEaZKvkcOUw3bSmjm5qVIUobaxI311xc0kkZhawkSIK4d8v2VHDtyfnaDjS6zuuJLOkhlGjltTDRGptkWSpglKtK4A7/KEbnBgxrxFCfPL5iuiSVm0DA9QU6RS2KF8qRI/dLYyXFPlZ5BAs3vGXdnsxjIDJqVCDmDgVk7jPI7hqK8E/lvVnvwUVc10aSAAIQmeIO2wRfFdvSI/DUUS6vcJ5YJ7O8vK8Kv535fqRTsWwLX9tHTbiKdbPymTUWmrJ7UIFo8YNewbd0TqWJ8vx0ep4S0rYVfUKqIZPifI+GPCuZo5ILpALwwokGuqs+FUD0PR8TRKiWnoVSyKmm20EiCtCIgG4VCffqEZ7prtakcCdKmiguTWkBrfnwms6uVk46NX37xS68oJ3whVQYgdoWCgWv9o8LubqfxIiORk2Q5INIa2bIJ1I57j/fcCcCFtFshZP4vp/3NzPyE4IqH4XLloOPgv6/KNwTIF3xjpJwWM26U+bwoc/MsnapHz0JM1h3u0rIUzuiRaVAhPM/AoFrkTK3fVQxPlHBuE9RyQZepI0WxI6C9KzAlTjvdbIATigYyt6omvx3ENmdLR3MJLXmO6XFv1tVA1X4e4sKOR/sKEXoCRaad3c7Pqp57tULOIgfkC4fERFoEHro4D/0mWj9SaBP5UBE9D8ilgA0aAJKyYnx+sm3ueQOLTV5tvHIhRowxl09WAsUsySpfKXKrmHmqYPfA1NwGN0prB+tKcgH0xI7xwQa8bURTZHpuxFCIkVsQScaREHX+kEmxF2++RkSuRwjHl7dCV2QPxfObLSnSUfQ95tbKUxjZocgBVGhfjBGNB5MwfSEUUTvLMv6kXq4ZHTOKOU0CsstY3FXBjQjemn6fm73iDThmKXdwWLSSiryqiZ/aN4xJnV0KlkxIVzcw8p183z76ThhgZKWs/qMLLjABINW6HUxCp+d2bIhkChipsvPyU676NHvJROvWKfZtXhdhihsrAlZG1wMe/33DdyFEiQ6UHP5evXojo40Tpr/r/bIQPywMf2zOUk7ZoZUyxUcBnBQTRc9fyZTjjXA9MF0RFW4N/Zk5dlK0mb19PW/RkDxOMuGRij0+hR2oBZmp9IcojSMejnuMylCsFFaAVqxMJJJWz14+87zyzsWpmSNqw1J3q8I+ZQ6X3dmXOQTW4H7IWAGWfw5QeTU3gukJ/+8OuGB8FVs3IuI5QNr361ah+/CUBl6z/F+t9vmUl9+sgkH8YF/GILNRnk4nH7VIjlci2T884hEQYzZNkTp90uzi33ZBPPb4Kc6b8dd+qwxwCVsjJtuaFSZR7WoKs0k5wanit/OYHNfYKll1pvDC2UNcf3W+4fwKXZZ3lykCIxxpxCu4TgQYO7iS9a6blwdG5pSayzk13vhTzr6tCcqTt7YCs35BBKdzSa/BzydTp6t4k7LjP1MKZrm5qP0O8c93jL8SlAYmdfuxuC4JyvtbVJBZjnjBq2fMUVWCIXjlesIm0jRWWxGEeNevm+JmB85NsjgmQnvIhPPfiK6Z8L+yce2qwzB1z2rCHt1InooFUEeLunxIIWM4XLlx4xE1G3Mr6Sj/aH7A3wppfiIIhIgTnW9u7GXSC/34FnR0nFO7IeQOTlJ+W61kBONh0fyttgIZylaqiWBnbBWIF6VyDdaY96/tVh4G6D36MWb4GqfK2YsYuX1pni1g5H1mow86Gfu5DcOSXmcwKAz5xt69KL3zTBLKsiDI2MgH7+K9ruknZzBuqsK0x6Ve2NJ+UN3JsRMD4XJrbmHeXsJ+TROQW8PKnM+/NL4c0nR5GTlcWJrUpBHHgrqqUnm2W1RZidpkFumNKrASMQ0Gu8lSZ589ky+YlxnqJIFHzSFSDMluGS9exiGZ/NJ80+rHc/TfkEDsr/wVDE0PK5RkVZAaaKkBB+3LsPTdB853/FRnNyVZYq4b+/f6EU3w4iSnJ2PjfXnv+GkateDTwVorHO627Eb8pSWdhRxeGt+pLuw2VjNT5hTTy0hWiy3sJ2u8nHVBKJ0JCtCgZYl2SGEixBvB/dP95/OPuhb0hiacrsr3fH/lZAnQVgS6bpRje3OSKYM1TTu0OqjwfX2TpZLONT1Vm44jiLfRBgIcaLbiDtwA5wV4Vd3ZUdauDXZll81m7hLHVub6oUZhBRNNWgcBqS9wXob2i8g8X4kHPmsHLQB+zYKqmUN2twIXl6/SXoXXha7qeHa/DaWKYYiuo+pG75Xi9tMQ84JFtCbc3C4slmnUO+Owb+ocy1XXsS9Lugs5/Xb3XQsChlgrCzgYa046H5SNeXCUHuYKIsDoPqAiP+Q+B7KJnszoPaLCz734RoahYGYNM0eIdf7sRefloVk2Twmj8zuH2dygrmngXBQFYwLOASw6S/C16VJ7TG90SUaYNYR3zhaRTGg6LskvgRUeto2YqXY1hxcwWkLHWHxiCwMU5a5MtwV0SmZ7O7iTcp6ItnvkOpMzvrg28BDlZL5gyvhkU0ltU7EvFXAe5ldbsUNVZFWIPx4fbSOMG0rIPdFdgEBmx0mSO9R6kENYrywG5+A==,iv:wi1Tl/EqZsRI3qk4Z4rTFOZURAsUkO7duUR16ErF4Ow=,tag:l8/aXDi2qREkQZdH1mp7pw==,type:str]
    identity.pub: ENC[AES256_GCM,data:TMhxpeaX0sPFlTDSq5IV7kr5gZrQZLGJxQ31TXpwP/5lQPtDNF4A6Iy8G9jhee8dy63V5e5GNH1Ncvdgzi015dt9n8EtGC4wvQUQMNnMCS/a8m+RDekKlyEAC5oBLM3k2JhTqFNrE7bLcjBX0zSY40pr447wJklf5A2RYDW9TFkyRUWseZzLTT6NCnRemBK7+XeI94664RlMVJaRNiUtGblInKghQjJCb1lXEwFpacRox2U2iidZwtVFc6OWFawVrWdCtpN1CzppUr/FAFWjvhiBJC2Um76YHSN9A2VZjRwzd8tHnxdQiLPpuWo9JehuyTjHevAFmDZllmgaA6SBfTP5inYVBtdyDhR/RZG5AzBI5a8abQkRbS4ULP/iNgYZQ3eQnfqQtUHO8PGHOelFz8A7gka4S3wxpC5gF1KnQBvmvCOum1ENGUAz0ZCEne9tMfMWMLP3ChWqnEnKC1bo7tINTTV6f3jsNS/sh5COR+QHL7WQxkXLqWpeH9m0x4nsUNPvUbo9jKLgpGAhq0PEExJrrdvXUja7TqHGp3FBibMvtzdFirUho21JfM+p2QBwr6ZDcblOlzxIzqjjy5Ja8/2qPrQBHYl79mcT0FWs8qc7QhIVds8Wtsb8J2SKLKjwIDg/9N0avTPCKu/qADBdm56fM3jqIvvZtTDUYripw7GiiymTvtVY3fmmqbEQc3W9BT4N9XBEsKHTDrDy+dN3aeVhx3Xs7mg+NQ==,iv:Q4nmAwYUfFslYGdEyBLmpmYXLL8sVE2PhGNxwnid+4I=,tag:ehlRXSj7MHXudpKU1kqd7w==,type:str]
    known_hosts: ENC[AES256_GCM,data:YwOzHiBR/l6ETNPbYPvIfYYPpERiAb8pfKLqPmgf1z7kcLieOPBFWJp3TCFQh73A0N0OpgcMs2HO0nbpYtA3PSknyzXjTrZNYij5i5mB0FrQr+vCqaahD1mAoBWmU8aF68Z4ypVIwqN+5HZKtQ6yfMIDNabLhCTK/coV8/TGIPoubV1PmELcy4Y+L4LkZiWsHlDQ0a+IEnie2DtKOACgUo8rSYrn9FRw8pOe,iv:Owqzq83NnVe13HwmLcofUtNEb+KnagJKGf8jK/qFBSI=,tag:56ROiy6pA6XfiKBtv88y2g==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzlDZTJkckd3MWlEVkZJ
            cVJCQi94WkZKcXlBcUt3ekdNV0R6Rk5JVm1zCjYrU2YyVEdXaUlzd3lWM2JzcWhN
            aXJwaUQ4TEJpTlZMMU1oSTh3QzZxSXMKLS0tIGwwc2FqSitqTkdHak5iYmkyeXVQ
            ZVhzczd6TjJEaGp1VW5aS2g4WWwwdEEKUyGJLZaiFyqA44QCoKqYFKLSWIaIdWJB
            /B/rNQdjtzDDYt9uiw/bCXddCcze820GD36J2UZ1rf3f+aWKdghhKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T05:38:04Z"
    mac: ENC[AES256_GCM,data:CUsjrlnitK/IEyp63BlyzlRNiu4cxgN0ROEEJUpR5Nkak3BAwzAyJ8XXfPOz1eSpEQ2/8MdbZfp4PZz1JGS3L0+xysbUHqTdeua9zu+ha7QQQyWf2LucWBuUZvwval7fpvFA3BRYgzCGk1SCTJ169vaCAk1hIboKX1vytdBoLj4=,iv:cJ77wDKZC2CcpcNdckKxuWryyzVxxrD1HdI5Qwl1l1I=,tag:KtKHkwP6ST/99kH7gKaY/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
