apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZZPRut8=,iv:Sizr9gssC8HWe/bZgnzy6mJRteUPRKU8E7tkV6oIF8Q=,tag:A7vd9hQaM6DC8V06WI8DSA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:wA4N/dK7InzhnCYxurAKAYs=,iv:kYpNOgwLcRL/sk8FDZAlwnYsXh0+wFmadtzHSRzuAnY=,tag:YX3NtapGXTqAnRGkxbfBTw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:oBx+/K1GdnSlPA2UNoMgEKarOzs8PN2hyxNF6S/XSeu2za8QvCx9IXSJCCiRKgU30Ct9Uye79f7y2yXZsT5/1zd0vA==,iv:XpEM1/6zgl93xP3/9OjNL0uElIzCwC3QoBADE0Zx2Xk=,tag:QuOAgtQEAuNHcCKJ5k14FA==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:MhemAjIPZnRVDM/FTPBQkDXY0JbmFc20NhvBb1XLzSVs+vNQqJiJmecxP4akzkPsXBmVY3S6Y0ROfSg+,iv:dmBBPk91974vZFU0hw3B+rxCO86ID2/aP9xncWqPsYc=,tag:zWWHrsmDuyeaZCMHe90ppA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:C4x0bK0kpQn7GoUvU1FBH2fTinkYKxtnbLahrgRCCw82kK76S6Vl+Q==,iv:Hx6h4TIEm4Ebo8gU4eV8R+qOIZ8I2PZ+FUlE8j3gbN0=,tag:DNvlxBWrruvVMYXo6HR9lQ==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:TveOzNJ+WDgnKKRy1ZqU0YtCZE+DRbdA/VGnScQwu2BawmEuWs5LKNFNobcJxtNiRiYvBQJ2poeA6OMeEi+OTg==,iv:8R0PoqGXGSdMbnvySPo38w5rzJFe5is/DwmX/ELVadE=,tag:Msq7D0r+5lesPueje6C/OA==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:GCVBVZIn244vdOVteU57k/RUPkzIG4K7eLtvvDV4uxX4sD0XrxzFo6TgDC/bNa+khFE=,iv:ZSlON/+frgVCpTXBrURUld2JzcLxO8lZcej4Q9NJ1Bc=,tag:cAtJf9C3/o+IuIR8PThPMA==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:cQD7/BReuW9/FDI9Fc+RAieom8ckx89xsFjk5stzFKmdeOO7hvUVC9cu3ppY43rkZL8=,iv:1riHGt1gYf8/zM/CqH2XX2vtzFiU2aZDFrKNaWbSI68=,tag:e3A1OFuP6z/ohDPlvnrwgg==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:QAW/ijHSyvm/9HPgBJxrtMv7J8SC5Dwp19O60kDr4aJrtWoLP7GXBksOrrENFdc1aE4=,iv:/Cb+sTmo5tYlOuModeXYOn9RJ9x/Qa6nv4UlgmUg110=,tag:lcIRLCyVubP4ORBl4jaIjA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFZ1aDd2NnpXVXhYdVlu
            MW41SnpFUGhJc2EvVk1jcTBXM3JFK05BaFRJCmJOWFZPVXpXVEt2blVidnJhalpR
            bFVNSk1qZXo4c085eFdXdHY4cWx6dlEKLS0tIDAxdEp3TkdyejhDS2duQUxsMnJp
            ckVUUFdnWEd2RXhmNDdsMytEK0ZvL1EKfT94w1AhUfKDajGv675dUm00lqnfzKhO
            FGcNmX0kycWd9sc+WKxBfEOmv9Y0/iYoAwf+qcL+TyM4M21sqSnmEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T06:10:44Z"
    mac: ENC[AES256_GCM,data:yYbHPiEqtgRRwIRWBpTet1Qu+GO4n6NjgUInuGzPlFjxPGaiw0uXtIklY9Xdgx0JNoTOe1gyqtTahUTuhg39uFAV3hEk4gzanvIQUuykLkBPhqtxDcp5DiLFFnunGE0oO3oiuy+2gjjAnsY9/OtcBjE29VHy/sx1VlikrvZVEXc=,iv:KerokS+zimTK3d6CdZM9PBoGoEoxvmU8BZKkrsPIzyg=,tag:iuPS3TebX/C9YQaA0ihyog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
