apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KTsqP8A=,iv:nIkjo7zAJ0eif/XS8DzXes5fibYCDUpYIfKHzakGGfk=,tag:kVCDZZxROVDZn9q7Z385Og==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:zOhLZA532f2dnYX+5INghDQ=,iv:qoWR0Ebq7/c9m6gMTKpUobvb81NsCuaVxXZjEtAe8VE=,tag:KIqkC9JsfGO6JM0DOrBqiw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:XtJ8DFiurWF5mRENuHg2KgEdSWRC1AyNaMNoLkP5g4ExCrfJvbZ73aUQrFeTjAZHC7r0BtjMXr+b7vep4Ox2jeb0Ig==,iv:DwGCT9IdVIBU6tGCuwAGL65blyx0hCladp5BqKoMjQw=,tag:0uRli7cXlZWHnm7TOKQBnA==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ew0HFgV97NEoZCeZQNC0xSzj5M+0nduaqT9akklospM1cVboA5cDNjtBgGyw+9OX4GV/XX/jOeN4L/iy,iv:9XH51DecYPQgvFaG+pZWX9U7hDRuT+r/5jGEv3yR0cs=,tag:8mM45FLiVxB6PfcblCHaDA==,type:str]
    CF_API_TOKEN: ENC[AES256_GCM,data:uT4c5bpJZVUAsPJCEnW9MBT9vGPY+0uqZeXEIcPifD8JO7kKPwP6ng==,iv:6dNcF4jpfqB8BmfDicgZeTBoCQBSzye0MGqWhVAlbPE=,tag:AdRSSuywnTlhYXMkjx29BA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRmpORURvQS9DaTlYM0FD
            bEFUbWZVenFLTVphV1pLakxVMVRTWkIrMHpFCmh5U2lRbzIrcjdzNi9LQUh5ZVZZ
            ak4rSERpaDRONHlpbWtRL2FuRkIvdDgKLS0tIGE1bDRpekJqMEFrU05PME1LRHhP
            VVIyZGx4UklYZ2xveEphNUM3NmFXZ0EKdrmethxCv6dH1J3H2kDMm3QEnn8xJZeV
            qcfqUkqsxtUWJ2JopSmcKtHwJCa0BYVel23WfxH5/ZgXYeQEkhOGWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T09:15:36Z"
    mac: ENC[AES256_GCM,data:Ad5mQgLp3rNQWMPLcslPk/IwvAGQAkNj09DchIPa9XbwX3O8G8yZjUAXwoNw21DMWRWKalhd5dRxq6lYjqF0irTmYAg2AeM4KPCKddL9H6OpaldtvHzlZ7aI3HbP0Ii2PRGd5QiSjKx11a2RPsvH8w6bj/Yjai9UV1v86sfJCyk=,iv:iQvfn9ytdSA2PC+io+uq04P+FNDmfBJE0/rXd5htnUs=,tag:CPp43kOzVksujjKCtvVe/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
