apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+uupA9c=,iv:rD7DEBlKyx/KlF8G1hOaJxnvArdYXDpOJgylk21AfdI=,tag:TWskq8CLRD6sf5SFdyKUAA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:4Bg2zPWIcEnOsxjEbXn5NY8=,iv:r4Lu4Fh/6bp9RjrR4JPrpnTQD9Ghwym9sC75HuY0ewE=,tag:FbthYj2yzz7q90S+JmVs9w==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:DFWrTV9IGhy8SVQpnqfb8ysLhxu6G92mdzMl2MikMGLkwIVw4dm8QkXdaBtWgVg9Oy0MorHUPQ8sotjx5/cLF+4ouQ==,iv:/Av67iyGtOfqCLecpCBSgWdYhj+Bg0OLrB1j2eG+Ig4=,tag:LFvGB9xWjKlmdl2baK6Sbw==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:kq7/6JVIm6+sf5/oRqIwKclO8rVLKAIW8jJmfqHXvdVZjBaZcri2Om0DShw+J3YYTawwiuFL1KSdtVeo,iv:KrSS64jpmc7vGsnMWmqT3A52GKdDy4l+yQGfZ8ndLr0=,tag:MqGaZ8bDNM9iVk53+K3Tzg==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:pvm1ooedb2OXMaLz+Uz9zLgK8Uv34P5qLL1TH5ThiNSH0EGCgGxIQZKNrOalm++VK92XiXdoKU+acK2FGZNMnQ==,iv:qtAvw7PK8BU/MrvLhD5HGCYMA7+XLEdSPw2lgwMAngs=,tag:ISfIdsqYZyy4VNaQQF0fWA==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:nY5x3c+/Baigt2f8BECVKZWRcTFSOy0zaN0GcYvnOEUCeCIfRaUkwYDOg64Omz2E,iv:oBAF7uRZT9Z/MvoPQy6sbTmZ7AhlKG+hjG6eK9xmoa8=,tag:VEZxLO1KAf1pgfZh/inLhA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:7YvbNA0S,iv:cdQt8WNjP3LAdMxMJVMJ+4W8ZOovYejhZFTFVxXz+gE=,tag:9SIypfaUs/R88ezkKilxew==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:gNr0v4C3XJWnKzXfSYk=,iv:PLNa35CRZmEDjo/RgifPVx3qOo9QkNBEHhejx3mxnk4=,tag:L1M+1MsGHIURCq+FFUlSZg==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:YhmeV+uN,iv:KwEd1RrpctxbvQm2TR1Zu3nlfAHo8PAEoqHoSod2Tac=,tag:59Rby3OdtsQQ6L7tKxlFTA==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:5OW4elKFT3qKq96iDjRiNILg/3/kii5zzKKA6Gvfy8VV80XLE0pgruZOOBGaSuD6xrI7A/1q9lGJrmF0ZqsMeBco3JC8WuSXDlmXMRulXAs3mFqEUG4qhczht2w9uo9EbA2ohCVsZnPzz4y39Rx2ZRuKM+nuSHqIIFno84w6xiqyn176KIAZbR+4lvPYKIvTjJjLkDSSNz9ESKSd2PTTDAr3+D63uF6Wmb5OIvVGGByZ5LdPDeLa,iv:J8u79rmkwkhFBUe5iod21eF4KVm3zpHy7huS0UYb5yw=,tag:9mufFFm/C9mzT4x3HB7Uwg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:xuZwSq2ypbZc,iv:eOBDHUTFAA58+3n0Buxc9RRLGE0FvVsRZ8g/SVSZbKM=,tag:3Lzh3BFGN0YsIeLIIN1DEg==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:hqutdcdcn0l7IYzB+HFIZecL674GOnaZklVDMOsphZYAKPe8ubg2jfS/+9Qf4w==,iv:lprk8STBfBhJ5IR+BPkV82Ky4olbKZnSloVsXEI+fJM=,tag:P52SUxB2D3jYprnyPPioOw==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:C9iiroJ/yLv4j7/6Nrg=,iv:D8zX6JJF3B2m6/mLxoy1piZCDw9XoiE7899+du5qk1M=,tag:6jsY1vw4KRDepQ0nH3z2sg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:M+HAL4CelOH6E8pcnuBBlg72Dbkn6QXZl7kLi9wWgNUP+235TJMqOw==,iv:c47LK8iJ+7GEFVGR4PEOXlatA5scKzpB7z+9U1V2IGk=,tag:2KaPU79jFeJaSadjlJNfYA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:A3N1u7Y/i6NFbYv6h+xQaI0=,iv:Jldc3jGe3cxq4FgzqanBah8GNw8xgyBN9GJ27E+DCp4=,tag:ZD9rquUXDclq44uVQs2tfA==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:0GWSaHDTbWE+SAVzXYyoG/syYQiodrUWwBtLFHGNRt0eZ61CV7Tp+nz/Js4TZe5r7MaQN0I0vs7C52TZYf/GAA==,iv:5ULVypaqx55k4ZdmoLFAm9RVgn7swN0RgVQrwv2ztgE=,tag:dNjhmq2mQbBNcURmlbz2xQ==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:FlQvmhrw/pE=,iv:sQ7voaVyUkyISDEvsjXHqWhG7R6ymKvotlXkNCKZ4rw=,tag:B1cpuYbkm+DbL8iyBHGg/g==,type:str]
    password: ENC[AES256_GCM,data:nCHUV2DajnTU8ycqu8WMj6BYXnsScXFUh2Uz446pDhCtxa0JOhR033+J8aSD30mbPwjEsQsezyoWUwSpek/OUA==,iv:pj04BfpNucdEAHr7Z51F+S0R6yxSMDRiZWTn/jqbHIU=,tag:GsTtVhPZTgK/Gf0W7bfPrA==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:qEFUccQjbyA/LcfwhCDn/1UJgzEkXi/N6xq1ol9kZ4Y=,iv:s/2pvsmojQM2L7bnxFW9JPJHR8S09YuoPER/iALt5bk=,tag:songVt3jilMqcyYTe8nW1g==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:BblE0NKPO8aWA8FdwnUWefkRAaRqHR2uQg//h0KnvHD2w90BjHVeYOn5FJ3SVCDvIkT/AF2GwsYhrKB/qL6ziw==,iv:qvnv2w7ZcnOsKS+E8wcDKacR+SXYXBS1xoKAzIEd/Dc=,tag:0CrN6238Al9Aoyh+uHRHHw==,type:str]
    PG_USER: ENC[AES256_GCM,data:5HpmWw==,iv:5VHA8dy8QtDaQ4JhB31OZEUOZIM6iryd4DHTrInI6Kw=,tag:2xD9hDd9SJc8ZbKHfRsUNQ==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:IUED22BM4ZerSaiXnzyf9coPgkUTlBjG+LVx1KCC/3nGfwB3dahnLxmci1GDtfE0nHVLfal7vdpLN/omoBaKwaLz,iv:N5+olN6r66n9PzZayGAP3Jo4+BB8MBJ79gw24h9GgMs=,tag:UbeyUTd+7mzEeT6ZetUC9w==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:j2/ujipUMIB3C94TubkGbnGWimlbSc51rZ6FtzLFU0aU5/LRWZKA+1jMj7blVfY3cbYpCf1W6gZ48CtHIC1kso+N9RnNryYMj8c6f2VhMRKuFHZMeIHg+bkKxJp8u9MwFUN3jZHwBtJEMIxvqgQtVsMz1MB5rCaYljtgcGlk9thQhpIjKBfrV8twfe7TWOwz3N9y6DIu6Jkk3O64TVDEc2c44VUb7wEXn+oD2dUF2k7byKFFg47S9dxWkVxiXHOTR62rFuXVUEDRhdUy8VNkpG2C55MzdNrQKdRj1bUCWa8TKfpPKdIwNJVIfgrUB5hZPKsPmG0vjcQTForT,iv:g3mtgvRqTzjX76CQiy0d9sFOownvlxem9msDrP7Cl8I=,tag:9ZKgMlYpsK7juDpxKo4S6w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PTHTyaucgX0XyqZ/JxT8ywAhcO402fAtXmKxQw0x22Y7IzWZoo9nVlXU9WSHQVeBs5eXUJYq0GWFnViI0VznqrqPJpsAC2WH0V0seEEjNLn4LBwynDgFq4JYOxB02GCeyN/xaYVB+asLImd/GLvn+A50i9wewAYuWEL0boA4vuDFwDAEeezLnxEv2bMw/syJPh1fSqyidlOE1jUl6ndl90JSPtOt6Jayy5gIcf66Szu7BrcQm3HQfXmcwdz6RSxJz7Hl0zX76UU+z/3aOOlE9ZopwV/A+CzYVlx3gmi0r1ogVYOTtKV5j3ZkW+rnulXOrkAyz/4SDuJW6znKmsHd4CcmKZ453QX3hy4+VmGQqUnm8yrYoAKMkWWyssHimQklfDkqBENd3i1kdR24sQnAnUzxIOxiaHRX48+hXvJMidaQVNY0bHOtOX180EwadrKxSiE+7fIKjfu95VUX09jMHLzCWJ5pYewr1LreBBsnlYERH6rgcmirJn0UhY3T90W8X5xWCj29MRrePPu+68YOKvkqI2YJsvPmW0ZY9PwDywmsGwRtHi6tXNhlavQZn50jXY+xhv4iTCXGhAofhU3Ql9DwtXOabf6QbyrgHhqr0SHeEC4RqVnmT9C5HJhy7glUuZgVKIGf3oJLDhNELfDexOYM4C4wU/REWTn8Ye3/adm0im3Fu60E62+5vSA6UvputDVPkXOyOexe0K3uCATXRfP9UV8OQjt6DdmDh5McjtYIfZM3kFsmAYeNAkMYgRRMK+DEGp/Xx1pqg07qUvTVHiZliSrvObOsP5La40W8SPmhxjrT9oFvuest2qdvjTs3WU96ZdySfNa13EVBjMLoTlCpzPfZ6wzQjFiCvcsTUsuwELAsLVtGDV8m6GofA13+WiwGPeNXmQULYZqgBREpEk8cLV3b0th686PaECNCaMGxLCG30lr4c3SVgCJNqNLNLwtkB73xKNtwyWnTtlrhyNUFKxjlzGb3NwXhfrgq+nDJrdjtHNJhVt4PbgRZPquea8IDbLTLxvITSecki/6f80asV2x7MAuzPdXV3mBDzBIyPqEQvVrU1mzedHHNK2dornTBU8ypZFtab/3yN0R7Qlo/iFr5rfQvKP9xnjsKiUhfrmY9qYgvWh2dF2E6xYjLS+2g7zk0TJLt7ncs6oyneCkKhUL+iw1vJON51gvSsTEIR3j7v5u5j4505CjIvnmzVb8KS1/tbVQ+uHlvhIIr2lbI75QTi2vtDj+K0rPTSQ6WBxKoFi7BwvWI0d9k0Y0SbtIdLdxocb32tixwsEP3v5c6UXkBxIakZgilyrowcMX6e7xhcn0a8PemUew+NvR8CCnuCwo7hLsjHKIu5/7yu5yh1k/VND5NfFWyWKeJeP97KPudQfu+vdqmdvhdm2PZAF4y8C1UKwTwWSN7RFI6ryGz0Ux5MZmKK4GUidxPaV1fvr3o6XXOtO9HF2xitDeOtImHyeijWCsnyCEhC9bxS0NABeGFazkp3TH1DfCebCYV/J8fwhPidqnNCKnKCE6O1kHv8j0uMyofrnroSoU9nmxMty9WIyEnUM5E6AXZUW99BoH9lRh4fWSTkISH7FghgwE5ux48QZ/BeD0dKsfjXBRCOBB1vueermmfFqtqR+0AVqXcqcsOSrESUQBy+tYQWj/beUEc69dfdcd5OigU8fvpvuLB1IJKbPb8NVeynclPQ6RI1tstnguE1LtSQ7P6pbRyQMuV3OjfIxd7aHM33cQ3HQWNHAObE1U75dR9YJbB+SA+IdHWukKCg6I/UYrEh/sSdZto7w2ghbe9FAhP+rF4zNDI9U8GjGXx3rak0E4+6NEGDXCoatca8yzyGTeHkxQ+ITwEYIy8xBLC48gWzSDbCuLGOArkHfgdxtqBbmQS5lGbkrqnNL4lAI8qt75k8eI8IgJ+ctpgk0RRLsSpbn4TpxjiLdegu0wnDtONbeTgc9OZsQOTn3hvqHCzbJPV2C9s+K8uSsfin4aIB2yn5QmI7PoKlTpMQF4ywWoXGgBIiB15q7oUPhVEjxvjsxJdxsJdjbMxtowRxoD8FW8XvEZ0dJjKOgz2GkdOPtkRAOcf+cUsHJrMZiHY96e17l/s+q4quqgRgUlRA3YMQO6GMeqTN8xe9LRVtncXjKkk2+EnE0UFvmqh+kFWF17Y8Pvoqwd+ggpGOk+S5desoXZwbc60oEGujWbZaDitCYTCmXqUh6kqw7FvDodOcmtBHsE0sp0Z5e088wbv5AYRSXCxvhtCWN86L2tYUF/zwVQyxtY2fveT00B05d92uAXlKDnkoxq6qTm+fGf6vOkaJla7Q71BOsZOmvHEsfXMsWRaeVdKBcIBj/1KN7GDLoLkAsbhpWWu4yqSF8RrYv6eq/os4iNTJNEDyDJsFxhkdm/88gdF9EgkiolrRvc2VLkVt7z+03kJj5AgEAXXnzigKi77Ywm3vvT8M9oiKB63kbiDb57+doDmYCzuASulEZO7riFfwXZSNSRChJpaTT8b4eUIUzVpFvdHqMd0fv4aBj5B9zFjQdfN15HGbQZlPphGQX6LsCuvgNDG5g+fxtsKNa4J506iFm59KOZf+71N+7CCeETjwiOpbBYID2lenneITz653fTd7hltD62jLTO2LjTEA9d6gnLaJN4SsCFnU+INyW8OFSecPQFgVPAEjTOKLk5BxDzQa1jaCFyAPLqA9RhHtoriTeD3MwO18xMwUnNO4sXYmgcsuaA8OnX/8YEMdBKqQF3MdYvXwFjTMdmeVdBQ122laH/Pa+evyuuzswx+TUPhuMAG29cnNX/cWYx3pQ4GOghhGC7bkdZqyc4q4hRGhTx+H3+9EKWui6s+UvXmGIvX1cbvgbT3599ONNFWfFiIx13b9K36QLTqpLMCsLtnCSyJ4qjEJVPwTNuuCDXSb30nC/OSCF4iwadY8NoyUUTfQUuLS3x670TfghOYoKeCwukDLGQeihxjbCuxro0O3ZtGgnqNwv5gsx3oEXnP6W2ogJ/0KLsOo4GkJDOOSKWsEyFIgTpAj/bzhLtd3pkoRXWOZg0P3jsB+3VAjmD2vz2Qp8J//Xxt1XChGMw/6tKB/rUNUbz550N09Ql8fn//+dLLC/Ci/m64xLUnOt5Aa9Z3Hk6dsdOCPuWcOLRLyJuso1De8KpazCOnv+VJt5NvE7WGnpvzW5DT+j6V271zPChZ76BAxWVBgCj8+2FPgfIpOuL58rKCH2kwaxKRWAk5v+P9FMZJY+bkB+XEE6+ugXl5rHyLF1hoHaoqJhCrLC9p8wPSk4eXEC2VvgjjZP4vt4kJw1SefovQAVCNQqwmLbElPe8R2pGJubENGM4MuOaebj9j6pJujfTH+ztSAtbKuAzg9WH1fF7DtRYnYtDtha4Q9Z63JFgI3AL+Rg/uNjVGOXYzDKl/MgYBBi9Wa44LXIIgoGQ1BqGBmbU1WFByY4oinUy7bJgHffc1uw==,iv:tsOBLk1XobM01gBI7GU+1dw5v4recgVKB3eh7xLlHpI=,tag:/90L3z0JJsLuX24665P36A==,type:str]
    identity.pub: ENC[AES256_GCM,data:JuGRF3c9SljvbE2jM4o6ZiVmTg58ZVNjZ7UyjSR6coAxL1u/96y87mPS2Aca+r/oh0qksMw90vhxZ2KOhhck5oWpyuv+1UFk9g7BgVjy9iEE44GvKC5kG+ToO6CPx0xm/KJFqilJG2ec8klukZkyKStVpzHbc5kzwxjCdRrXRXlE4mNDCb8j9nW4/XJ7mgOQG0ip39eH0bxOpjz60aR7n4P1rhG++HjHzHH3kiL0MfO9G2f/aN3txx6x1+wjDRaHoALAA+f6pE6LNsAmn4Cw0HCDRmdBzl+10a6PcYYBAgxV9bsgGkcqrVOPzj6KbJKlYjJT4wvJyUdnb2hSyufn6F8k6L6OP6Jnj8i1Qq3Mimxe+NYvOXw4qqysTC2G5upELwdfntqqKQT2tx+wzwRrC8zkvTb7PYrBUtrXJwi8A82uiyXt0b59sSpcGBIqJdRIeYZDKQOr2P8MTjgRHIkw+cQWZ3V/D600j9KW6K+HWPO4LlwDaC+87V6C/2T3SYnMP51Kc6zvQRjviSmN7bDrAkOnKj/XFXh9Yyrwma3LIQUNMNYGRemDlxLWVREslbYCrpBA7AEcju0MwOIEVyg1w4jGdH+lN+6wk/dgTIJ4ADPdUe0U3t+zW6Ae+HmuQHxLuaazMsl4Gqo2060AgR4Dc4PQXNOb1KAM8N2gXZcGyukKBaBMSE2tHbzXSXF4P/QFmOinpDkjVYaLmBdk3FWFnR+zXljvF6Ifvg==,iv:oz1/36M1p0nbwhjXH5bLtm/5SUJOL0dkhhulJbE8jPQ=,tag:K9omn+uSAcyHH0SFonkhnQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:fDrdTbyPd95AFtnFgRkyZO9FPMkczbNz2kwtwzFyISdfRbuRN5PaaSEpycak13ddOuc9zWlDOq/t+75Nvy0fZgVXqNADbftvZ/QS1xzpBJFIfcpxGkbTrJN/OG1kg/Ngm62/rlq3k27S9SQKRgRjXFzjfcmA+Bp6dB5y87M1mkgFa/gA5cjuH/Nl4fjv7PmXgXidG2p1dXWHJpur2bLV61EJSUHgaZ/HCHnq,iv:w6mGocGLRovGw79JVCjSRrK6pYvuIJi+zFJmkvBJIcY=,tag:GFhOl4DyxbLQOCDQ9YrNDQ==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWndGZlZScUVYRVkzQm5Z
            VlZCcWpubDZLRHVjcHlZWU80RGMvQkFMdmhBClc0RWl6NktCTDBmVzlmcG9vZDFz
            UlpVOXR1OExmRTU5UnJHUy81cWZJZEEKLS0tIEtKNmdMdmU4ejVYQkZPdzJXK3pv
            YnZySCtiYWI1T0Z3VDhUcm4xblNYalEKR6UUGvG+RkmQgJ+X0sJ2HhbC6c4Y6LAp
            HBsR/YVHq08QqCUi2Cpf271WSEcyLbqTYgJTaYXxJ85UrmCfrLsP8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T09:06:47Z"
    mac: ENC[AES256_GCM,data:7zum+DnYqz2LQrLFFDc14fAVwZ2D094HIC0zbZfJ8zWKox/piK7oP9L9HCjr+MwpFss3NPXJe602GNm0Zs1GNqZMX7yiz1UU9pHr0dE/bk3uwYLMyiz/3uYPLWbMK+xUhZf4A81CbmgmULHnw7SaUzPzrI2kFZYdgb5c7UnPYyM=,iv:vgg9ZgxwmHBZ0gsr1hmsOJo9G97+lV4BwqTS1OH2QXs=,tag:3oZteYgEYkYayFiQbQ2HPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
