apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nzwsBsY=,iv:Ym1V7SRs0huArv1QE8sPB7WOXrq5/ALyGVRdxaVMrx0=,tag:3a89L1sjjwEQtdFgleasEQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:l/TkdBfUJBIjHb/VgSMOCOk=,iv:LQNgE6Y5iJvbVn1HfcXsEwtk4Jih4zpS6pFj3NpCj9o=,tag:MqufRHimWEMl4/oHlaGDwA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:/gYuzWU9Gtd9qNyTiqMUeeqNUywmO4ULTFWWdaTaAwYtkoRxlHJeozxWC1zPfWCjQDwbVSwJkd0L4T9eZtinzeHPGw==,iv:gJ8CoDghcU3BlSjprzwPLjHUH7QOoPyjg7JaU4ttPnY=,tag:Sbndk88153T60bC6rgzQig==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:LrpVeDcCk4mDrXA4HPGKNxRg/clM1dmG5+fyIw1LLKGBqelj/1AG0+koXZRv6kBoGVdokGpPsBVu0j1U,iv:oMrrcx6Ut9EudOnmJjH0098C6qi89emGUA6RDUQ7Vkk=,tag:bxvvqcT9y6Gykon3YsakHw==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:qAJkkLNGGuHMqW7KCF2Knbju5WRI9GlEby4EkeKnIZI15mcffXRd2yuHJqvgdHcwhLKT92GVAbeB3T5/Ru8/Jw==,iv:ZIV4hsqoKPs4aAfy4u373ETV2R93N+rpH4xJyeVOH1g=,tag:6/fSSSHzGwSjhFoZg+3pcA==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:KTxNRTdni5LLx22b6aA4B1WXrj0wIzpn/6ylaTfsBh6gTu0NroJiI+hH5jReazGH,iv:iDa3p9mOwcRXJ5A54D8wJG+Y/fLOafYWJhGXAUT+lb8=,tag:h4CrSjRQd5vL12SO8SfjJA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:LjdOd1Rv,iv:rWdO9jo80IPipsw4Hov0JgHEHtJZMMXdfgamXczE1hs=,tag:ZWCmI7tqgAxUAdOLY6a6qQ==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:hOaJlk7/NEo+GVyTea8=,iv:WJnY9sOLa/NvRdVM/tMl3IwmXkDQ74gmjQXGIRm2LkQ=,tag:A/7AOh1vj/AAMQ6V8iwfBA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:dOFd0au5,iv:IzkcjOXe7ms0byStla/pTzQqt39f2yv2KKfh1q9PU9Y=,tag:0wfF5owt0uumu3zlwfhFUQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:INS0ZpovUdRBBQIMafDr/DzYmNDM9w5CzwDuyJLCxQlban9OVm4q/Yeik+NS5ab+IqF022nYx3ldnAX0hjf//NHWfXoGkEvB/INjI2mPEMRje0YomTj8CP2o/6BSLW7tS3dzaK4G0cOgQ/H9lhhIxcGyRpQ/LrmHb0hbtm4ts/jyFInQmgJgUDAh9bqvZLqt8tbWTQjcnVvLLPvrOQ3d2jwRDm0aXmEcMnatNbsLpVCPnD3M67Yg,iv:cZaPrBSmbQpJy8aMhdpHFSnPYkIu11Ao8VsgHCXMmX0=,tag:k69MSUQuIhmzqxWlR7PTTg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:4JwILflUjyDa,iv:4SiCXGHNvv9jnh74ChBIYo9+3WU4f+KSIZIZeb3qUuc=,tag:DRlEltAxXyrzDPsvh7gKYQ==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:Fuxpz+VrtEvryBh+uzrHoag4G+DxGEVBOYsT7lTOfHKa4X0wDJ7cT7ZKOgYflA==,iv:qxe5PY9Ib7O/FysDilbQJuk5joa1Kbzfyf0Wsa7FksA=,tag:ca1Sx/yuFjchWWSHMrdJ9g==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:dwGr1x7304xNPg5WClI=,iv:rj6p/gz5cTzEtTYoDXuygbdome+o5prnb3MAzOvjyqw=,tag:VBMF237EahRFe/OE9TTZWA==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:JOOKK3nUdrKWYXnKZxk5RbQWyLiEfWCLBnH5Moh4ZhUfJvTrumn9pg==,iv:/mnHVdBEYQ8OqDFXggm4EhDOQe2qUWY7zmKoV0EbuHw=,tag:h/nr/RiMNIkCMSAg/9Bq1A==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:As6V+HTCbVubN/lF+4BLJvw=,iv:jkp0wsz75c5EdsqbifSAA1HzV3+OxRD+Xn/LhKtvBTE=,tag:DKDUrXD/t+b2PveUGZqulg==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:SZ2PIv8N7HMsBrD6mykJQi7JgJu120JeCz1ZWwsDXla6Aqd7MIx6X+hu+C2q9e/KGewZ5bQ+El1AnuG3gBIAfQ==,iv:PCN0oeMW9sn8/GGLmUq+wOABu5hgd4v9izko/S0ga5U=,tag:nBOlYZ1WxauSfuVknlFy9g==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:sNedyLIP9ZI=,iv:6SGYoh8VD/SI/33d0dK+A7eVKc0Oapz7XL4bADRfCcA=,tag:bUQmbGKxHY0Td7LPV5NxxQ==,type:str]
    password: ENC[AES256_GCM,data:nIZK1SQrdjkfXG5htiGBuLQJN3sCtSFOG+wqwrJHZ+Rph7ZLcef/SH2hrVHrpiiR1INL0c5CX+vV68MNrq8Aiw==,iv:DreZWJ/bhxfeDLVvnOSr1oHSaM3ht4aYaaU0c9Rm8cE=,tag:6g8oy8NwEPpbBn3CVVom5A==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:+Eed1/VaauCjN9WVdEFjUltqc867Qva6X7rGWYgFAAE=,iv:OURu+/+URWcMX39sbbb2IitNGrInS5Ez0MPApqQnzes=,tag:VttqYqidipINz6/q8chMRw==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    PG_USER: ENC[AES256_GCM,data:oyZFRg==,iv:dKIOovkob/zSAKxT1XgJeQvYTV20umTSsRKDleC6sFo=,tag:yOpmR2R5uCcjA76HjQp5ug==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:ZOTwlc3RoIBvbhNv/CTZcDncKBfIRerCSRh1I3XLUeNY7/2FnXZJT8R+5b+Trq4bIWdCNwdw5OqIG+cZyOkG1RpE,iv:/S9Q0JtNGN9rr6Ts5ELT+Z5TrLp+TCbN7FhPa7vNIh0=,tag:CWE+SIbpx7fpdJ4Jt2zMoA==,type:str]
    SCANNER_APIKEY: ENC[AES256_GCM,data:JdpAO39KxYPLaAU4y0V/PZrnj8gNkB6YFQCfoP80Z7TbZViHq/Y9LRp8lRATlH5c27xgebhjcYwom3+BY8BkoQ==,iv:7jpEKP9iHO32Bw7rzZImHz3mUAw2DuLuZOC+WgywtF8=,tag:rOZaUC5bSLDhhitgXRLqPw==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:/oljO95uTN9s3dq+ks1ACtOeSAQDsdSTANjYjc6EWxngoQB6f/gilGz3gxf4sOsCC90W5BaBJtZhihtKrOJd3hgIZVotQnOZG/kvPRqZixZIhVjsrYyl5b9AOJMb37XNK7hA4Vt0IlKIaoj0D8X5slxB7IVs7AHSjMuig08KEGN38LajXX1xpv+Nt8IYPwAf52YiRQjy36fvMBp4zo9nD8a2b46EH7RdSoQx+tCx3Mt/Leti521ZmaJZe5hmtv/A3SOApo/rTjqcCC/yiCcj22yB4AvRiyUW7FFTp/NR8rzP3hJFEQrUJ07ktQSFhR69uP4piHXbNOgtfwDy,iv:O3U8ZV3gbKoLsbx/WOwwuqtS0WW2HQEHFDCJ5MAc0ZM=,tag:2b6yiPG7L7PUrQSfa4E6Ww==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UPuKgq4a578OdAyZZSywV8aVnGB28cRwzl+Dz5c1ZIUentDTABv+X8wBWrOD6Cq0zhdWLzk7f5mZajNaiIPMCB0mJ6HYMYcd9y8BtrSEobKSCveMC9iDRDPr1GBL6pKy5GsDl2jTOCdXxaJN3IeyG8El1fZXLboZqXba5uAEMaBdBUoQAexu+jjeoBkrqMBtgAaXlKCd52euLi/pbgMB/YqAqcF6usJx9FfqcvLf88KcCWMYb/ckTBzdainJR84PCIrgGKrsKQiMgtJDsoiXJXePFxO3Hh6uOEAq1jcs/RQI3GfTlu9YGCuP+CffEEjMtLQ1iRTR10b511ZC79e1pHVcw83Ped/IARZdbHcS1NVjhoxpvqZIV2X3aGZg20oYzFX4NWn+zSfDP5qxATA3NSc9GbKyQbSW1zhccLX38tiFye/We3gxKB3p6sKi8WHKHI3LwLAjGTNYOm2DQOYFdS2E7dc1A5OxlrR6HQ0ZYshSiGI97RgTPXnPUddi99oP+O6nhrzjnDMVKU17XYouwh7CFMOQTChnh3CavVh6AA+uWHjsnxYXKevDrJs/fJuSnh6tnWh6xH6MxWiw6ZYj7jBkJB2mVO9uGOeG3J3dqU2Xg1RYg58GmKubKLsPuJg4OSzRFeAztR2kS897ajHpVzVza10vvuiQr4jiUuosVfqF4gyiXc4J1UVXfKeQtWIQDRj805TfEq0FXfB4+2ubX09Ctq4hlJ2Kep//KA6hZio6r+Rdy56P3Zu7f7enRpZir/vknSZwhPhcUi9Oa3M+PaeC/yBnnugGhIdBSNZrSq3+VeF9UT6gYRgiNSi28Y2DTNGlmuAYuOqyfXwlePejzqhKGjd04Hdk5mO0QrGByJyhWw/+Zh/KIWTNQ7RNRzzLAtxvOuqnPHCqWQfcaPn1llnhYumivhIU9lkvbgKYGk0V7D2KEQJn5jo/pC7+Ap5uYFKMDP1eyjpW+Qk0ktOjwvwEpWVoICDZ8e4iQa+NFtPZ5lrbfDppz/Vf9DgW2My78NaT0ma7pheysZeWme/ASBxPPHJ0ZjhrFLNcNPFsqYq6EDvX4uRwjvm28YBwikll/aou8eI8rAJymiLFqGPoS+okF/OOXzB2RtQHsd/u9a721bYvjqgfPxF2H6xUxm4VgS9gHk9Iln1cBcdHJrAjpqJ5Y+vDy9BI81qirXnEmp5jAhcflMyn6JLnggRqF+DFT2UbD7mqaKJIMPLOjdVrcWOQskaVOSS4MAwQuIPUBYOkwqH1I+KvKx+Vcy2F0p4ksZK77FaD19KFprYBICNuMcr2A94OTXaBarpzXUGvIMjyujSZH4PskOeguiCktphKXnPl/wQkiCDirzIczvyEbMRQ6D39XggR3y9ZsIblQQPaJply0Y17BmXLDA3pQ4a3uunNRc6yTjLSgEKrSFQCyVn1v99xFRuumoSEI7qfxnJkY8NPGKY7xt9hn1f0bG5MgKZNfJtuvL7z5KH89WeeuTPlpsn0iLvuMJaNxuoodMu04Hb13RgG78a1bZ6yfXkjoJbJ05l1wUItwl3PzjYwrAs0mUAiiAYNIJPLCoZPhjLlKqAWrvOAZVDeDxyJtrqU4EoyGXdQ3B3GoKio3hXULQqPPa9Mrxi1EqUr2mySfDWpFosry+8Y8tCrcX8wv+l55w+CzPU9NbPIW1cWgVa4AzSDc8eWGTvONfQLnZhwVEM0gR3Y8e0k+kNaZ+/PsFMzqcKS4zrGNVYfx4L6kMtp0lNXK+imv2m7CerUIyiVluaKmB3FQfqv0pOq8lA/8wN4Eg8m+P02fpadQ+59wfkrDgjoAzTNIZCm0ZxrSB5ZQ+RLRcI7sp7Ork/01DNWeSY7O/uYDwxsg1xFsk5bvM7qpQ2MYv6sUEydEo9Z5RJec9ZZ6qmKtc78s3a5YeKqCR25BPFpQletrLfTPhCQuZKd6O1Viximt+TDy31lf44wIpyw5uwBGx7w5wLXEun3RydXiKH6y5eR1HSdk9UM9nDf8oae1NLDXifPRMdwm6JmtVtm/ncbDLzXzz7a2z47fYBJ2Jawu8sXpeR2jp7SBUPlRMz9FRTia6W58by2QScB0kviLW6tfmBZsvUD8GuEplnr3DulhoKz2E+qNvQ17NWk6RrOM/5O1oCwA/dDy2G7vqOBE26mv9mxNfxFEh9GiWSlOAWpJe5glEBYXdrP1mrqJ81nq5Hd4bKW+/WI2wWM5meWK8pE8M81/gLjcpoS5WDdsSO5M6QdJbL4GiV++gZDP3lw7iFeYiw5AJbfxjDxdqF7LxfjAZkfIuTHUTjL3DuXgE54JWeBdB57nWajUPEOtRChXzkcQmRPvWefV98f6cieyL2vyXzdw68UowHbJLJtJNfk5qVVpKwBVIQYPWQRxmzox8v/ZaZO9EHCQZrkSnHMjd+AQY+6jCe8bbguru90lB81dfTi/HCRcVKX9f/BdxZFZBRUY+Rd2C/8tH0SF4nMYWPnv/9hHm22APi33TSpyGcwjoGjlpCt/XM4gSclSC+uEG22EXMRyAKeh48j6e+Me0Czb8lWW3Tvn7CRH8oWJAd2yOScLdgf7mAWtXxd1z4xWSw5I9fUB+jm+Fl9u3T38cdyue53Klbotn5HfjIcIJav2TBFXo/+tmMpE9ATLLol7vCCGdxQrVUi7zBEfVkHlqkGCYClwldlrsIlRt4x6Ty/7khZPuEsggWnS2GINCQmhg1F9Tb6YwcVWD5iboDXjqs3MmKdODJ62EWh7by8EsBZJzLsnbcqVdma4XnOZ8gLl2Mo6QpatMcvrwxOl4ElPKf0Rz2L2lXQ5BiZFRMOFv8k1U7deJhE5kltk3bp/NRIo5F2zWgIME4KKgjQC0qMh3ujR9X9cWrOP2ssoF2K4E5SNDySeqHHzBwBWMBQ1wyrwrtoOQlkAcIHD7GHgjxfIhR2JcxUGQqsROH4usOHvnv/V+qb6Ld+6k4Grh85sYG+M7aZJsJkRWOBFmfcLgWRoJUftjXPuuAKe2SRF45WgFpV9kn6A9ZTKBAqaxI/zId2FIAAAMmzTvXU5yMn8jf4ZuKghWei4bXh+RpxL2toU0EW/XaxybYtiMq/VeWD24hsJLTf4ZM7+bW1xcDEkmTeG144tKZKNDhooYYdWYxrwOjETmXSv1RG0N9g3y00w+D3a8PVVZmPu9/dFW003lWMl/rdTP/q75S8APcUxcBXzwkvWmSu0fUQvSYMhJTrIsnewnu1+yhk4vp1eFSIW5+E1JRlOBYOfltBJnRODB7Ey1pKDO5wmHsZ4Vfw1LrB7eP2WxXCxzKFlbkXmD1HR29qlDb3AdYozOCD36Gz5nqtJL+R0D+sr4kaVSNyX1usOjMmkDQunUBetTCTGL8Cevq36xyG9ECp6var7GixCRuim6n6jqWPQfSr2wotxfpwA6bNVBmapM+pC5S4rFTIadyqapAT6pBXet6ZCGlnqAeMV4MrZ0zTv/ECjw==,iv:M2x1YPNDxfvZcAAoowud6btWKeuHqH0QOo16wM5DkAg=,tag:LgMeAVXwcouXLmXkLwlrwQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:WZB9XS5DnfXCbV4s4f48CByAbSKBr6tuB56IS/ayT7bvBm8tLNWskDNMYLzbH1oFolINJNG7nVG5DRwaQyZIQw/8YAHVreCxflQM+KZRACOPBwnNm0c/CaOrlbHfEQzoDVuS1/2FqlHLSaECSKt+xCNj1CVvGNNBII6L7ICNuRNM6Pe0+FEkvA73BU3fLv/n4dcMcAaorHfVfU2nZcgYhjemd8mrU00puD/rnGo49e4+FcSedYu/6G5j9OlAdPIG3ZVr/YnvwzPIaJxrGm8+6YNl0h+TvGqLLvNVWXjUsDiKHEvPyPPGGCaTWbgyVcqCtvNOc3dRR4BcIj/to3k/RyjcLcW1TsVKvK75H75nwmoqUtynBLMMxg3q7azdUMuaYpqDIO0spawnULHLOJKETqwUwTEamW9Y1Zrn3MdrStacTljXrd7GSzSPnUDGVZ2X1U9c89OKPARDufkQfsWSBKSMbrR1S+8/HYLGix0RHjKeeGgko20tYLKmPJFX5fA7F0DOJ9YkSjs2zHzrB7tkGIUdT+iii8A0jUJcRjARPqUpWonyPSIjoGpFfAh0pPs5SNfH5+4niSQ7qJEPI0tkQ7+cwqvQQi/pltJz0GTl/D8S1dxGOLfGFmggHzt4X2nZumbimHSolYsvvr6R0eVTG97DOm+ux0Jzv7DNUiquE0l+ieVvD4+U9UcGlJlHgBq3Ana5fhgp49Qc9A0t3esKlkH/mWMXNcncTA==,iv:SylhiGz1Yo3La5jQZdxl8dFdmQ/Q0KkS3pTisou+F6I=,tag:x4HfGVex/QNsM2Lb4/hCuw==,type:str]
    known_hosts: ENC[AES256_GCM,data:FQZQcorQtefz81Brg/0GYQ02A05vTL/cUoM2EAb46ZuTbrMjqELs6RV9cSINze0qbJPZBew87ecCXqCaem06bqr8BkytH5b9NoXTZpvc4rSezY9LEDDbUGmCvVQ1SX4Ia/VL0XsFBgzlTUTaXGxBFYODccK4NERU4vEyvrxi9ITJW6cL3oy0OWgXdug7F1U8hGukCrP/L9Ll20liWCwyN2uFfid9Eq4p4HSa,iv:5QkPb4dGdExw9qrtIs6QFWEHz2LsbTlME4iKoFm0zUk=,tag:4YoX/EIoftG4d0mfhqrDAA==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSlc1Q3I5cTZmMUNudXVm
            ZXZwVTA3eG9ETW1hQyt3dlNNdTZiNUFET0NnCjFISWo2YlhsRE5DWEJzWlkwWUUz
            RUU1RkI2M2NyVVR2NS9wR3pPWHk5SzQKLS0tIGZMbjgrUzY4eU01WjJ6Szd1eDdv
            bWhUMkRBS1dmUitLSVNieGk1RTZzLzgKiGDMfee0NQguKDUtynU+/bHP8wQqdgAv
            Y19unVt2OC7I/0Gf+YfLsoHLi1x0jG0t72rO7YWyItSwvALcgrFHYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T21:40:22Z"
    mac: ENC[AES256_GCM,data:nHavdBi/nJAqmBRPeU+j90HBvUIp8C/14EwLmLyehAqgpLp49QRyKGCH65qPmNCHl+aZ9ZJop8ExxN9TlYFgDvHC8sfGI4AUqBqlttVokBsDyoE1s0aY8P/Ja9YWEuuSx1yhcY5tGQb3Kt7e50TvT/Ru8f/pfEZBzkiwpVgxwJI=,iv:lkak7g7sFMRQd590zsqu9lB1NZMOEGPoVlI0b2VC4oc=,tag:YkTQmm7rCoSdbB4PCOmNsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
