apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PN3mVik=,iv:b+I0XQzg4eMOXLPeiOHOxcy3uwF6N15KAoxUrSXJU/Y=,tag:s9QbUNSPD64d4+hIcNJmPQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:PE51kdseaHbh78K/w81Ae7Y=,iv:pR9ftX8O4IIau2ERz8iMVKcn2L7JEeP+7LsHFWgo/70=,tag:iYu9uwXUPESo3h0C+xAizA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:wbjEa4koRk88FYnss5MqBfG+TElRmnHftGMzEH5atQLZ7My1qCnv9DYkhX6l4czLP6EMyO5IcKgw7DupeSje2rTLuA==,iv:95jMW2wabDF9X1rL18jqYXucRAcv/qkPGkc48A+IdP8=,tag:RKAVYHfK3DjWjMH/OHTBbg==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:E40atNNE3Y9E5ymOGKUO+yk2zynZgzYZk9xX87scZ2Oh3Pqej9utG7fgMctfB5R3Oo4bpoohcAqiFVsI,iv:VOM0p7X+duxyJCQJ7jaBzpFuwT7tsls32xKo3K8G4ys=,tag:WTLzHkMK1W46UWtuJONQAg==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:BQ4tDvZ2hV+1JzOAg85k7kEXLzxkbmte8tZDgTWD9yDhUAkA22Wd1Xxm5Z6/RDLLlzHl/rVYeNX6StrewqenmA==,iv:G8yKm7fbGOq3pBAWKqI6fbul1XO2d9xsbu8+Wzt0Yxc=,tag:ytteD69bapMQDTKPYX6AbQ==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:lOzOGieDYdVrrZKM4nHGnMK7Ug8WMZbc6YIaWUQGhONOqbGb6G/YC2Q+x/zpBM0e,iv:uthVbuFt/O+X0nsfIIeJE7CQfavYltSADBLs2r9Guc8=,tag:iwEYcQP7wFA9HTsjuOwHWw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:hlpWKsnc,iv:Nb1IVJ33qWQmilT1hDR1Xz7yBO4BKzqXEj4iEJpeSIk=,tag:2skSs9dnd+AoOE4zZ8G91A==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:eIiad/F2AYpUULQSA8M=,iv:/hk171gOd1gZCM7OIOWRXsfz+r1+fxzGJB4YLNHnw/8=,tag:sRWGmzzDozPraz/YEtPLJQ==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:iNgdoSqa,iv:A6D75y5VNvh/N6c/iOXT5iR+TGNIhen2BhUrTtOj50E=,tag:36rnGAYrNoLbe2yID28MpA==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:G0GBUU/skdmwBj2kOjIerZhMCzMht0348OMiWJrr8H+NAFinSR561GH13NX1tPryEzgrsn2qFjyksO95o9LaoZ8QVF1QaDW0gHTm0FuFaFaAcj4xC4n1X0kmxukdBoU6s4BwO8W5gxSooOJzx0HnK0qif3Hb2GkYuY6lrxTB49qI/E8exhNR2Q+3Z0ERcXYhJMAvA6xQIGcilfkUjgYgJyftUc6G59s1OjDx9B0zms/OPCbn2+Ol,iv:WXtfjF37VHUegBx/0//ZabmxXAu4c54C4T2sTaXfIiU=,tag:F453TT+t2yQ9EnX+UvJ7gg==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:0B2jNyozon0z,iv:mPihF52fwGyKk4pQegecdCX+UGPGT+8hqy9y6qT/cWg=,tag:vIGTIdEhGsvGTTk2yxFodQ==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:JoxoHzWwy8YxbvJo4YLwiFRcGfGiGPYCKMCg434npzJi4ZOk8zMTpTWBYkBUAw==,iv:tcWIsi2V2ONb3q+ldLvTpeSI2TKQ4UC4QqYspD2HjTU=,tag:cmv0I6AE1qSzO12p5JHgGg==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:3/B+edVi9RRTRKOHdmM=,iv:rmAdJYC8GridF0Mjft3cpnXnGW8WeI/7U3rHQjBXSK8=,tag:J9P0y+QRW9NFOuIa/HkNXg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:WFxcI9yLaWND4zN0XgXDTVZOeqbjSTxXF12U8s7gpiFWigUAE1iYDw==,iv:s7cQHBEUkYxFmQBJ/I1yW19YhH6xZZnAxh5bfNIitN8=,tag:5CgOj6ZOKscXpWJFhyDWXA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:JtpZ73XjKRTjTnhwMhYbPIc=,iv:0KxYucFcYWxZ4cBZmFy5HfNxKzFsrOkuFqQ9GbaLPmA=,tag:xitWlq5p4R4EVTvvC5dKlg==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:UzyNTNohdyFsh4K3rlM6VlhAX64/hbO8dZjdlvrd0hUIhUrzh0OimMimSGaAUA5S5V3pLAN3XwOMhJ5RJMB7rA==,iv:NzCIMzdHewj3GWO86yewS+qYuA2rX3BHhGUmfdGFVFo=,tag:0Yjs3hDGOw4Ar2k/qTfTkQ==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:Y6yv+F9qffw=,iv:W4bU0DvwjEXHGOOidQ/rfdBCG/d+Hu2FkR+AjgY6GvQ=,tag:X83ein9C2uCCXH4uCmfJ4A==,type:str]
    password: ENC[AES256_GCM,data:/nd0o0upHV+00JNZg/VDqjpU+8k+KUwlOwQ5RFyMA69ChtKC8IgteHPAfLrCVLT/Mxy44ap0oFmiEyorcsXBFw==,iv:I5gw4jX3s2WQp+J5D5OxSezy6aJZI0NX3YHfOaLSXtc=,tag:cIwt0gqSQIxzHhuRc7SOxQ==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
stringData:
    TMDB_API_KEY: ENC[AES256_GCM,data:uFu3CHLzKat/rs+NvHSfrhBfYQEr0aoB4kpxe4MErYHKPwHin9UZhJ8CyuS16JHwOqcZ3DMMZ346gHyMSexn+8zFvqt1ITouA6AswWZIV+YaT+8qU1fa3fXFUeSp1q3v2XvjAgbf1cVBNnVwSgp0n1S1hvbq4STHO7yvAHiCdw2ZrrnruH3dxc/fJAJzidc1hNcFlfk/PuuwZucRpNXAN+h4vLuVmCLfujk5sAVUfjsibH8BTq0cClB8XzpYK/Q7eAbAfIMpqQjzotbQH9z4lKu5AKfAoYcxkgbqZZKF6CYWMbcv5mn8mPwbY/64Zbs=,iv:SWbqh4occwOmfJH9va+ZQccGxCKYSO/gcxpS6Q+kDKs=,tag:VcXYaCZLi1uJVU9slc6QIA==,type:str]
    TVDB_API_KEY: ""
    TVDB_PIN: ""
    SCANNER_APIKEY: ENC[AES256_GCM,data:DuHv+fxyV5ascRI6bgqjF8GXR1E8s4pn417t47R0OEHDSBwWc0qZjVDsIxBYbodYSMESDNvRDF1Ruv8bmEIj3A==,iv:sePI2Zh8W8iBlmboGkqtoGYNni4SXZOprsd26emT17Y=,tag:Ssa5ZlFXjJnUahDgACUw6g==,type:str]
    PG_USER: ENC[AES256_GCM,data:PW3Q5g==,iv:1HFP5pxttip24+V2bhwdyEnVJ38rH4Du8ckBri4oUlw=,tag:Rc/gIYjWmwyafUbQ8nX0Lg==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:IebPLJrhFE21l8u7M5vcIM11dje5F4LompFu+6H0eQV1RDrgHIcddTT21K8uj4vqVZeL8W6p2/rqNMALCSjwQbQ1,iv:tKFskI9MwNJ2/qrY7OBcjitUVHijXHOp+LEjqnZO5a8=,tag:S95MQp/LmWkik3VYMjJ0zQ==,type:str]
    PTE_RSS: ENC[AES256_GCM,data:Y0FNRwRiOefl8F0sL+x/MinmRpr6+vIzHoN11PLthcrqWxs4eZSo1ZFadU031TVO/BIrUV70nRvYPeQZnOkK0+7MCWvORm7KzA==,iv:vhei+9XI5WeYAtc/oVBERZYpLyDrW75b1ecGSCayGSw=,tag:a1x7qR4iH94hoX+HultZUw==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:lK7QYxTd43gpgz6IRg1riirj8ggzdQ2zPW3RLE28Cp9WpKKyU9kZnKNYqDBVYcse+0aK9NL3LrbujfcfvoHCyqGhvCgzZ12CVJpu57EP0H3sbC7yhoE0xwmTQGy5nZGuphE9KJsSYRsDrUdd98iDEBPw/Kpdk8qTvB7x64U=,iv:v/wkFml8JqnW39XE1X1A81CQWqVWYZB4NynClyaFKp0=,tag:AmJwR0X0PijLjyo/fed7nA==,type:str]
kind: Secret
metadata:
    name: kyoo
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:28kR6ETTxfDIR5QhSz0w77HdTmqWoqn7XI5ozf8PJH4qgXDW/WWEt+OaedWnnyQhduI0pvpjHtg/YnImWrIW9d/erJdSZILJ7wRZ3pM9yTuF7Pq0Eum7PzfNH15PMlAVCqccOkQjsWrB5LqboYFBvvdb6aPeLzkTXzbbNJayFqBNXDsNOdaVNo0QQrxc69OBSxyZ7uK1oljLmw7mxwDhCfmJb270sFfF+MOxotgA8Afdjq8tqJmm2VVxXAeUPMjXuSHAk0JM8qSgDMvgJJdjrks0WQT/jmafVxSZ0QDdFodAq6ZEAtflgo0SWNOee9P9xyWaDj8F+X1Pq9yJ,iv:UtY8JWZi5sA1HGZE8+z4SRO71e4KyQKvfzpz5pcGGpo=,tag:/mLK4wxDF/k/ycasV8ZqAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0ET5uP4ic8YCtFeJXW36vyEdmohrkxmVLhV7UPUcBga1g9NxLUJ/qerpWeR7Z0haE17wOa6AO9vuaWkVs81+OHdjFNZYaYlxqylODCWXTUpbuZ9ijcxZyXwF96LXSZKFEOmyBO67/kWnEZQpRvflvqlNQIJWWldISkYnzOEyBniWOhnEFw80VfdEc57PM57Q8aJQno7ImVDYAkAz5cdMCdFh7hZ2f2G6I+kHNmj1PAE6Ekj/6tJhnC/fdCi12l/6EbCsVX5GQaXSveIexooJnrmgUAMC0OWTGwqDujCORR9a442xJlzNBly1SbZPwz3KNT5c8jyQ70FMS1Awaw5Ofs0aUfQhLbxNgbcBHq89YqEU+VFSAUBCGpde/WAdwI47atAScHQ/W4evn32vJEqMD0sTlLodJ1kUGEtrAlzxodJsSM1eLhZvMGxMQ+X9+7TLY99iQvXBrhJKqVlfHFym77rLp0xNMco4iYm+SQlVlgNnUTZGV1rqC5k3pn04+y0TZ8WIfk7OcgRW/N7r0gWU7PKMdct41IkrlxM+BTrl77xJHmEc4PFT3U/aTnFgl2Qv64q/kOLCvdKwOVxpSdUFbo4X1gXLovQiaSTAk9G6X7e11eG+XvrKwwuCAUBZ002eVNRaJ6CigtrhT0iMpOtPcAoWciZK8xvFahDn/JT3WjuYj1hbdhelUXLZKLkVVhurdKZmsZRkKWW8Gw8w9b4HjTuNuHvXqkJ0Aw8bzigQ0dj2hlHDQ9Fy8/6CVt2+DFRT+Y7+uDz0qrDMEr1/v+fO258tZklVv7fctiM1pLCwg5UgYtbpFi8sjOV11ZPJqjKw0r9ZUfgI6RC7HKQHo74FaRFYFEWUBIKJvWFiKdjuiFXVdwcsaF1hwSPS382loRNzEcaGeUBSsc9VZOjWzsib4rK3OSckzyzhjgiFlsonKbRIKa6TbyUPE8LqflATAkrSTUljNF5Cbvep2vk8kmI7SRpafawwXe8LQO06AMMQtBFRWenADGZBgTBEWdzNMSJztQ/wRO7B3yEYlmqdi2IGimVJLfdPLIGP1T69GJs4RlYTbu+NFxO5Mua0zfsf/Fc3FPzks6GBGFcBM41/0gDQLa02P3a6w/OVE5yGF+usxCFfcTOf/bz55OROaLQG4WMG+8/ygxWg2sTmPGYA/WEL0yo8ZMKmD0XlhfTRBg2vQwcB28+z+SmajOXpc48GWw0m0//pHMftcVtCEsmNBdofX/ESDLWxO7y+x5omgbIzZmztxrZQcSCX5EU7AQa6ti/+dpjIlyitft8UkLNvLxGCNZBnw+7qWE4EFsDsofrJ5aSqUvYyjb3Qc0Uc4L9EEwYewUBWEY8KUWltmttePHaRTKi9sByFVegJhdw+4Ji7//jSOKezOds5uzmOGDMzQgO4Ohe/Rhg/8NoWEVwEEuymx0fwBSsPC5xJuKN+vnUMjkjGMnf+b7HeKBOQK1Osf9sDLxuFBLE7hQvwSagFRN390pEud157Qe3GEwFZ2O9iVgVHI6Kmsesp2bcdF9u35s4rkjidWPJ97O8rVaqKWr1IV5OIJC2FosbI2lHr7uRzPLVfa/DH2CNTrNTwKrlX1bRaolQeUmwS25CPWHcHf6jZxpd1uEd7b2Vz5sl1kBBspEUNh5iiOUo7QkOJoNXG5JnSdHV4zqSdWZNYCVwLxmxQs4si40kZTq0j8MKrsDEzn7zALKgUqFBXDMAVZeKP60Ayh46yQx+qJhOGOqXgIqo3YTpPuKPmEhuQBDGd79Ns5JOVGHE9w6QFLAgFoTUDX+0zxfYzh4UNpC3MgWICgatS5XDi9yBldT74cOYNqmUsoZladXRVa/BP7uchX33A8O1pju2WCK4e3bVNpPjAPFnarcGDRNgik3w61+NHzJWWLd5QxgglapFLqh1jWQR2CJQWRV1DE0zpm+ZwqehiDAo9TFV1Oc5aKQ3nouZl/C2su3ycX4KwhzMSczEXaWPv9L2a6wwHOUQOukO6pxjzC9B8EiHEt3GmmedQ/hoN8TE52kXZta5PrGICIy5FaX5F6m0ChbMKNuWffD5nRLCK0IfWl1Q5NC61v0T5GC7B1xDxVv3LZvODgAnHIF2jFbhHZ/TJG5ltOY11P2Y+I9IYYxCabPUnV8XSb4mlgW5aKP4JH3DsJ711uKu+wqjA+TjYdVVQwMM4w2yGAWa5MGjA8G9vSkQccga1DF/dKm2PyR4grfUjXj21+M8lgvYax4JJrTbvnhC7qLkn30PUgVZXTHQrg05XjtRVmgq2wdO1WXhW6qvufHRCsCDYmvN8CmzuT+pENg9UXIvicdgrfa2CgQNOb1RVejQUV8egSxHzgy/VxBWcrymJneKvA1eENS/r5iZ0t9M16txhbXWUym5qFAVM84mELOvunETU10K1aE6yupajykjUnk7n9M7CS9XSql/sL+X0OTdhAKyt2j5Sr5M+7nIBfkEZYrUvo1Ny2VwHWsyf4mCkBUHYOgT1madqiFAzdXroOfn1sylpOYYLpEB4kX8XU/moJTaRGWzo2TDNE96Ua6Jl/8svmPhkqpi4JfjxR5rNKmCUQfL5u+2rbUVD3fGRv69GLokpM3kjrRU4WoLTv5BcCzxHl6s9LWagDWE0NAaBAa8om1EK12YSVQLb2H2nOIxnn/xnZwESfmhSdeqyTsN0q3Fi9XyqLRI4CQWfmn1CE3zDbkwmRGpS0MBh6Gs75PfO1URlt/s7JFvtEOl3/SZ5O2E9yCvCTuj/cZWRavoEmWBpYP9IQmrU7QsaGq/ZVKI/9m/C8+156W3RhWsPLrWqpRgrZuVb89DQPpUt4BkNXmj+kuplxKMav0D++Ww+UAWBAGy2YBRiWqGtY7yyumnVZvzqwFQd9a/H69aj5fXikgeYv77hJv8z5oS5xYRN+hkXl5oSVlZkkfchrRQGGbGjIonrFRrQkRiV2SVbgB51XcCqTCKMFfUx0cTAKacVtwKysQSQSHXIw2iMCvx5YpETn55BZ1rZF42YMkQpzlrEEf/ok5rnPa17dCzqjCc60c/EQlKlrIAzC4M2FjXFnsSn0ilPeJvE5RYiMceHisWBlqSeL5mWv9Q2NNqybuCGll1Qj9/rPgLaGbVT5eNKVW4NjQLe6QbkZWLi9yNtPbFeQokFYXIVWxykJawW48+85d3b7ZCpjXBmT/ab16rYYkiRzaw4sBBaY3yavt9v5UjtWnB2v99ijlhxh8urCI4GmXFgcKVOZA+kqrNH8fPSYJinpy++W5fNgZ4ELDipa7r4NRytFx8uFsrPA+cGgMmcfJH5QZ0Scwg14YC7Z+aZ0cMbVOjgHDE9ExtzUYE2U15xWoWUjpDj1lwkp1oTaDFMdD91k//ZHrokE0v97D5QNsz2K0OH91d/N6RUlKxvGneKj7A+pI8236ZAS2S9wjNGmS8mP+dr1Ywsm5f5E3dc+ryoFAXpr9dW9YkjBJW2JjXAkyNvEpM7+w==,iv:zai0f7149RJF2scNCOUqZHGx69mIOUttuiCk8fZakhA=,tag:+iVdfvocpgFEYdrBLygORw==,type:str]
    identity.pub: ENC[AES256_GCM,data:eDSqHH3s2bOq1biB75fXu18Hfn/8wrlmmYjQ4U4cXBTIgcYBd7Dlm4xoLhl9kxmPWj9CBbMD8YLurbHpeGl7Vb4e7/Qio7Rj8JqMdJhOBM3UMSb2NzpRD8VFCIYJpYS/dsLisf0CWhCwqZDyOkkeqYCrbOSr1ncb/gYdzHCw7F7zNhrjPX0JiCZTyJ9OEMBPTV2unlnSkKge0syV4tHvodNz9YSglMT+rUdlseZgnZLzUENwqrRw8HmnRkOEhseQ9FbV9CixaiZ7iZc4q8ecvSCflKdrAG9fYMac8aPeP2oZDh5R6HpzzhW4VEyk+3Y5C2r/rXJmDIJqI/couwIESEYB2GIFWcwZDaG/OFckOChq88NKKpVwfxzi0wLj/Xryof/1hMjaiHqY1qavRisJH17y1qyGKGfw/An2O+9+Lr91FsDpyTd66c9rBSBzJcDyxa3y+VkKOpeOJkKzvbSloCS2eo8m3f7JBHIhEIwbD9XS1SCO1K9dtVZGhnY5ezQhYxH+bxhDusW7lHtSk0CkqlojV2TwFybMsKe5m37e5MvDQHMK1elVjcTbxz/qUGHjgpIOe8b0FhRJY+/eC4gYmA81/qFZ2CkWYJWut0s715OQ+uJ4ZlpcNz5LHPxi7I0KeItESwegVh+veOcnVmPnzUlLDh7u7yVjzG48VrZQB7qzAE9xkqqrT8yHSjvwpSHrNVN8zyE+iERpD82bPGHHHFgHRgOe+rOEwg==,iv:Ze8o9FBvL0IZV2e6wKye+HV3OiINaVdr/op5aG44oF8=,tag:Pjw4JvsFavZ981z6zOPntA==,type:str]
    known_hosts: ENC[AES256_GCM,data:t/+/DXJKt+lld9aDzr1drx1TsKfvASbw/XLumN1rf1DCckoBNIKbY8TXvtxcBzJ67oH3wSnJ4Ptt+0gVY+3Wa5yOmCJUHZOXGu01eGZRpmQmHcHEFjcuRy2M9kKJVGkkCYaGi4WRAjwuSPsrg2BG6MEPLRx+NbWnapwbQNAGUG5t6mPoH7XxSlGA6Xgc8RtQowGBOlv910P24U/456OFweVxieEnid66faBr,iv:dSrNSZi2h1sLlkrd9SeRttdSAhO2usd8NEpEcRxeqyI=,tag:x0vxgkZAHd79VR7ZimOrxw==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYjIxYVVpSFpuRmZ5QTVC
            OTg1cVpHek9GWjVNSWpoY25VcENvSmNaR1M0Ci9rTGRGYkFIdm5CRzAxMUZoNVNF
            eHpQZVhkNEdLYnVkRjBGWGl5UXZPVmsKLS0tIFhRNU5uaHY5SVdJK1BtdDZxVDMz
            Vkh5SjJTdlljRlhpUktXMlU5cUJCT0UKA7V8uqNsSMvtomb8NZsEQ2gLAaaM/LFo
            5dZFPqpE3vGgAjWnWru4qgSYXUfeR9dZYr+891ADB1mv6jOfbV3VrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T16:45:30Z"
    mac: ENC[AES256_GCM,data:uHN7dFxt3j/AdfspuuaR1s9jP7hbzzGaZb8G9ohpeTh3AZyLm5d6FGSB24WC+TjKdiqRvHJxp9GiYICa0VZGTobCOdTx1uOdhUGOYvNADU7rxOsczejQpZF4qxEmWYsO5YvzwOBDQ4eLnGogqXwOErqBg/rET6HyTWIGew/iDUc=,iv:S+Q+Hm/suoJZQ4/jExMnvT8jhrAJXdHZyN+EWI4Rftc=,tag:akLkcMxuI1QT0KS2u6QCZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
