apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uIiCivg=,iv:a7ctQ5vZGKFJRjt/HFObp8v8SSq4ZGzeRPb8Ctnkr2E=,tag:yRQ5fNH2bDMU+6Kb6TuAjQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:FTxNri5pSHSynTUHYaXcOso=,iv:0rjkpdWplzuYjSZ2tEAbTMuMYgNVsue8sTEhnHSXtsg=,tag:wXvGbs+T4BGMDiFyBcS3RQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:xo1VkFV6K+rxCDM80N2POoetEaouohrv41pKQAONX7nmQ+Ny7zDiOjPMLRvAdDuYeFjO/pCBsvJcmC8h/4+L9OTh8w==,iv:Yb+jAVIjrYXU9iAvYdvkSwBKH8mtqkOoggNEfXLANog=,tag:eMVOntc8KHxiiEvPX7NIwQ==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:PWyioQox8Xe3n7exR5SYv1oMfN2CTL65GDO/SVw9QMsgbS79sP0sFEFoc+N/q9eVl8pXS+s6Bnm1pafp,iv:NUOE16k1M0bKBekG40t+p5Gif7hUl3Mt66aEyeA0e9M=,tag:E/6357IsWzbKlF3DfvVikw==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:KIRpZY8tJP6VKrTUKN71k9ZVnSl/RbwhvlIpfnkMpUWrt9BhcBeWuOD+iCiklftEwhgQGPWojTu4aIwuVZvqYw==,iv:pzvrtq1wR0psa6eEzqRo1SIYx5MYWqydamjZXotDJPs=,tag:8t97HP3uhSRl4LUm/7+1FQ==,type:str]
    KYOO_PG_PASSWORD: ENC[AES256_GCM,data:Z50Csl6c/VGKmBG1QjUTfSePvgs=,iv:0oz5t0YS8UdatzGO14IUmRuF0mB7E+TfOfaJ42wRerM=,tag:klc8ZevuwpYIArsC86K/sw==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:oH4gNcdShpWISjqStLS9pspAWcW+ahDfheFfoqN61oiQT5CJrV/a358K5x5v0O7a,iv:rN/8la5Eq4x9p+cn611bvvlWHXyFPejnK27aBDC43cg=,tag:IpLhsgblnkwz6rcGb/G5YA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:Z9R21+Oq,iv:jfM00Kt3qrchmpjPU7Gr6CAltTx48MnhMKfJMkGzvsE=,tag:YPN3Q1zbZhsoxoBxdVCNDw==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:c1Rgfw1vE/3b9fBoKnEJAfInP0egCpj+YfcT0GrLn3mCwZhuLUYW5i86SFpv+fnkT50=,iv:0hb+Lr9nYqIFpHeLYOSXoSgdQGh4/LBJwxZWEcUohu0=,tag:ZLrtIMgfLd9zudt5vt7tUg==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:cZvWJE3tevsdtjoJDHE=,iv:SKvJJmBdK5KrtEyHiWVDTFJM4xNQP4CeBPExqO5lOXA=,tag:8cJCZwdBgYdEBDp0/MvJrw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:aScux09x,iv:tyzXNJ91noxt6SC2cgNkPvfqkprbYJ1T8EMVMvWV6fA=,tag:vgi4J24Qj6L71gRyc9cIPw==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:FG/b9PzUmctnPkAX0wUK/nzblfMArGq9iWi6BZmHyERm8E0x+89vyFt2hX3lmqa2egSafzdadlyzQpIL0hv0MNU61HHxQOahLrlWAQDHWfcDodTLqpdmpqePdsksg1ZtxgCmCZG1ThDAoz4V2esDsvqoWu6KvDDrp1P8iNviINSLAzPo3jn9IrgFyhEI4lNPyJ0KQfTnEmmAjikBDKN6gvSr6hQQjLzFQ0iXiOkkrrL/e30UA5vD,iv:elhuoVnsG6VztnvEZ6B7sw6g00qmOhikkC+REPraXmM=,tag:9MY5V+giG2bAj0fqcoZXpw==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:byk6Pf+NZhfL,iv:7IMJk6wqhC08kiGG/UFCpsBP0O49GpNNdCbowLpgTOE=,tag:jLUjW/ezAB/vWmP+vpwFoQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:mS9HxXwuaqKJRBU2lPAYcQJ8l7UaI1uPhxrxZkuvIA5dRDcn613bxwDh0r7fmGSynPTKZPXJJQA=,iv:Mu5/qAvdNbXB6tMLs1tTAvJT/rgpbRFsI861piFQy40=,tag:1AhA9wWWxhgXRE8PCB8SGw==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:cAuj23Dz6bPVL1d8ObVcEom39/RGFsEGjoeJV03aO3hgNXi8UByAzuNVcro1Sw==,iv:UfdqyGOMwGejxZyKmGOgJpl+EMZl3ScyOQHBHO74ykk=,tag:fvOb0O7jr2F0EJCgrKiclw==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:HUTI2PgWwjya13+CpxM=,iv:P5saGJRztiJFVcPVWVJXLmQMu3bWyRjPZVO3DA7H4vI=,tag:JofDF4T7+PgDuOsaUnT9Gw==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:93cRNgK1,iv:WHytAYX2ayNMOGt7ULUZznIZx0iqFBx+1Y+qWrCKJTM=,tag:GaJgrNB8O2BX9j8WvHef+A==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:fVh58GXx1GyRjThviNePDqCH3cPW0e+2GoambsySLiaMmoZfBp++Ww==,iv:bfGdOGIsVAsXB9fEhOzxv3IVaqnHRvDy3Dtv0+DMSBg=,tag:jLqtbReX7yho+DSbFmvyzg==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:XrBctBSUEd1LKlvSc7VkwPw=,iv:s8XbtucdJ+wv/gsyraW1W6MCnG3CosAi+E/FlUkzwZ8=,tag:K15LcMZijW2Wcuom2KmshQ==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:U3ynBak8edGXQ8j9OSJF5M6FicSemVyRqAUrtfAkQhtmJ8HQOoi7kGLxv7fwC74S7H3oP6qos0IU0sMS4bGIOQ==,iv:r29iyjFlLnbSNUyYU0iybCcuG64edGQXF5iaEHBnZFc=,tag:e4aDvMD6se65C7zF/4vS4g==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:+nmMQvBNHUd47kbVb4Kr+6QwbUMJaXr0PJw/j5FlPIj30PR/O+Az7WbgVeWkv2f7tP4YvhPXVsk=,iv:VHpJRnWGf9Su/nICOgI/82tpXqHX/Le28jWrL3HOVv4=,tag:9LcoYUYyLWsLMMJTP6stWQ==,type:str]
kind: Secret
metadata:
    name: ai
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: selfhosted
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:Zpwm0FgZwB4=,iv:e0ejeNqbbGOXOCcNBqYrbMpnMCueIkgCrXiuX0/Dpsw=,tag:KimfZ9dDSkKxO6HfmGkPcg==,type:str]
    password: ENC[AES256_GCM,data:BCBTSNuudMYRicQ5NULshtvPUBGbfiyaoHYGokUf0JByhC5GMkD3pWRMwRJNT7jRn6BOlzzWqqQqq2D4JP5YnA==,iv:IjRSbUx3q+TAlpVwQ24wci7XEk/iUESOb6yxdYzDMG4=,tag:37LlQxxB0+5K/P5g0FjrVw==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:ch5N8p622jqzudwAwwdGd5Y7tIk=,iv:BSifaJ02bnIbJcDliA3Tqp5elJQdqlkty93jOs3wPPg=,tag:8Zd1lEdw9YGg6mX5VksicQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:6ST9hzHGT7X4uQXxjM365AgjS1m41VusoXiSIcxRmGd5kYazu1AY0A==,iv:4s5Vs7mGyYEmHAg14ziuOEpU77aCwQmbKuDWF+NfuDY=,tag:Tm3gyyCP0rlOdWBAX3xmAQ==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
stringData:
    KYOO_APIKEYS: ENC[AES256_GCM,data:pYAPnyETov1m6/q8e5uBbtXsFeLnG9eilj1uz2BrUcWfSekBTKfW6NCQBfryT8yD+Zw=,iv:D5ev+2ePeeAnBkGL6BTSq6P+ZPcYXDri8I785PbCAPw=,tag:bkFkDat4ppLtEgc1XI6K0g==,type:str]
    THEMOVIEDB_APIKEY: ENC[AES256_GCM,data:DlmAXukJcVIMNzE3yiU/SUW/G+04vfeti37oTx//Olw=,iv:/Fsbk4jKuNvant9lR9dDwlGsAQBw+D1m1gdnsPY07VU=,tag:b9G8TxtoNtq3r1P3eT4mzQ==,type:str]
    #ENC[AES256_GCM,data:frtksio=,iv:zSxhyILTVjanXL2z5mbd8DC9hnpmQituYhMsxSlvJPU=,tag:4Hp9cYzAn+hszHfJxFy13g==,type:comment]
    MEILI_HOST: ENC[AES256_GCM,data:w+knd73Tx8CG/H4A9wkutDUILrdz+J7CsHogAw==,iv:CVxEPGhuSZ9eSmWNVuIn4xIT9Cwn3dnSOCl6hAuXTSc=,tag:nfiklWA9octQfa7V3UOHAQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:i6z0RPrkDd3GxPvfPe6fToGbw14IeS8vw3AJ999Ziw2TFVwWXSqPT74vXLrodckaWWE=,iv:cl2VTSGkVgQHhVEm/zisFO+SDAYWtZ78y4eOUF4V90M=,tag:XarFfau11MWXEs5yM6Ue3Q==,type:str]
    #ENC[AES256_GCM,data:AJCTL1iwDZk=,iv:4CebesOsuf+0iW4vjsb5/ZGcZTYOOJlwdhh2/gOI544=,tag:+9bfwX7xdY4S82t1OqFHNw==,type:comment]
    RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:dv16bw==,iv:szylZUbZZ0SJ6P0cKfJNslOUWguJFAXgByjIwRez+JM=,tag:hzP+ILl2IzUYLyGwQTTGYw==,type:str]
    RABBITMQ_PORT: ENC[AES256_GCM,data:tDXCXw==,iv:KbTLtUQ+dCxG+aa8ilq8rXZv1fVS5rUAGMyDp/bcK7U=,tag:eTRqmrhdUV3gkthSqAxL8A==,type:str]
    RABBITMQ_HOST: ENC[AES256_GCM,data:8YFdHQcCaR1/pW9ExA==,iv:MDaVVZmHhHmTJv5EE25Pmf+kfcepurYp5AlABejE8QY=,tag:YkgPXxx6mqToigduJGK2xQ==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:wisAgKcQSkQg5MVpLOnAYEEe0F0wCsQ/YkYfvAJtVJ6F8+eVUmgGEB9aJZS0S7DSXM8=,iv:/e9ICu3xHia3/rmUOt5i0CBUGB5kpi1ux2/Bl9cIvDE=,tag:HWCRONFFdXX1kdqKkkmHsg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kyoo-secret
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:HgzU4VoKJSV0CVIBhf6leUuxA3kbGE8+QjP2rVcKgoyQNlpj1zcjOWQvFBEetLt+LzsDsOiWktfUb4x25AK5XW3t48xOI90HC/tE9ujNxZT/C1jX+lbu/dOfh3fMAumaf++iAZLLhA0TTFD6xfXvOblcubV8NOJ7fkK5kW8rr4GpLdkuCAWDPJ1HmFiqDPPiPpR5h7Pw84gGSmuSwCuLwx3zWyMTSedF5rYHNok/8wTCaQjn6iFr8YyJrrFTePh2deayUy+nbPMqgzPyOtW0Asavmibaiv25TJi8JmmzKzbJtKEfDqYKng9UeUx0RQ21yYNrmQd41joJv/oJ,iv:cvruHw8P5hIrKKFAjbCTVqlx7o+1pGeZyJfu3YpskXI=,tag:ZcWFXgkB/vDJPz3w8yCkkg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K5Uq/MJZAN2hflKTbKfYQ+FRR0DeiS8McS8ik3Jg1Z8jjSixvYtrNkEZvrMvtOotWk8igcOWVDQ17ZVTlQ0a+Q1hHX3GxdeWlHMJExayH8+KMNlPSqdR3DAMYEk1b3hjbXNnqnqohpYByZcdJgTM+W/0yB5jESuQ16WZz+UDjSulep0uXPAhuXzIFbISWgQYgcN9VdIdSNssKPBDLX9K/TRx7+qsRfos1cB7GTwcWb7C0nZJwmBZ9s1vhFFLIXNX709QoQ/4IjXFZuJRBP/o5xR2J2nmpb3Ef56y0Pj3Yjdqj60DMr+TlzxcDLzzsOfnkc8mNBZyX8Yr8C8F3jiFLMtDNGZd0hgTOx3LFKGpErD3VKwycSz8EGYayh9DGWukemS7/JAV0m2fM/Teuoqz10oASwLuT2zjiuX54K0ybKQVb7PnSZtRiPud7LF6PmIrwqJGdK5OCHX9rT0iBeiPRKCeDa02CXHWH8lkWQQB/sv1R1YDObZiVldZAU4yF4ypcsh6FmwAfQ16E5pR85oUyCDX5oW2wFqRaGmJ1Gc1E6pA+G0OkxoD46U2q2kEU1x2NfnVXDAH3ycBIZm3Y8wWFTFrsyzdN2qeVOCvtF1VaSLeEo+psN8qfricb0BaM2kSQboDTQmOhTUNDZwYl7h8pq+a5VVrXYOHOcWs8dwIyBJ1g8e3Yt794xjA9NRAAKzcCt+03ThLW/B/wcoshKV1MoZQ+lhObyZTO+k+I052xiQVcDpto1dcZ7IgMau10mChmFVX7+oVWcH7TtpOez3JGh6xI4HmHLNXDK+2KRimPoNaSbZx8EYqCmw5w44PISgPsWlTOywoyRU9D5UFAHVpMsyt75u1koi7O+JV+3DHYOvJXSsN6es0tzOYLJ4DL8xm2DWToq5n6W1TBtWi7yagdMOi03QWZOUx84P4AE16JYhIHX3Ru9aRZ5miZqe7Nj97f/+DhNJuNedX7QulrcmsWtXUfsIaucdysLOXcQxZ1slqnt3EczvrXsU6nnDc17AsB/sDVbzq13bWWEWrm6E+uCRmQ94+5GizFsLs1hHI/LC7a/jsv1ovZ0I/Waddsc2cO0H7r1ukHFKCI5x8SRhOe/ADbu3p1YKucYelkF9paGT4PVjmmYpA5/YiDRqki91M9jRu7ljm3nG5OnzOunSehGBjx1xbdYt5gb5pP/LzsWEfy9X0VOgLoBfSi/Og9TB0Gvb7+nOYte2nsSAZRMvFIjREB2WtoW6pzI2bS0icr8Ku16mg+U3vnM//HGW8rkc5bbpUIeKt4yMnl9r9ipd731ewpHC9JaqhHB6P4cI0pOYXQtAhJLtqghG+IJCMQqYapxhmjXU9WAY+zYvVpbqOhss6F7d/3wkY5J23wsNcOpwqRgznKmD63wfA/h7U8nVkGzbf7zHGtd8d+bXI13A9yS4frhHj07V5i8pS7a1Fngl3JlF1cN7JAOQ3Ei/ND2JGxWbWRstCWf39ahmHU8cbUWzkyqaZ3f1HVlYDxBT2a5iWoWbcsqzb47k91gq77li0VG4kLY5Q6qNF0XYA+lfHUTRxwPnSZiGhFu9PuP5YYz69ikrQ6OaEMkOn/743LxVIzUYgCHaY1hFMYGjH36JrsgsH4NaOR45RJqSi0PeiMu0Fk30eqV0yFKR5grSn7YFBrjQ9oWxfsTTpbLSDrz5W0kkYeJyrDX6EHxu7/MwJaCH2A+5JUvsMHYaa9mN2TRYaXV++++l1K6VgYsJQ9dyq36BMVzOzr0mq3zkUTvxTmqs5P06mlGZFvK+qA5EsM2BJJ2ZyA/Ipvmd8k7ExALLU90FFFezzlGEzGfG60rhytUitXwk9PfGk5Oo2lVCCVK6DynFSY5Cs8HOm5oMaURWOLn2PO/SrDtM10bKQmdJ6q1B36wAW/HO52RFLK/E7ojWcjJRppX5i6qNcJGXcEBCQRiKKbAe9I/AWP1XTErwLMrxnqEPR5nyROARohkJ5o2bSqgir0sAEZrZDrdoLO3QFUhlrWKEdztNJC+1YwM+qMxroHg7PKoBpsWQHtqzecdJ+7ZhFU5Kid1OLnqszolkXpB412gCd8bJmL8yQGWGZopm5kDZyl0uHH2zPbgODSCiBSWM6SCIK/MARiqYtAYbuIiFdIfFuRLm3PqRTRJkAka5tF5wLnd3jhAGvEO3qagFqxTsQVEuuJSVWTCXnfb7BLLF2i7wZB4K7vEbSRYvUmOefmfpwBm42Vt9CDVyWz1IbVxzHL6gvbjtVxmZXBoWSySHRSwmrPkUqK5dcvZRf/+QPCWVR0H4dO9IPhQdb6oYs7PUScJ5Oxvut2lELL92et0PEgGrT2p4h1ld+WYtYdgFl2//KBnEzjfR6loIbQzBiFnY0eUXEpp4Drhp/r9fSb8FI7fBsFSLCxvSwpbcSsWO7IhzpaMQIzrtikFVcBPhqIgI1peY+spercj6uxO28nFMSumguh4hsvsJ04/gpv8+k8Wa2xKZq7Rbi2KPnyfpFgfpdCYCDsfFDRsNuxJitTgTWM1bQjU6F6Lkwuo9qjgj4LF16Bcz5VnplFrPgy+j4XC1xMbTjP5aPWwh/h1bByXIL5mUaD1iRVWsf1jGYhJLgi+UQ5VnyA5raNUZ+4HfNnjjrTRtnAUGAcpNoHPxxxe906OPaT5TPJtKZm7QxMjxTqTsJ3J3RfI/pdjnUpyaYAI1aVRynsdYKMM85vsBRzQkZkxJyCK7p3bRQV53e/v/00nS7QPbgNrikFGbTeSbsLpCMCkPZ2iv+dItjjaL1rQKyOUN3xo2BUJ7WXpsLnbhzP/MUmu5NXOGiIOrFTHExXR98Wt8usW1smftwqUz4fPIg2zsK0xE69xSo+SIdPilGRimwiGIZ6/F6Omgg/yfOS1BjFgEME0NQsPpsbwcR1tvo8CgG1iaz/k74KsQKxx9/xw/HezBNgwKorp1+lyNaxpL5exXfTXZqme0hMZ3A7aC62hjRHoBDFyMhI3jrzVnMIzxDafmgaBDYCIlgkmD9Vtsuyt/Wow7A1MMOoEDLBzBUkMF9OB9DQxjFG/tl5smtvhuA+xEQ0AbLR1FKz1gXP6eHCNg4cU2Un+Lu3gXUfQK50P2kSq/GzZC/EHGhswJCrurFRbazdhp8Oj8TzXg9jEymev8y5/RmQtOwjlT84f2Y0GOyJspGX5wAZjta5eQ2p7UpL4Ap5M3RcvKyddKMv1X2us0yKizVoRP1D9hauEEy+KvDm9MFiBw93UqaPKIvEpiBt6R+B+7s0LeIqnnpx8/fMUiJU34RlDg2VbaWo7tO8HHV26g6Ft3kf55T7qwF/2zYiNp0nO9po6WeZ0nllFZOu7fDChQ1majMxesLvxNGI3wdWXccQN/xmAtZJsWQd038xBDTAcF7vguYcyRmORm6X7pUyRJr6TCC9gYz+S4b9e4DO/bNJ82AJtJNSmJN5KT4yoyfYYdrQ7dfjZTllhR6Qk2zZ+Vq7Q==,iv:1Vlc0d2XcA5e5lgl3k5zO+DsKJZhQ1CF6t4ZSMNCLB0=,tag:QSHf5BuzH6kHRK5mnu/0vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZKB+/vD0hNyUYGZZB1fuV5cRsE8JJGgAf42Wye8dmXuMtTQ6EeyZ6fzM3UO3LxvgrBt/Pc4oGkaAvo0oZwO4v9nlvdGLcfJFgmZkzVYGXjYJ/YMgXtKaV/KH9awaCs9FfKWsJf454OawWjPDXKJ997gnGNnBGvnE3GXiFwhkeIfFkGV3jawKC2gVGPaNBIuDD+kDf8x05JCvs4AadyweUxwymA6DZSf/LkdPQQ5V4u2nSN+PUr2JulWKDChnktTZV1/L9BXUxQxxvLcR17j6ogG14MTvizftYVDKYBCBJBHgN0BRxtIUihyGYjZtFvUGLyC4by68a7E3a92TDVrg8B6CroH/0J2Oh9gId0btpi4Wz1taH/e5hSN04CAbIWbUoe2w2p/JruH9otIrIVGCbOmj3XXquONgcxoIBVAdAbahDF/1B9cuPn1YcIpbtTZmC6zgg0HBVWvSfNY9v0nKaGmx44fUsXSvkw7zgohteTk2Hy0Nyzg7DBJZBmcj7dMA6o8k9kIsNAldgK5vqUD9YFG1WN05n9xq7nrEuPcbaFlMQ4ffBf2SAXHqgpz4DzGCKnevycJ000mT2bu9CBvWHod6RFLmRXh9M67JrmVqjYamYPtg3ab5gWuwcZaQs23QeS8gbr8KmNsWoktc8ABphaAFsly4xBmk3t2SlkapnuUlXti/w56BZPCGWiXGMdGwsyRE6aggWKuz3B2T3ObxRLeU3VcS+5qKPA==,iv:/8Mf6j3y1v9BOm3qGU8vPF5SuLKkBDF11J+w00C5Ss0=,tag:/HWjYRUBNYyOCZygu5MGPg==,type:str]
    known_hosts: ENC[AES256_GCM,data:REbx5VtIwci2SEMKV9dqjJJd00ZpH+LGWdBtcJPlJcQIGaBfUFnEfRRJRBM80C8xVIlySHvV6IjfXf1F8j7botWcIMEYzmiEibTKeFZ+HCn/GQUwdfK93ldchtbDY+f++TIdYW+GKGmBm4+Qmxj8SC/Nm1873OfECfkxXUpf1foRaSD/gy+5zOtwJM2+iJVidU1a6SsLIE3RxtZPYCrvlOKa0VuW97FRoXT/,iv:Z9fxSucpueiO8nbOnWnlwUiKmWqv4tjD8Zf8D7HDDy0=,tag:7KZ0TgNDdp/h0JADyL1bEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXJyWmpkdXV6cTJyM2Zq
            cTNQZXJRTmxFczlxMXY0ZFoyZFExaEhKVUEwCkdsaWNvZ1J6Qk1KcE1pc2g5RjlU
            a1NZdE9qVGdpRSthb1M0NUtjaDhPUUkKLS0tIE82d05BOXBDbm9KRGJES0duNlVx
            NTBtN3lCMllDazFwMDVPVEpyRUE3cm8KB+ruHS3eSomTUivcYYDJ/HlaD36K6+4P
            Rf+RfFodwiwRJLQzlQCUcncAH87a4h3rOt0bmGRpQLrcdH/aVgmNsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T07:09:28Z"
    mac: ENC[AES256_GCM,data:6BNGjV9Pdrh0rdLDgTgKMUcLFXINXGHyMX9J2WdAlTaRvgKhDUYVfuMA5tmP4eUgDCdn1HVBz1AR0yGqSuTNzCXfh/LNHWEd9mJTadon/Gv1oh+Wt3JyIDYTeXCm5bLFl97LsXt6LAGXIoXVV0y90nFbY34Z6cKRGCyg85AmZ9c=,iv:dUhUrr7Sk8EskRAU2615qAI9TgjOsvCMh/qcFx2TfoI=,tag:MEqMYCrrTEIC1bSpID+2nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
