apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7j5MYxQ=,iv:xAgCNrC1zWYpb5m9xqmSV+NSAR9NN8CR+X0W5X/Uok4=,tag:G0fzjvReMEbfBx42w2zkGw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:W0S6Vii7JH2GJI1kL+wpPUE=,iv:f46yilK1AyupEe+nY409iwdQLBUmkZltj1wzjetG2Xg=,tag:jnjBneV8PQUvKIrcZ3suIQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:1ZN0I8dbf6Cm8O01mE9N9+cFofQBYuftfS/KYA7A8WLabvGCpNsbMXMSx1zjDyR39EZJJZH28DGzd9Z6LyX68++Kmg==,iv:iqlRVNFRUv9+QZH399Wi/ZerKVgyvztOSthSt/55uww=,tag:gpLTVJN8F5Zga9uGx/lLyg==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:mQRJ5zK9RVseaoKg/MbiSaHajY6o3HcXLtT0tJvkkGnFVDixAlLHCH9DQXhtSeWoPZ99xHfhl24TxpcP,iv:2v/ZG5tPz9R+69Cr7QaK3WqAslxpn0ASZYMVad3QTYg=,tag:TNE4LPPiUZgHSk33R0+XoQ==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:kEGupU6vK4LGW1T6q4V90X0r0nGUz6bFT+UM90XUIqr1cCT+R75CwGjJfv6jn/3PRFxbadgwN3DTtrAgcbTQWw==,iv:TplZjN45BqTBpuwYpkYFV7MXWhjb77Wgmvk6RGrJ2hs=,tag:juBs+1e+eleJSq7TiYIWoQ==,type:str]
    KYOO_PG_PASSWORD: ENC[AES256_GCM,data:dNMVAYgpgQ9rsBvxgR5NrZjwAE4=,iv:MJqxdm2VE6UEPOcTruJGYr01NgGXDMiWv88sBySCbjU=,tag:ckuG5RKHZMxXcQYB4hFpDw==,type:str]
    GRAFANA_PG_PASSWORD: ENC[AES256_GCM,data:rjoi1ddik/P08P/lU5nUMw4E2eHByDm/uFRRLao0V66EwMvwcUV8+C4XEo4s+9tf,iv:Xi+pwGzBd0g38kwK05gfq/Lzwse3VaCWzXzg0u0sAe8=,tag:Fbd/+laca8Y+WZpaHx3E2g==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:DXixCVTA,iv:s4QkB8OafziCnEy52xjz0rb4W4f+YocZXTk89CHwQDc=,tag:wHmnNb+//E0aEkyDfYlypg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:3sdIbfeg+v65C8Z6z8G3UGXBMsjK7xfIFGquSAwIBp8FN0uEfh0I25EO89zSgMIRjNw=,iv:sn6ywWHxVXDoN2QucN7PaRGuGWerFv+tCI0FicPy3H4=,tag:I3OCNwcXzllSKu5BZXuWUw==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:l59fZpYjkzqZwosmiVY=,iv:g7pXs7ecX9VjfWHJMtrYPwRZCie4D7pFtnMRq7aWWyg=,tag:M89T0S03bIgIeWTkgStZEA==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:2EWOGsWh,iv:+tU7XQt0L9RtVPs1W6x6Hj2nuWVnJQAmJnsNka6mx3g=,tag:KAbWVUKl+Sl5qUzd6AuUTQ==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:Cq2GapaLUOFLWKDviKHJBU23yMmLmQj0seOczu7XnmGyx9+zpi/Spu/en6jRuUpx4FMFjBe5oxZUGnT8GBW1Uj4gOVSGQSq2ElYD7Esd6BXABvczsKi/PFHfwFW/aTYIpIQw6zZWwJXLzy4gfKhhe+1YDcg0hpob0sct8GzTILHPt2dhEVx/o1KcXnbAEfAQ9mgWE1oEqz8TOi0nbkByZNGz2OARQhvh2hh+1fVbgA1NvLPIUiko,iv:DrxjhWDQJysyAXDcuiq3OiM7a8L/yKMFWJH+CoD9zqo=,tag:4KhQKuxp5o7dEsYMd8T1WA==,type:str]
    SYNOLOGY_PASSWORD: ENC[AES256_GCM,data:BYm27Va61QVV,iv:OllOmv4lK4xa9ETEXwCIV/ZBxhLJZ4LkZEjIBLna+Kk=,tag:ktKTFdE0OiKv8wOe/dP7Tw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:C+jYnu07QcIZIdhOp72XMO6xW5tVuxpKaH5TCGmosNdnagoOdyOHXELioHdjlOYwsVMdoQYSb0E=,iv:6y0C2EWsFrD2GVwSSqwydXwTq/skKltGNGuGwQPysZM=,tag:DVTDMaiWIimyPEGW0fNpjA==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:92+zlgQl3H2XEZE/EUCez8VGDr167LqrA36l65vFu0ricNBhf8Ex6ecYMK6Lkw==,iv:nCKExfDtxNrv7i/JqZpNqS67IDHfBQ9MzAa5AxE5Ri8=,tag:Ggq2RjVoRFkQZqTqH5Digg==,type:str]
    TELEGRAM_CHATID: ENC[AES256_GCM,data:v59M5X3jGiadRT+Ybow=,iv:EWy24rHyzr45SGWFbETBJaIs0OzGWykEzHDkDKX5NhI=,tag:itThxcvpVqVzrSalBrm5Lw==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:d08cjsga,iv:fi62+dpTTs9UUur3dhc4ZC2iWnnIpVDaB+Lciaz6my8=,tag:1WDo8IQupcSMoGf9x4uo7A==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:IenoWzkQ6B7zKXWj2620qijnTiscW8T8pADSp7MHm2ned7i1eTNKAw==,iv:WSTF3G8vGvo8/GUVjm9Y/JvjO/r/zyO0fARHEZ8Sq9I=,tag:P1axkvVvIu0Eclg+9KAGAQ==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:MO0N29n9tyI3DpaDefGX0PU=,iv:0ZfChjoqBxeYxeaxedFtvNK0Uces4y22EA4I+xNTyrQ=,tag:EyMSQHsgGfkeET+oAgiLGw==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:J+ZA4IJq5RnxV00osahousodu6ODJOiscvqwq9VWPbGgPNhQ5New5XdQ9dCfDxWjH9w9er9faWb9h8hVnMro7g==,iv:xQH5blKxCvrO3YJGT6GdmYtvRuUVNGw7B0EtAUe5f+k=,tag:VgJlxAl5kuJ0eMvItJQOfg==,type:str]
kind: Secret
metadata:
    name: dns-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: net
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:dSpLFFZBrAawAMrZ7o1PvvLIvp92WsfjVZOCNd5g3gy9muduIZXeh1EqHBfYawZHPuep/qcG1go=,iv:vLsdEu9nKZbYu/uqD932emiPPzwsnXs+WDNa7kTfdz4=,tag:5Bz3spOAaPLp/w6eZNfFwA==,type:str]
kind: Secret
metadata:
    name: ai
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: selfhosted
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:huZDHiaRKXQ=,iv:+AHSGrxN7jCudvIIew1eRayZvV6B/w6ZQwXduVC9jEQ=,tag:DdP10w5CzOITdfx+xzOkjw==,type:str]
    password: ENC[AES256_GCM,data:NyWfvoymVGm6ABY8FaNfoWJnYDyJfYb3PTF8tVmq0SkZKoZxqP5d8No7TEc4fg4P82xT/uoVs2rg6zH5WZDAHw==,iv:l4yvGiZMlbhyLbKwOwjvWharb2WKBZsoGxrdCJT2PPE=,tag:CXL98Kl8LvytcHZ07LNP4A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:irHllYljW/g55ID55xqzR/qJs+k=,iv:a7kR38/z0hKx8KXgc2fCBA+/1KhFO2BzgRyb2NczG3I=,tag:NFT+k5tkQIw+QQRErXqfCQ==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:PwAqOYOw3FyH/RqhIMxVE7+LjSpbiY4dO/SWetkDb1Jghmn7L3cCMw==,iv:rYOSQ89zKgE7pAneHNKHjunn7pa32SHmbBjQup34UxA=,tag:0yph1PB3glm2x8X0tpn1sw==,type:str]
kind: Secret
metadata:
    name: pg-credentials
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media,db,o11y
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    KYOO_API_KEY: ENC[AES256_GCM,data:g84FLXRTMOGtdVDt0Fw55b9db3fFkLHPcCr8GYbSCE6k+VFCJnv8HxGI+ugNHI1rrZg=,iv:HrG54iD1cA8Z84o1bIaBevor6gCJ4G7f4H2nzyu+fQo=,tag:ijpKRvRIW8JU6OitoO0plg==,type:str]
    THEMOVIEDB_APIKEY: ENC[AES256_GCM,data:a2d6MQut3IOXeBMP9imyaZaL0I9pklFQGUO6k8QJT3A=,iv:v+/46kE3QFzGciFJVA2niRA90fpll8bjEVNSmfSvL1s=,tag:KmfeX4sne/NxVXjD4ASaYw==,type:str]
    #ENC[AES256_GCM,data:mGzYt68=,iv:wxHP5xtbJL0lvi3TvSRHcZQvSoT7epJnsjt/KItsLYU=,tag:kbCMEUwpxQXCo1tqmjuzeg==,type:comment]
    MEILI_HOST: ENC[AES256_GCM,data:IFMVveOFmnTZUQPVbnipNvXXVDpdg6sZFoaVEQ==,iv:x31sVRfx5J75Ietnz7/bpcTd215rJbW017OmY7Dj0NM=,tag:KLpzrwInr+CJgs7LkVUbQA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:/zIApJxcamj1cPedIqzsnoFTQbH7LMBxDF99QrImT6Soih/TA4IqgGFLzYCcssocets=,iv:cU31/Y17/1vk+Yg6WB2967vjn2tR22K4jeRnGZWskZQ=,tag:Qon9N9toT5SF1X4K9qG9wQ==,type:str]
    #ENC[AES256_GCM,data:VBYAyDSYGVk=,iv:Kvir3ZKzn0xHVzysbx8PMFDQU5Xm2pybqY/hC6rEquk=,tag:kr1BTZ71uf1AQWsbZngm9Q==,type:comment]
    RABBITMQ_USER: ENC[AES256_GCM,data:XFHPAA==,iv:uEiu8jL4g0CrYh/eubOLQs9GFfgepj6TMjs79D6NUS4=,tag:soK9QLiWJPt+IfDnISn8pg==,type:str]
    RABBITMQ_PORT: ENC[AES256_GCM,data:47Th4Q==,iv:Ix43WUBZT2hODa8vRTo42csbx7+fsAk05pkUwyNoggY=,tag:tM5+asFYynVEyQdKkdeCPw==,type:str]
    RABBITMQ_HOST: ENC[AES256_GCM,data:IJ8mvjhyB+kYV0ReJg==,iv:+9s6XH1pOipeol56WDforZJljcead+xp+Ct2n/BHdAk=,tag:EfYil7X18v2awCRwzdE+gw==,type:str]
    RABBITMQ_PASS: ENC[AES256_GCM,data:MyspNhcHZZ5HRoP64omNiaNUve/nErrWdHxnL7RIM0oxuWOWDj/6nPdYbla5cHDD1OI=,iv:1wxXUAD4PT4x9bdWUC3zFIMP+8w1TXZdgHuXFCFIv1A=,tag:wARgCcnbbXP62DBPk0WbUA==,type:str]
    RABBITMQ_COOKIE: ENC[AES256_GCM,data:pyH3pQ==,iv:d1oUoFG8ul9ary1gjX8iZ/x4dMQF32Y8WGcagCrZXfk=,tag:JN9FH8HDO6oHrkZk+49dcA==,type:str]
    postgres: ENC[AES256_GCM,data:InPnm+e88WI=,iv:+Ef3mE1pIhi+hgAToN/HW/IFLbdQrVDQOLLj5OsiXe8=,tag:il1nQMbvV2qGVlhuIAgPrg==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:boXJS90Zjt1BAcKn3c3kjfXYrcDodohiaiPZ8ou5hUX77quD8wvZV5UW0ZZY/ZXf/4uwjFG3RZVH5/UpQSWh7A==,iv:DvZGohmmo80qfllhBz+9aFoXtM/wX+bZQap6321ZkK8=,tag:j3maJbKkdyWqzBbQP8pZlA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kyoo-secret
    namespace: flux-system
    annotations:
        replicator.v1.mittwald.de/replicate-to: media
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:R3GVxZGN2XwNk6+blmLNiZ0jINYQQIQTgTELhfMqldt+3XDqW+556LPzoP9HKzdKQLWQ33xorppUpath3dHEn616gimJjQ5jTY1ASBhAJUcZBOe3XuwzLxf59SPkndks1zQG2Ptzdc2M2O4kYEOk+pls4Q9P9lk7lAqla+oww058YPci180fnOzz0gEboNs8ZPNlPAYgEPgtwijTw5tAoRaHYoLA8Q48Aul2nVWUteuzM9H3Nx4Ml++EJ9ZXg6xtjbgRGFoCDe3djSFRcKOBokqzLCG4MvKnqgonLXZpgz38u3OrHQb8D0CvbC1jN3VCdoEBM6TuQTUipNkf,iv:mhyNCayBzpGzVKX0PpdXBULTssUcYaetYWMus7i/bnI=,tag:W978FG6yAIy36LcHQkM5pg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gCVUt7DGmnE9qDQXKrQy9hTjfNSRjs4TBec9jM7DvbphowVZtG+jxvE5bTAD1lVMGPo2NRow3fbqgcrDEFmuEddFPge60sZ2pgD+kfIYKyAD+6gPOgsj1oiOvTrpx5ByDsz1ciXlw/elFAFCvgxP6o4AHE7k7jmJot8PXjmxekMfKxG22/s4oc+y3pS2L7LdhPyHsf5GZFQsMN0s3nWqCAmTFtLryMFPuBjxxaUx4E2cNFHE7LtGEDFgxPjbnO+wDcXTc+Vs7BNU/rD3bZfpxFhk9TAO1krB5RowDk20I4RDzNoMbOfw89kZZ9h89QwyZnyMdcSpCHR/mHto19vVlWsKKX0ibyVDnyi1LMbrMBai9LrXtK5eMTHIYMgXeZ2xL3Z3qKnYmVMnO3e5fchK+ginJHTmEJKih+wuUAdnG+CYNO4s29MhtyoFzchAhCerAt9Zer1yroN14pohGFd6/6BBpEpfWsYw+FHHijXoeQlJ5RW/u35Ya7PVgglAZ7SIyxGVaI4ZmAtCMaE0Gu5EDPX67xMJ9w2t23laE2l+cVCigznhTPYeJjUKTSoR++ddzK5F+ynX3bFGXX8/thqwcz0I2ukhPh4/7bTuPSKNmAZSGt6KGtOPanUli1boyWC02J7zUWPDp6pNtMSRW1Vnx7r138fMcUMWNYq/EH2dZ15PmwYl1iY7RUX8pRNL+pa8ECC1AkHgc53RuMCBZNbMptUrl48mHHDSxXnrjC6ediSauA961M+jBnEqiCT6ydw6vI/6CJofkXMTyC/s3OlW+ucppH5KMg1cFrMwAO1l3Drz8RBO+wBlgFrdhpg/qN5QVkFkETTw5QC6WYnTJXjaNz1OplVDEjTZe1q9Os7TOJ64nRFe2b3S8XwgRDneAIHY4zWC4y/fJrJgZGj1nOv3bDOgfo8KFmDchNFd1yBqpbiyd5N4hrJ4EF8MZx5rMYIP/zHp6OvSUkAb4YQ13xIw0jtTg4+06/s4qC+4p4v3qZxwkEH/iNjg/YpJOPFFU0P4jHH5VMR75pZgRtTM1T2cuHqCS/onBlebVxC5vbC999bT1zcBgknbxuvLL/4X/8y4ubYg+GEKAmO/EZyunTDxfcxjzQK3KS4qT3eivgx5VIFOrtW/vFo9UNSf8Vp+ChU+En/baoG5Qunf+ASonbZHiSP9K8ituplggK982M9k8rQQAbP21epR354/3zJpzPdQRHt+1Bf4Wr1jKaqfOUtsbzQytTtELiA6Ngvtc0J9f54jFG/5VLuDBvGCL/m6Y+S+MPrGmFYX7vpa03mvrZ7o+KqBDR+5+8CR3/y3zdHs017EVjAnwLOceOK+e3YvQdGcKh0xzIibHoZ/nqjWw/Cuuhfbuy35el0l6a+rP8sb4wIejMZS9PavzBUs9vJrs2q5ST44Q/npzngJVM2Rf62LnwbE1py0uwDaobYVEg+fL6+z3eBRIhze1as5/e99op4knVgGpbOsFbiZX7K6fI/2Q10zwGtjPbLS603UU9KmzVATZRLLIyIktE1YEsa+Pou4hQcc7IdFaRmnv4w3TC7Nltkg3a8rV7TeqQMZfIvHRdyIigwZky80y06pkVbkKVIHSYw6V4wRSdHIct6b6Q7uNNdWeCseUPIwDfaLTPv0xxZn0u8Dcm/adKYoYCEgri48iJXFSA3FaWPJ3mjOozk6iqBiCLDmgNBJDF/T+HFWrTohJQD9gFwBah7YYiWNjtHKQakRuXYL8YdFiwMmSyjptjSk/0V3/xZhLXe0iJTMwRdk6iyCTHyBAKAto/Q9A4YhtDrlBuopUfP3qJOTP/T/a6EITwkTBW66efvjrjwYSJieP34vaokcaOfwjNgJv8cwny/S9Jouq9suQphTsabRoUmLGYJwQ5D7PmPxVyW5F8EFT4Ypt9Aw8dZG96vVfaj/5D1a592QJfn/7+Tu8VUl5awBsUr7W8xGOrUmP+tD/kh9KoZjVEANzpuJyg/2Ne+x7OtucFWvF9rzyQId7gIgGsUTp56HJ7xDAvgbxfnzZnn9zx6qpUGEOUKLNx8KAdl40Q1pwAWn7r+DpqK6hg//KA7SPaZf5mOGPLzsprbVRi9UOLH+DLMNLdg2Ip98dop5jY0b+4SVgXgzPXrMxzwrvcN5BXutsnVZ+z5MolIb9HSLrdrAUrjvMHdN7sFcxYx0dTperWxguhG/v5/B3yQLPiFYiawQeRRV8Yfd9zB/MChRadYxKrgLt18t1Bz3GUK+RVuYcYeeu4kbJDxJK+l4qFqy2TDnLab61g/xplviDmBZUJtf+GZ28eLvUFxJIBgPS+WW3hvDhfMuTLE2i6cdj7kj0umWgXYmgw3xcRm9kTiXcrt0aL5FcUJLKwUSr6FPrjeGneqj6qBhidPMKo1yHFArCCkNlmEiyPBc5kK0E0w2eS1FTYwbgUw/zxEa8dzXsCbZXnfzBl9lV5xw67yFoP6kbVqoliVCDI3LJGKkE0hodYiHKLREiUEY9bzDCJKfLwaI9JuQlAGpcPGdGtTy/qsiUb/eE2rzPEw9TEGSRFkAzWHZHq5dRQ7Ks35NSpZmM+YnNDat7QhGP2xtN1HNd3cj9ktiKI4liCHJieNaid4rnJtdxu8nZ2l/dc1gMUxmqGl+xVup1RYAbM0yPi9waUxjiUQluLTCGMUdOX/vwi5j1+XRXyqf9ES3p6tba2H7DBHVXUHYU1YRtuMxJ6MmOrRvyOlBbTDL3qmo0G0z3p0w/Ajzcg2rxd2jP3XyDQQqOmN7QcSe9JR2pGq0/NZS9p7nQUxjBkOsJIRWslogiiv2OYqnLUDXmdgn6sQ55LvtH/31DOxYPzxl9psaGnh5l57TEuk0ugf8CV7H1p1x2OEjM4aIk9aReVNeuKZgqh4H8hSXOpLHk5satMb9ZZq9eCX9DSZWmYARr2UUmXT0OfWYBp8ffeQ3J8nJGz65N57e3jLtGwbQkqCnbJcy484uuzXXXKD+ziyl4E8Kmw3lr6kcfSNEXpEbuaSESv9/JAva5va3v4xq/Og+qxlEp0cwOEcxovPbIhQX50xvwHUgtdz0QSIu/j8rcjmhggcUeV010cZnOr8iGtez9q1WpTA0QpyS8KJpSJOmIIeFDtfcCbb6ZYCH9c4S4tZ6k77DF5emDq5lCaU9pQtBy6kxBIH0D1B5mSx3vFZjMFfMpVrqhglXKHFoULgVwG8nx63ik0kQ6XQ2ps4XkWdpZcYxjsK2kYV3Ks99D5/r7I9trvPLcgR3Rmf/gVbOhp19nK48X1n6mgOUiQax7VCRT4T0pHfYno+M8NPf5pEKXmX3QITvNLl6f01xWGVlzTQ/Yg16RlDmLXsFEm725NfgYjNMVixd9WWChEDXbKQxZ10c2NP7x+9tn6wLU2IOtHIke/f78ZFnv484a2dNgOpYrk1c/K3qzVYhNaAqzB9cUjKuqZGokjwbvcv9NIgXMSbI8eioVhpsgEPxIGnIxkCYWQ==,iv:o+e8LALQtabX2SYmfLbYNW5jRzFzWZI2fjRucC+DU74=,tag:BeyBmkpbhdHKomWII1Czgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:LQ1omSxaq7sKPafCFl7aob1C1A54cV1WRsWzNhBEVkm0sd0i71kYZwYbVjyJAOOMhClMzPyr23CyKNik7GWN/qVkQ6YIcKeBIS/FGGR4jEkVq8kJTBUzpsc38SIZ4p0zR9ONmcqhJdyD5nS9yh9vCmzHag/jJpgRofOW+zy1664rnMTfOychJT4wwBr6su+eSHO2xHcoeEwpB/LBPzTdEabW6bncPhTMVANlE9YC1xKAJVDjlpUYmqMI58n8KQt1+fS2Fu1eWG3Ak6Kzpj1bKgwQ9mYaTV2qiV1XIaNsRBBIj15f90G11/FCDviLOe9H7Tyd4hbsQRJVDrtWWVBo+WTBV7AO3a2O3aj/OOQDMc6vAKFDFnBY3p2IVpjpH4zADRDElGRtgjZoj/3kRD5ENrM8FbVlMQrttFMSLXzEX+wfxQDOoqNlT9w/BdLtd5UtG0ofWIlfyNPCf54Se/QSYqJFalRpjYuKRWWRSnzJSjp0yhxZ22c++aJJfzAeh6qaBu6Llepk/ubu9I5577cplahuc3FhtlzynESEQ6nkbVNvMEzWB1z4iatsGVsp8FoJFuIWfu2cVf5bDrzorY1xIkJ4fgh6aimTRfkYU/sVEvazhq4Bs/6Pjezyu5FZchumYTE0SUEXYnhjmYOPni6wZDlmPyB6Ts1kfQ7YDT3cCBtGa3J5OqRfq5tFthDIjJQIZHcGtXzRn433axQbSqR8MfeF1W1ZOlsufw==,iv:8++IaoMyfsTMuXN6OIWGnEVxdAxuB2CJC45QaYPcVBY=,tag:HSyuAevqf30crhTPs4sviw==,type:str]
    known_hosts: ENC[AES256_GCM,data:fVkd8LXIGK7wCcHpcpF8GhI7qz+50RpZFehZ/mFEgDJMtIq4anq1nNdhuM8lnChu9HcDmbVDVLAAtoiIlmrChPUAK9hkeT3gvqeA0Gvaf4IQ2SAqqkE9cwEBkOPeqowuKDgx6ryhv6kobkMAPvG+W/NbdGc7Yl/6n4DWc5uQbKVyuqWUldc7HnQhl4xMKvrx3BrL85q2qBTCqdHDqbg5h8kKA1hB7QxLLkh6,iv:/W9UalSJAzDIu7kiVs+0ArLSxaCvLsavbXmd3cQz/aU=,tag:h24tw9zaqmyPocI8/8TftA==,type:str]
sops:
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeDV2Q3JjMEVBS0pKeE5r
            aGxUeVFHem8zN01HQ1VkRURCRzVvalM5QkZZCnhMUGRVbWtPT3BrU1hXOFlUMTBW
            cnpoZjNMVEJBdytOV1NmdVAyek4xaVEKLS0tIDY2NDBPd2p2WU9ZY1RFZFFXQmVQ
            TzluNythRDAyOVdwanJwd1RYZkp6UmsKy/pqWpdd3f5FE7fCj9W5jADETmdtgefa
            1pW+++Bj2hNZ5kA5tpvD9TxdAFfd8Uxypzdv3RlLw506YNUEfBRxEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T09:32:31Z"
    mac: ENC[AES256_GCM,data:+IC2R0DqRThRKg5a9slIJLq2NU6YyyaeUFvGQAL7Nq43GAsD91tsbcCt053ZqLYecrvubPesIO3yqJUBZLRyiruSdRsoZVvZLdA/uenieVbeTEEwktrJu21+oPuWHawfr3D/DhQvlTxxIq5ALW6uSIpDD9/k5tve2fRj90vjf4c=,iv:0Ax/rMhgipxK9xkRhxHjDL5qA2dFdlz+dSyUyCPomAU=,tag:aXHJelIKVNvQkkxWnigZ2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
