apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:zfu6ElU=,iv:Xl9/RaBVpy1lvpxMDc4LLJ++X3d2U+8iWmHCs9DSLzc=,tag:mXX85w0ItsVNleMoUPv6zA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:YBO3ASWGJB3yxtTwGaopjBI=,iv:M6EPiBrlqU0E2iT5G3hRwaLfhhwaOPaJcTOZHG9ieDs=,tag:61SU4jY2kRI6aCmNGBcsBQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:1/XnTe7CQyLwcxZm2Y4OwBYRFY5zGkmKVGSOAT+LhXIsFyTjKbh1WdBD1yt09ikIzqRYQZp4zYPD3qfZFj1hoiz1WA==,iv:aMozaV3HzRIrzuMJVDjriYdbOqgTZiCY1f7VDR1bQSg=,tag:tLmYlpzbEi0nUyAGY0sngg==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:En92cUrejzmqz2QrvdjbluJLSCxZqzbFO3lBfIAFtn5jIU4D+Yad6/bdJpT4RQXtCQm9EqA3kmT6YX+/,iv:++waLqFrWobc0GZtMYb97b+YXz6YSOLZPVEq3aSsSEg=,tag:6NnHWVYpTYZ8vMNjwZTJUw==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:bVjY533LwHXeUZ7wHfV+Q1F8u7fJxSWVBusWZHLUuoS1czK/qSr73gWRg5UCHpY8msawSkAlaAhyJPRmseD7cw==,iv:CZlSoTaa4X1fKRPRSCkyjdI9Y9tdSJcx23DqmhnKt/0=,tag:xEbqCb69GOEwVavVImp+wg==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:dCk5HsLWb7V3Qt2dEdcFw7Ze4ArTBYhCowIv05/u+13kdkmtHFQcWCMq6Bi2w4dK0/0=,iv:Net7JckpfJwqI4a2Q9NYbnYKpk9+R4HpVgNEJaRT+dw=,tag:W0XmEth064hJxm6KyW36Kw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:Rlqfx6RFKv5tPTp6IeKTD0Ak88uur2fsK7FM+B3Xog0=,iv:H/dDM/vA0p6h91Oopn/5U8R7vmY7llqXtX9eUqSrWQM=,tag:s8owM8tueqxlDAeiUp//Cw==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:Jr3+riZjjK9ua40Wt/aOyMBfbO2GXANwOzmJTP7CZIbqdl3gVxZyvbuSSOfQmAHkLT0=,iv:WoYHP4mSo9LckS2YM30UNbcCeV41HLqwH0TfY/7GnXg=,tag:FU8tnLMVtcN+7T+3FYem1w==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:4BniQOsDme1jBE+EvhLR1YLTdOxunuoniOSi5T6WzWw=,iv:SQF+RzUO1SLzkCkLneyXWodYjAfZrL97ViwzUssUNy0=,tag:m6cEtnQmohaNqeYfXWHnpw==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:IWSCZ+cERnaj6Zv0CQ7CXjgtwZ9HdwxvL1jhHZ0ksHyjrwXjzxdvcz+geiFD+jmtmCg=,iv:Dtb2ah9Oam3+EN985Abpfelx3I86Z2o9ZlsGJ2vfeI0=,tag:X/izPEQD/MPUeBsZSg9TIg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:y2WGJs1QpANS7lxai4hrK8mtRcRVdyoMcxul6y9d92Y=,iv:UTfgunis1T38pccZuA1/JUmN/QlN2UsEIvzbOvt9xYE=,tag:8149yuHbTIXAmVZ5vzeLcw==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:c6wpFWOpSUZVIVhOgbSp2seMFJcEyRV/n67ZTagDRu394omj2zjya95NhW/fCT+2qTA=,iv:G7fce1wpX+TRcPLsv+dJROrVUGtxaq71NZStE7vQme4=,tag:bXpf57SRGAXmMU3W1qZNPQ==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:qezggeQthXk3i2+FEJU=,iv:01Iwt/52jDkKBzXLGHn4Uk7EtQCgDMWhl46WZ/MvPA8=,tag:Skb6Och3vED/a47NPBagMA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcDZ4Qjgwd1NKaUFlL2hK
            OUlJK2JKUitPeVY3Ri9ucU95bVkvUmovL3hZCmxwc05reVk3UHpUQ0ZTWnhpaGZt
            RTRFS05NMHR1eVE0TEtDMzFxTllDYjQKLS0tIDV2TmlsaVJzZWpNZ2IvUjlhaStt
            VlNRaGtYV3ZSWFJEdW1NN3pkTHlXUkkKaFBzyYQ1qPZm8q04HRG1eySuNXPwltU+
            CbfRZdTEylAwjvms6e3vDRQb9AegSxve9BSllweBBfyAktfgp6myBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T18:52:38Z"
    mac: ENC[AES256_GCM,data:NPuD2jTlOtpp3Q6GcbuPr3AwhB+TF8H28Yv8xemnH575JMngyMHsQeqfnukWAInJxjJKH0mJlMh37BQDhQjRI1LM5boW683PI5+Y0PAAokCy19djNsa2Ndj+/bVQ4/6gyze3XsHL2UWkuL0nM6l1u6RhbqTGFHdvaNAp7nZUoZQ=,iv:8BlilKSzuB6ZP0w/vDMr/0dIZrrZwlR4PLjqb3R9/ok=,tag:r85nnEn9LKUlSlV6K88sHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:Ej8ptCetU9g/cFOjzsgeYSou2pE0062L2akhD0vg1wDeUqRnMBC+cw==,iv:iG6JKw67lWJK2ZyWHCPWtbnMvuQnc1PJrboAk4I3OuE=,tag:qi0xd0BqfdmP5Sm8ld08qw==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:NbPfLe51An3NjjIp/FR6KDw=,iv:bfUBei9WeBGoVHjMFKBp21q6w4IuxEjC9PEo1MWUZck=,tag:RdEXX8bgKBDoo1fyc1uwQA==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:u8nA1k0CdV52pRrrsW12A3+2/AqF99FyuLQSOqqaGWpo2jR8pQO9bp6JwTyz0GILUHZPTio+v5olqAeGsS7wtQ==,iv:GOuumBvNnOR3MhCXLLsCAjcedCGwcXDMwr+zv9ayPNM=,tag:8lNtaVOX0tqWqub6XR0OWg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcDZ4Qjgwd1NKaUFlL2hK
            OUlJK2JKUitPeVY3Ri9ucU95bVkvUmovL3hZCmxwc05reVk3UHpUQ0ZTWnhpaGZt
            RTRFS05NMHR1eVE0TEtDMzFxTllDYjQKLS0tIDV2TmlsaVJzZWpNZ2IvUjlhaStt
            VlNRaGtYV3ZSWFJEdW1NN3pkTHlXUkkKaFBzyYQ1qPZm8q04HRG1eySuNXPwltU+
            CbfRZdTEylAwjvms6e3vDRQb9AegSxve9BSllweBBfyAktfgp6myBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T18:52:38Z"
    mac: ENC[AES256_GCM,data:NPuD2jTlOtpp3Q6GcbuPr3AwhB+TF8H28Yv8xemnH575JMngyMHsQeqfnukWAInJxjJKH0mJlMh37BQDhQjRI1LM5boW683PI5+Y0PAAokCy19djNsa2Ndj+/bVQ4/6gyze3XsHL2UWkuL0nM6l1u6RhbqTGFHdvaNAp7nZUoZQ=,iv:8BlilKSzuB6ZP0w/vDMr/0dIZrrZwlR4PLjqb3R9/ok=,tag:r85nnEn9LKUlSlV6K88sHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
