apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Khns7Ag=,iv:TRP8pawcDXqPjBnT/Nx4SVH3t+kasBpLbY8ccwY5wXY=,tag:267Ia910ySVZfGUhxLSTkA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:WXl2kB2fXV/areyvW+pTEXQ=,iv:yOgUkqwfjnLRuYrjqM364nE94aB2LiW5tQGSYJFRnwA=,tag:F0emi/i5r1WICxiKunEyIQ==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:pLhfGlPYOeyGUN36Pq3x177le0/59MnazvHhMNibOEQVTpgkz9taQhLWnaE6clvnDOKke8+cl5SrvIy0JLz/BIv9LA==,iv:+/FJgm4LS8Tjz6rOY1e0KvDOUS4aSExc0lzdkTLIu7o=,tag:g54XRPrc1T/7fONYM3Odgg==,type:str]
    WW_ADMIN_PASSWORD: ENC[AES256_GCM,data:JSLRxMyBQA0bQQew+PaaghzG+f8RFtLbJpWqGp5qpAdWxL2Zmo5YZ/RuGiVSDR++tFM1NMapz2sa3NhI,iv:zANoZD5i5GJkJpg5hdbOHdwBYMEoi2M4bXGXn0NnfEM=,tag:J7uXgDrlpPx6rS+p7cgsTQ==,type:str]
    SECRET_PG_PASSWORD: ENC[AES256_GCM,data:EnYPghEnQyWAgb7T4spUX0MXiAQ/7b/Dw2rlMDmm9bVsWrw0+pCWIMOK4+HSuhd8OKOe2crc6myxHxm7Bl2XLA==,iv:iA2Uvp2R8oPkD2xO8lIm0gTAClvx756HXTz9zEsFN0k=,tag:4VEO5MGMdQgsihZQHLRJbQ==,type:str]
    RADARR_PG_PASSWORD: ENC[AES256_GCM,data:GiHvT6v1y1OrEwomj2uRDe9SYenhEoQLNybdmwDU7BSNxixx6hPxxQwXope8k/2amWs=,iv:XkOUJSixLIIfGZLLulpxbfCLeu/Wa91uK7kgKlmJY5s=,tag:spZxCKya2nI40s7I1sNjAg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:/82Ga3HwPhRQ1U7cPXuk1+MBmG4v5EzvfF9sGeCh1/8=,iv:+TqSteQdHCXL8bfLBNLXuYLuyaUyT7IOQwryLqXmEB8=,tag:CyjAe7JP7i+kLom+1Zp/mw==,type:str]
    PROWLARR_PG_PASSWORD: ENC[AES256_GCM,data:y6AyWDhB9pRr3qSKT1mlZToAKDMnBLFPaOAp1xwmMPSq0CPvO9DZiH1Dhee5H/H5i2Y=,iv:5Ysy6U7FbZpcJn8hbANTa5t4YMy1/1Q4VEN+WMk6SyY=,tag:8wvMbRiRlsOHMIPIO4aggg==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:GorrCPFWWxD13DN4ODRQ6ndF3Myrd1ExKOikf4RZnZE=,iv:qadhne522yfnBM7bbdgbAv8+MxVBVlhjYzFyJhI4MIE=,tag:IOVkgPYz9g6oPH9gx2HAAQ==,type:str]
    SONARR_PG_PASSWORD: ENC[AES256_GCM,data:AGQG9FtfLwB8NG35eVLGJ60xgKylqW4aIGeA72HRGJumLSZa2Qrh8xr6phDNScAvhh0=,iv:j0PCB9bXDEOSsMvxVvyUy7voes/ia+CHNDLQT1ONjzM=,tag:gTVeQy2K+1U6Vg0RzRs5lw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:loCwbuntPxQAi9vioKxeIYnD1y536JD1zemFNQv0pGw=,iv:T5P+9iuELIqN47nf2vTypo7RwZvXkRRIpmE0UmEzJCo=,tag:I/csviPtqUUGkCcj7NJKtg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:VOdCgvqcjX3IidGy8pgs7dE3KtfEwFEQL3wGm69LKaDA0ghGvohciwZdNAJyyS4SmeM=,iv:YPEn/lrz8fATE7vmXv7JuJlkvkllJmkKKFWpKHrH6t8=,tag:Oyvh9gXKIGvpouvIE7YO2g==,type:str]
    EXTERNAL_IP: ENC[AES256_GCM,data:AyOzhYMIfB1xTLj21fM=,iv:9dxAF/7bj9+QLKJOwwCFfnPdtnomwaTsTnTqE7hCBZs=,tag:Tdf3tZCcMoxAprN8sZ9WRA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbnJzZXVSL1FEV1FmdXVy
            VjB1bFBQTW9vbC81QTg0bUVaQUNQRzlnS0FRClJ3dGdFQzRtVzlpVzJ4dVlCaU5I
            OGZQUmg0ZzFGMkV0bTllaVRQczRYbFUKLS0tIDh1SWlCNDIzV0pWclJ5Z0FSMUc5
            bXY1RllGdmFZdFZKeW10THZ6MWhpOHMKE64Cyco7qrqiMPnkstKJsVavLtUrqXpP
            94F14F89qq2ob3gR2KRc7c8ZUM+tHR2z+kCA8p6tmw9YfwaUNaMOKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T17:40:12Z"
    mac: ENC[AES256_GCM,data:Bf9TdqsdE69FVm8h0IfvNL+T7W+ckTU+89s2l4yiG5jsSAerjHAeg1VizI+I8dUEJjYJvLazGn3dVGVKbACt+OuuumhyenlW+KKJI4CrvNNnEYtX9dYqxIb9bAyopUnwlFwaV5jxrvjOc8mIL0EwBhggwsXRVdWeYj3xCtimdTA=,iv:K40Gp6BYFwRQ0L044BC/x7k0lNEEv6zXzdAmKpOemrI=,tag:42rKGdVWCEpTThJs8EunhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:dXtJcZsuQQ5VgDuuf1fDhQqfjrUJ6GmsruYPbsxMt4IUBM51D5gOiA==,iv:yyIrfkoHESZWmsaW8epIo4t2vrWNiA49N+V4WXW0Xjk=,tag:WRks9Q6j4+Z+xvWtGed/mA==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:xNUkk6WAKhSpWIrCHRsqbm8=,iv:6H2d9FvSS04S39OJwpzwQRO1XLf2Z07ZtCeGjNzADiY=,tag:njyznTSTgVidOnNc3O1Bgg==,type:str]
    LINODE_TOKEN: ENC[AES256_GCM,data:FiK6TT6yRzuF6nZnFAQtTHVli/PTcuSRD5GCEYnAxYmBAqRnYvZz4vYzVRiDbCC0Q0sWVdpAv757I74d7kReUg==,iv:W5HW+6SRwzWfM0Vbk409LLGmaPqsyzZRfXfjofW4L/g=,tag:GKPLC8yi3+smPDf4LhPXzw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cluster-secrets
    namespace: network
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g8nxh9vntdtkjmsav07ytqetpuh2524a7e98f6a77rulu4rzvgwstyvhru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbnJzZXVSL1FEV1FmdXVy
            VjB1bFBQTW9vbC81QTg0bUVaQUNQRzlnS0FRClJ3dGdFQzRtVzlpVzJ4dVlCaU5I
            OGZQUmg0ZzFGMkV0bTllaVRQczRYbFUKLS0tIDh1SWlCNDIzV0pWclJ5Z0FSMUc5
            bXY1RllGdmFZdFZKeW10THZ6MWhpOHMKE64Cyco7qrqiMPnkstKJsVavLtUrqXpP
            94F14F89qq2ob3gR2KRc7c8ZUM+tHR2z+kCA8p6tmw9YfwaUNaMOKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-22T17:40:12Z"
    mac: ENC[AES256_GCM,data:Bf9TdqsdE69FVm8h0IfvNL+T7W+ckTU+89s2l4yiG5jsSAerjHAeg1VizI+I8dUEJjYJvLazGn3dVGVKbACt+OuuumhyenlW+KKJI4CrvNNnEYtX9dYqxIb9bAyopUnwlFwaV5jxrvjOc8mIL0EwBhggwsXRVdWeYj3xCtimdTA=,iv:K40Gp6BYFwRQ0L044BC/x7k0lNEEv6zXzdAmKpOemrI=,tag:42rKGdVWCEpTThJs8EunhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
