---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/all.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CONFIG_TRUENAS_IP: 10.10.20.100
  CONFIG_MEDIA_UID: "2000"
  CONFIG_APP_UID: "568"
  CONFIG_APP_GID: "568"
