apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller
spec:
  chart:
    spec:
      chart: snapshot-controller
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    webhook:
      enabled: false
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 100Mi
          ephemeral-storage: 5Gi
