---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netdata
  namespace: flux-system
spec:
  path: ./cluster/apps/monitoring/netdata/app
  sourceRef:
    kind: GitRepository
    name: homelab
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
