---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dnsmasq
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx
      namespace: network
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        initContainers:
          init-main:
            image:
              repository: debian
              tag: bullseye-slim
            env:
              DNSMASQ__PORT: 9553
              DNSMASQ__ADDRESS: "/${SECRET_DOMAIN}/10.10.20.109"
              DNSMASQ__USER: nobody
              DNSMASQ__GROUP: nobody
            command: ['/bin/bash', '-c']
            args:
            - |
              echo port=$DNSMASQ__PORT > /etc/dnsmasq/dnsmasq.conf && \
              echo address=$DNSMASQ__ADDRESS >> /etc/dnsmasq/dnsmasq.conf && \
              echo user=$DNSMASQ__USER >> /etc/dnsmasq/dnsmasq.conf && \
              echo group=$DNSMASQ__GROUP >> /etc/dnsmasq/dnsmasq.conf && \
              echo "log-queries" >> /etc/dnsmasq/dnsmasq.conf && \
              cat /etc/dnsmasq/dnsmasq.conf
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 100Mi
                ephemeral-storage: 5Gi
        containers:
          main:
            image:
              repository: docker.io/bfenski/dnsmasq
              tag: 2.89-1
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
                ephemeral-storage: 1Gi
              limits:
                memory: 100Mi
                ephemeral-storage: 5Gi
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /etc/dnsmasq
            readOnly: false
    service:
      main:
      controller: main
        type: ClusterIP
        ports:
          http:
            port: 9553
            protocol: UDP
