---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dnsmasq
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: ingress-nginx
      namespace: network
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        initContainers:
          init-main:
            image:
              repository: debian
              tag: bullseye-slim
            command: ['/bin/bash', '-c']
            args:
            - |
              echo "port=${DNSMASQ_PORT}" > /etc/dnsmasq/dnsmasq.conf && \
              echo "address=${DNSMASQ_ADDRESS}" >> /etc/dnsmasq/dnsmasq.conf && \
              echo "user=${DNSMASQ_USER}" >> /etc/dnsmasq/dnsmasq.conf && \
              echo "group=${DNSMASQ_GROUP}" >> /etc/dnsmasq/dnsmasq.conf && \
              echo "log-queries" >> /etc/dnsmasq/dnsmasq.conf && \
              cat /etc/dnsmasq/dnsmasq.conf
            env:
              DNSMASQ_PORT: 9553
              DNSMASQ_ADDRESS: "/${SECRET_DOMAIN}/10.10.20.109"
              DNSMASQ_USER: nobody
              DNSMASQ_GROUP: nobody
        containers:
          main:
            image:
              repository: docker.io/bfenski/dnsmasq
              tag: 2.89-1
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /etc/dnsmasq
            readOnly: false
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 9553
            protocol: UDP
