---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tns-csi
  namespace: kube-system
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: charts/tns-csi-driver
      sourceRef:
        kind: GitRepository
        name: tns-csi
        namespace: flux-system
  values:
    truenas:
      url: "wss://${CONFIG_TRUENAS_IP}:443/api/current"
      existingSecret: "tns-csi-credentials"
    
    image:
      repository: bfenski/tns-csi
      pullPolicy: IfNotPresent
      tag: "latest"
    
    controller:
      replicas: 1
      logLevel: 4
    
    storageClasses:
      nfs:
        enabled: true
        name: tns-csi-nfs
        isDefault: true
        pool: "storage"
        server: "${CONFIG_TRUENAS_IP}"
      nvmeof:
        enabled: false
    
    rbac:
      create: true
    
    namespace: kube-system
