apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vm
  namespace: monitor
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.18.12
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    victoria-metrics-operator:
      operator:
        disable_prometheus_converter: false
    fullnameOverride: vm
    grafana:
      enabled: false
    coreDns:
      spec:
        jobLabel: "jobLabel"
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    prometheus-node-exporter:
      spec:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 200Mi
            ephemeral-storage: 5Gi
    vmsingle:
      spec:
        resources:
          requests:
            cpu: 200m
            memory: 1000m
            ephemeral-storage: 10Gi
#          limits:
#            cpu: null
#            memory: 1500m
#            ephemeral-storage: 20Gi
    vmagent:
      spec:
        externalLabels:
          cluster: lab
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 500Mi
            ephemeral-storage: 5Gi
      ingress:
        ingressClassName: private
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: VM Agent
          gethomepage.dev/icon: si-victoriametrics
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - agent.${SECRET_DOMAIN}
        tls:
          - hosts:
              - "agent.${SECRET_DOMAIN}"  # replace with your actual domain
            secretName: "agent-${SECRET_DOMAIN}-tls"
    alertmanager:
      ingress:
        ingressClassName: private
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Infrastructure
          gethomepage.dev/name: VM AlertManager
          gethomepage.dev/icon: si-victoriametrics
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - am.${SECRET_DOMAIN}
        tls:
          - hosts:
              - "am.${SECRET_DOMAIN}"  # replace with your actual domain
            secretName: "am-${SECRET_DOMAIN}-tls"
